### ISSUE TITLE
Glitches for certain CMP1 images

### ISSUE THREAD

**Issue by rr-** [morkt/GARbro#1]
I reversed GRP file format used by Brightia by Cronus+Riddle Soft and I ended up with the same code as you did - simple LZSS prefixed with original+compressed sizes and magic number. The format it compresses, rather than something custom, is just simple BMP.

It works for about 99% pictures, however, I found 4 of them that were glitched:

http://tmp.sakuya.pl/f/broken_gcp.zip (Note that all of them are NSFW.)

Example how it looks like (again, NSFW):

http://tmp.sakuya.pl/f/a16i.png

These pictures unpack incorrectly in both GARbro and my program. Not sure if the pictures alone are sufficient, perhaps one needs whole `Game.pac` to fully analyze the problem - unfortunately it's too big to attach here, not to mention copyright issues.

My insights:

- The glitches start in the middle of the image, meaning it indeed is compressed with LZSS.
- To me this looks like there's one byte flipped in some way in random place. Analyzing Brightia's code revealed nothing of this sort, though.
- Because of this, I thought it was PAC archive's implementation fault - there was one 32 bit integer I didn't understand what was for, but looking at your source code has shown it's just size of uncompressed file.
- Perhaps checking what WESTSIDE has to say would shed some light.
- Maybe it's a problem with my copy of the game, but I really doubt it.

**Comment by morkt** [comment]
that's a riddle, literally. i've retraced original RAGE code step-by-step and don't see how it could behave differently on the samples you provided. unless i've missed some well-hidden pak-contents scramble routine.

**Comment by rr-** [comment]
Hmm, I checked if [http://www.westside.co.jp/download/sale/20011010/asuhare.htm](WESTSIDE) knows any better and apparently it doesn't, since it unpacks glitched graphics too...

The only plausible ideas that come to my mind:

- both us and Japanese reverse engineers have missed something,
- my game copy is broken,
- the developers themselves distributed corrupted files (it's not that unheard of).

Closing this since everything else seems to unpack correctly.
