### ISSUE TITLE
Help, please add support files .cpz - Purple Software(パープルソフトウェア)

### ISSUE THREAD

**Issue by EAxp3** [morkt/GARbro#10]
Please support archive .cpz
extract archives cg :(

archive .cpz
images .pb3

CMVS

Extract Games
-Hapymaher
-Hapymaher -Fragmentation Dream
-Chrono Clock

Info Game:

https://vndb.org/p132
http://www.purplesoftware.jp/main.php

I need help please
there is no extract tool cg

Thank you
I'll be waiting... :)

let me know if you need the game files

Thank you

Please 

more information tools:
http://blog.sina.com.cn/s/blog_5e29812f0100r8ku.html

**Comment by EAxp3** [comment]
Crass
cui-zeas.7z
cmvs.cui   
https://drive.google.com/uc?authuser=0&id=0B6sGIpWwuzTMckhZMWNHSHFQSHM
info:
http://09pure3.blogspot.com/2012/03/cg_20.html?zx=3878786c51ae44c4
http://09pure3.blogspot.com/2014/09/cg_28.html

**Comment by EAxp3** [comment]
Test Implement Purple Software .CPZ and .pb3 images
:(

![archive encrypter](https://cloud.githubusercontent.com/assets/15073580/11616195/afc59c5c-9c3b-11e5-95f0-667eb9dcb783.PNG)

![image_pb3_1](https://cloud.githubusercontent.com/assets/15073580/11616199/c20bbb3a-9c3b-11e5-8509-6e5012fc80a3.PNG)

more information:
game files+others
link: https://mega.nz/#!AkoxCKKR!AuOucLZbt7adRUqI0Fc8upxEssPpIa64vnay82TfQiE

Please Support.....Thank you   ;)

**Comment by morkt** [comment]
wait for the next release when i'll update encryption schemes database.

**Comment by EAxp3** [comment]
👍 :mexico:
