### ISSUE TITLE
Game Request: Eiyu*Senki - The World Conquest

### ISSUE THREAD

**Issue by Gammokin** [morkt/GARbro#100]
[VNDB link](https://vndb.org/r54219)
File extension: DAT

Can you add support for this game?

**Comment by morkt** [comment]
i've added support in recent pre-release.

these archives don't store filenames, only their hashes and contents is encrypted based on file name, so if filename is unknown file contents would be inaccessible. i've added whatever filenames i could gather (they reside in `GameData/littlewitch.lst` file),  those that are not recognized will be displayed by their hashes (long hexadecimal strings).
