### ISSUE TITLE
File can't be opened as a resource archive

### ISSUE THREAD

**Issue by LonelyDoggy** [morkt/GARbro#102]
Файл не может быть открыт как архив ресурсов. Такое со всеми файлами. Абсолютно со всеми.
Я не знаю, в чём дело, использовал самую последнюю версию - **1.4.31.1932**. В то время как у моего друга всё работает, у меня же ни черта не работает. Я не понимаю, в чём дело. Не может же ни один архив из кучи игр не открываться вообще!

![1](https://user-images.githubusercontent.com/33221634/32168027-07c6e0ec-bd7c-11e7-97df-ae859816b3fc.png)

The file can not be opened as a resource archive. This is with all the files. Absolutely with all.
I do not know what the matter is, I used the latest version - 1.4.31.1932. While my friend is working, I do not have a damn thing. I do not understand what's the matter. There can not be one archive from a pile of games not open at all!

**Comment by morkt** [comment]
друг, тебе тут никто ничего не должен. если хочешь, чтобы тебе помогли, укажи название игры и вежливо попроси добавить поддержку. а вот это вот "чё за нах нихуя не работает" тут устраивать не надо. спасибо за понимание.

**Comment by LonelyDoggy** [comment]
Проблема не в поддержке игры, но я, конечно, сделаю реквест. Дело в том, что у другого пользователя в той же версии программы архив открывается, а у меня нет. Используем те же файлы. 
Даже те игры, в которых есть поддержка в списке, я пробую на них, и архивы также не открываются. 
Это совсем не здорово, может, я не так установил программу?

**Comment by morkt** [comment]
возможно, попробуй скачать из Latest release GARbro-v1.4.31-setup.exe и поставить заново.

**Comment by morkt** [comment]
closed as duplicate of  #103
