### ISSUE TITLE
Game Request: Boukyaku Shitsuji to Koi Suru Ojou-sama no Memoir

### ISSUE THREAD

**Issue by LonelyDoggy** [morkt/GARbro#103]
[VNDB link](https://vndb.org/v21534)

11 игра от **Campus**. 
Движок: **Malie**
Расширение файла: **.dat**.

Существует [all ages](https://cloud.mail.ru/public/Gvxb/tFATgkecH) версия и полная 18+ версия. 

Спасибо большое. Thank you very much.

![tw_icona](https://user-images.githubusercontent.com/33221634/32175460-1ab94a7c-bd96-11e7-9615-66cec5637664.jpg)

**Comment by morkt** [comment]
added in recent formats update. use check for updates menu option.
