### ISSUE TITLE
RenPy games

### ISSUE THREAD

**Issue by sim22x** [morkt/GARbro#104]
Can you add an algorithm for unpacking .rpa archive?
Like https://github.com/Lattyware/unrpa or https://github.com/Shizmob/rpatool
File example: https://drive.google.com/file/d/1pM8kxFEM74KWVmb_3F6X4FG7I1H_OF7J/

**Comment by morkt** [comment]
RenPy archives are supported to some extent. it would be easier to improve existing support if you name particular VN titles that are not recognized by GARbro.

**Comment by sim22x** [comment]
Sakura Halloween

**Comment by morkt** [comment]
fixed it and uploaded new pre-release.
