### ISSUE TITLE
Game Request: Yuuki Yuuna wa Yuusha de Aru

### ISSUE THREAD

**Issue by Teashrock** [morkt/GARbro#105]
[VNDB link](https://vndb.org/v16448)

Разработчик: **Minato Soft**
Движок: **Whale**
Расширение файлов: **.dat**

Заранее спасибо. Полная версия новеллы есть у меня на руках, если что.

**Comment by Teashrock** [comment]
Так, скачал релиз.

Я, конечно, подозревал, что увидит не все файлы. Но когда я открыл архив arc1.dat, мне написало, что он пуст! При том факте, что весит он 80 МБ. Можно это безобразие как-то исправить?

**Comment by morkt** [comment]
try new release. still, not all file names are discovered, so if you find out exact names of files that are missing feel free to post them here.

**Comment by Teashrock** [comment]
Names of found absent files:
S005_Z_0001
S005_Z_0002
S005_Z_0003
S005_Z_0004
S005_Z_0005
S005_Z_0006
S005_Z_0007

Can I write again in case I'll find more?

**Comment by morkt** [comment]
of course, although i'm not sure how to provide you the updated version, it's too little change to bother with uploading a new release.

also, it's crucial for file names to be fully specified for proper decryption. in this case, actual filenames are
    vo/005/S005_Z_0001.ogg
    vo/005/S005_Z_0002.ogg
    vo/005/S005_Z_0003.ogg
    vo/005/S005_Z_0004.ogg
    vo/005/S005_Z_0005.ogg
    vo/005/S005_Z_0006.ogg
    vo/005/S005_Z_0007.ogg

**Comment by Teashrock** [comment]
vo/005/S00
vo/005/S00
vo/005/S00
vo/005/S00
vo/005/S00
vo/005/S00
vo/005/S00
vo/005/S00
vo/005/S00
vo/005/S00
vo/005/S00
vo/005/S00
vo/005/S00
vo/005/S00
vo/005/S00
vo/005/S00
vo/005/S00
vo/005/S00
vo/005/S00
vo/005/S00
vo/005/S00
vo/005/S00
vo/005/S00
vo/005/S00
vo/005/S00
vo/005/S00
vo/005/S00
vo/005/S00
vo/005/S00
vo/005/S00
vo/005/S00
vo/005/S00

**Comment by Teashrock** [comment]
Ладно, тогда я лучше выкачу список, как он будет достаточно большой. Пока мне хватит.

**Comment by Teashrock** [comment]
Вот более полный список того, что мне нужно.

vo/001/S001_Z_0001.ogg
vo/001/S001_Z_0002.ogg
vo/001/S001_Z_0003.ogg
vo/001/S001_Z_0004.ogg
vo/001/S001_Z_0005.ogg
vo/001/S001_Z_0006.ogg
vo/001/S001_Z_0007.ogg

vo/002/S002_Z_0001.ogg
vo/002/S002_Z_0002.ogg
vo/002/S002_Z_0003.ogg
vo/002/S002_Z_0004.ogg
vo/002/S002_Z_0005.ogg
vo/002/S002_Z_0006.ogg
vo/002/S002_Z_0007.ogg

vo/003/S003_Z_0001.ogg
vo/003/S003_Z_0002.ogg
vo/003/S003_Z_0003.ogg
vo/003/S003_Z_0004.ogg
vo/003/S003_Z_0005.ogg
vo/003/S003_Z_0006.ogg
vo/003/S003_Z_0007.ogg

vo/004/S004_Z_0001.ogg
vo/004/S004_Z_0002.ogg
vo/004/S004_Z_0003.ogg
vo/004/S004_Z_0004.ogg
vo/004/S004_Z_0005.ogg
vo/004/S004_Z_0006.ogg
vo/004/S004_Z_0007.ogg

vo/005/S005_Z_0001.ogg
vo/005/S005_Z_0002.ogg
vo/005/S005_Z_0003.ogg
vo/005/S005_Z_0004.ogg
vo/005/S005_Z_0005.ogg
vo/005/S005_Z_0006.ogg
vo/005/S005_Z_0007.ogg

И да, всё-таки не пойму: мне говорить с тобой по-русски? Or maybe you prefer English writing?
