### ISSUE TITLE
Game Request: Yuuki Yuuna wa Yuusha de Aru S

### ISSUE THREAD

**Issue by Teashrock** [morkt/GARbro#106]
[VNDB link](https://vndb.org/v16682)

Разработчик: **Minato Soft**
Движок: **Whale**
Расширение файлов: **.dat**

Заранее спасибо. Полная версия новеллы есть у меня на руках, если что.

**Comment by morkt** [comment]
'Yuuki Yuuna wa Yuusha de Aru S' should be supported already, although these archives store hashes instead of file names, so not all files might be accessible.

**Comment by Teashrock** [comment]
Не открывается. Архивы "Юны" вообще не признаёт как архивы почему-то. Архивы "Юны S" оно признаёт и даже позволяет выбрать алгоритм! Я его выбираю и... И "файл не может быть открыт как архив ресурсов"! =_=

**Comment by morkt** [comment]
try [GARbro release](https://github.com/morkt/GARbro/releases/tag/v1.4.31), pre-releases may have missing some crucial files for these archives.
