### ISSUE TITLE
RPG maker games

### ISSUE THREAD

**Issue by sim22x** [morkt/GARbro#107]
https://github.com/uuksu/RPGMakerDecrypter
https://github.com/Petschko/RPG-Maker-MV-Decrypter
Can you add this algorithms into your project? :)

**Comment by morkt** [comment]
available in recent pre-release.

**Comment by sim22x** [comment]
Tool can't decrypt .rpgmvp files into .png 
Example http://dropmefiles.com/r0bRw
Check RPG-Maker-MV-Decrypter

**Comment by galtgendo** [comment]
Well, this is quite annoying to implement and - TBH - the javascript implementation is misleading.

Until/Unless upstream changes it, the simplest implementation is that Qt one, that's floating around.

There's a catch though: until/unless upstream changes it, decryption key is unique for each game and found in www/data/System.json. That is, of course, if the engine user didn't Enigma-pack their work, then you need to unpack that first.

**Comment by morkt** [comment]
i'm not interested in implementing RPG maker archives anymore.
