### ISSUE TITLE
GarBro not supporting .gyu files

### ISSUE THREAD

**Issue by Haiyami** [morkt/GARbro#108]
So I'm trying to extract .gyu files from Imouto Paradise. I see Garbro has support for Imouto Paradise 2 but not the first game.  Also if you could add an gyu to the create archive list that would be helpful.

**Comment by morkt** [comment]
can't confirm this. GYU images of Imouto Paradise are displayed just fine for me. also, GYU files are not archives, it's an image format. if you want to convert them to another format, use `Convert multimedia` option (`F6` key).

**Comment by Haiyami** [comment]
So if I extracted a gyu file as for example a PNG image, would using **create archive** repack the images?

**Comment by morkt** [comment]
there's no archive to create. GYU files ARE NOT ARCHIVES.
