### ISSUE TITLE
Game Request: 9-Nine- Kokonotsu Kokonoka Kokonoiro

### ISSUE THREAD

**Issue by 20100157** [morkt/GARbro#109]
I was trying with this, but no luck.

**VNDB:** https://vndb.org/v19829
**Developer:** Palette
**Engine:** Kirikiri
**Files:** .xp3

**Comment by morkt** [comment]
i've updated formats database, you may download it using "check for updates" menu command.

**Comment by 20100157** [comment]
Thanks! It works.

I was checking the configuration files, Initialize.tjs and similars are encrypted yet. Same for you? 

And why **2 startup**? 
![ipkhuvi](https://user-images.githubusercontent.com/24992464/33233822-db4dcb58-d1f2-11e7-942e-1eed5fb7aa32.jpg)

**Comment by morkt** [comment]
tjs files are not encrypted, they are compiled into bytecode. i have no plans to implement kirikiri bytecode decompiler.

as to duplicate startup.tjs, one of them is fake, the other is real, i don't know how to tell them apart, so both are shown.

**Comment by 20100157** [comment]
I see. Thanks!
