### ISSUE TITLE
Does anyone know how to rip the .cpz archives for the game?

### ISSUE THREAD

**Issue by EAxp3** [morkt/GARbro#11]
https://vndb.org/p132

https://s.vndb.org/cv/99/25899.jpg

Título	Hapymaher
Título original	ハピメア

Título	Hapymaher -Fragmentation Dream-
Título original	ハピメア-Fragmentation Dream-

Título	Chrono Clock
Título original	クロノクロック

https://vndb.org/v10957
https://vndb.org/v13108
https://vndb.org/v16208

**Comment by EAxp3** [comment]
GAME DOWNLOAD torrent
http://sukebei.nyaa.se/?page=search&cats=7_27&filter=0&term=%E3%83%91%E3%83%BC%E3%83%97%E3%83%AB%E3%82%BD%E3%83%95%E3%83%88%E3%82%A6%E3%82%A7%E3%82%A2

**Comment by EAxp3** [comment]
Does anyone know how to extract file .cpz? i'm trying to rip Hapymaher -Fragmentation Dream- using crass but unsuccessful. i think it's because the cmvs.cui is outdated (the newest one is 0.6.9 but i couldnt find any download link)

**Comment by morkt** [comment]
please don't spam, don't post download links, and don't use issues tracker as a message board.
