### ISSUE TITLE
Game Request [AkabeiSoft3] Mahoroba -Witches spiritual home-

### ISSUE THREAD

**Issue by Veshurik** [morkt/GARbro#111]
[VNDB link](https://vndb.org/v21455)

Разработчик: **AkabeiSoft3**
Расширение файлов: **.dat**
Движок: **???**

Спасибо большое!
![box_front](https://user-images.githubusercontent.com/26744056/33243128-21fb75e2-d2f1-11e7-9fc2-da2c10c6f3b1.png)

**Comment by morkt** [comment]
там плейдрм? если да, то не получится.

**Comment by Veshurik** [comment]
Когда появится взлом на игру, я вам его скину. А почему с PlayDRM не выйдет?

**Comment by morkt** [comment]
по-моему очевидно, почему. и не надо сюда ничего кидать, и вообще обсуждать это нежелательно тут.

**Comment by Veshurik** [comment]
Спасибо. В игру теперь можно поиграть.

**Comment by morkt** [comment]
добавил в новом пре-релизе.

**Comment by Veshurik** [comment]
Благодарю, попробовал. Пишут, что файлы не могут быть открыты как архивы ресурсов. 
![1](https://user-images.githubusercontent.com/26744056/33516432-bcf36d66-d783-11e7-9caa-981b72bcf1aa.png)

**Comment by morkt** [comment]
#20 скорее всего, анлочить дллки надо.

**Comment by Veshurik** [comment]
Хм... Посмотрел, ни один архив ни одной из визуалок не открывается, даже тех, что в поддерживающем списке. Очень странно. Проблема в самой программе? Вообще ни один архив не видит.

**Comment by Veshurik** [comment]
Благодарю, я просто тупой. Всё теперь открывается, кроме **data.dat**, но, думаю, так и должно быть. Спасибо.
