### ISSUE TITLE
Game request: PRICE

### ISSUE THREAD

**Issue by yaksamace** [morkt/GARbro#115]
Приветствую. Спасибо огромное за столь полезное приложение, однако с данной игрой что-то не то. При попытке открыть файлы *.XP3 приложение отвечает: "%FILENAME%.xp3: файл не может быть открыт как архив ресурсов". Перед этим я пробовал открывать файлы из игры посредством других утилит (xp3tools; AE - VN tools; kikiriki) и данные архив распаковываются (а в AE - VN tools можно посмотреть структуру архива), но содержимое не читается, ни скрипты, ни картинки, ни звуки.

Игру брал в Steam (бесплатная версия).

**Comment by morkt** [comment]
при открытии xp3 архивов должен выскакивать диалог с вопросом о способе шифрования. если его нет - значит, GARbro установлен неправильно, переустанови из [сетапа-экзешника](https://github.com/morkt/GARbro/releases/latest).

игра использует такое же шифрование, как и некоторые другие игры из списка, например, "Bra-ban!" - если выбрать её в списке, файлы в архивах должны стать доступными.

**Comment by yaksamace** [comment]
Да, всё так, как вы и сказали! Я использовал GARbro из zip-архива, т.к. подумал, что это портабл-версия. После установки появилось окно выбора и при выборе "Bra-ban!" файлы прочитались! Огромное спасибо за оперативный ответ и помощь!
