### ISSUE TITLE
Game request: Eden* (Mangagamer/english version)

### ISSUE THREAD

**Issue by verderojo** [morkt/GARbro#116]
Hello, I would like to request this game's version.
The japanese one has support on the actual resources, it has the same engine: Musica (*.paz files)

PS. I have heard that the english versions of minori's games use the original key (the jap) inverted. I hope that this can help

Thanks

**Comment by morkt** [comment]
added in recent pre-release.

> I have heard that the english versions of minori's games use the original key (the jap) inverted.

no, not really.

**Comment by kuhira123** [comment]
Was it really added, because it doesn't seem to work for me?

**Comment by ashSH** [comment]
Finally worked for me

**Comment by Mantas-B** [comment]
Doesn't work?
