### ISSUE TITLE
Game request: 	Mesu Ochi! Kyonyuu Tsuma to no Iyasare Love Onsen ~Kyonyuu Tsuma-tachi to Mi mo Kokoro mo Fureau Love Ero Seikatsu~

### ISSUE THREAD

**Issue by AlchemistofAtlas** [morkt/GARbro#118]
https://vndb.org/v21919

I'm interested on the character sprites of this game, but file that contains them is a psbpack.dat file. I can open it, however...

![screenshot_23](https://user-images.githubusercontent.com/20749122/34351303-73f5e6d2-e9e1-11e7-8962-871d4ad3ccef.jpg)

They''re all invalid file formats and cannot be opened as resource archives. I've seen other games with psb format that can be opened/displayed.

May I request this game can be supported to open/display those formats, please? Thank you beforehand.

**Comment by morkt** [comment]
i've added releavant key to formats database, you should be able to download it using "check for updates" option.

but those files wouldn't be of much use anyway, GARbro support of emote engine is very limited, and it just displays raw textures stored in PSB files. writing a fully-fledged PSB interpreter goes far beyond GARbro scope as a simple resource browser.

**Comment by AlchemistofAtlas** [comment]
Well then, was worth the shot. Still thanks for answerig.

**Comment by AlchemistofAtlas** [comment]
Oh, wait, it works now. Thank you very much. I can work on the rest now. Thanks.
