### ISSUE TITLE
Game Request: Grand Order Mahjong

### ISSUE THREAD

**Issue by YoxalLoyal** [morkt/GARbro#121]
http://www.dlsite.com/maniax/work/=/product_id/RJ215449.html
http://www.dlsite.com/ecchi-eng/announce/=/product_id/RE215449.html
Developer: Splush Wave
Engine: Unknown as it is Splush Wave's own engine
File Extension: .DAT

Is it possible for GARbro to support this game? I am having trouble extracting the CGs from the game's GOM_CG.DAT file. Thanks in advance.

**Comment by morkt** [comment]
try out new pre-release.
