### ISSUE TITLE
Game Request: Bitch Gakuen ga Seijun na Hazu ga Nai!!?

### ISSUE THREAD

**Issue by sim22x** [morkt/GARbro#122]
https://vndb.org/v21429
http://www.getchu.com/soft.phtml?id=967808
Developer: onomatope*Raspberry
Engine: ShiinaRio
File Extension: .WAR
Sample: https://mega.nz/#!3hFH2Thb!9Rv1nBENVbVsc6vxAqTPj62nWPd5EMbIdFzWeiG_Uow

**Comment by morkt** [comment]
it is supported for a while (#114), make sure to use the latest release.

**Comment by sim22x** [comment]
oh, nice
