### ISSUE TITLE
Game Request: Japanese School Life

### ISSUE THREAD

**Issue by anhhuyninja1234** [morkt/GARbro#123]
https://vndb.org/v18387
Engine: KrkrZ
Pls help and tks frist.

**Comment by morkt** [comment]
i've updated formats database, you may download it using "check for updates" menu option.

**Comment by anhhuyninja1234** [comment]
Can I repack the scenario?

**Comment by anhhuyninja1234** [comment]
And can you check this visual novel ?
https://vndb.org/v19513
i can't repack

**Comment by morkt** [comment]
i know nothing about scn files, so can't help you with them much.

**Comment by anhhuyninja1234** [comment]
ok, i have a last request game : ReLieF
https://vndb.org/v19587
Engine KrkrZ

**Comment by morkt** [comment]
it should be supported, have you actually tried to open its archives?

**Comment by anhhuyninja1234** [comment]
sr, my found @@ Tks for your all help.
