### ISSUE TITLE
ISO format

### ISSUE THREAD

**Issue by sim22x** [morkt/GARbro#126]
Может быть стоит добавить поддержку iso, как архив?
Мне кажется, это удобная фича. Можно сразу из образа распаковывать файлы, без монтирования/размонтирования.

**Comment by morkt** [comment]
я этим не буду заниматься.

потратить 1 секунду на дабл-клик, чтобы смонтировать, или убить 2 часа на код. не, нафиг.

проблема ещё в том, что при заходе в архивы внутри архивов, они распаковываются в память, и с большими файлами это всё будет дико тормозить.
