### ISSUE TITLE
Game request: Silverio Trinity

### ISSUE THREAD

**Issue by thecsf** [morkt/GARbro#128]
https://vndb.org/v19223
file extension: .dat

**Comment by morkt** [comment]
i've updated formats database, you'll need to download a new pre-release.

**Comment by thecsf** [comment]
Silverio Trinity - First Press Limited Edition data1.dat can't open file
https://vndb.org/r45697

**Comment by morkt** [comment]
are you using pre-release i've uploaded?

**Comment by thecsf** [comment]
Sorry.I got it wrong
