### ISSUE TITLE
Dies Irae DZI

### ISSUE THREAD

**Issue by kiraduwang** [morkt/GARbro#129]
Any support for converting dzi files? I'm trying to extract and convert them to PNG but Garbro doesnt support it.

**Comment by morkt** [comment]
dzi files are supported for [more than 2 years now](https://github.com/morkt/GARbro/blob/a6865194c48bb033029816053fd3d978691657a2/ArcFormats/Malie/ImageDZI.cs#L2). make sure to try [this release](https://github.com/morkt/GARbro/releases/tag/v1.4.33) before reporting errors.

**Comment by kiraduwang** [comment]
Woops, I downloaded the wrong version. Everything worked now, thanks for the help anyway.

**Comment by kiraduwang** [comment]
Alright the other dat files worked perfectly, but I tried to open data4 and it gave me an error. 

I'm using the steam version of amantes with the mangagamer uncensored patch. 

https://i.imgur.com/h7IzlRT.png

**Comment by morkt** [comment]
try to update formats database using "check for updates" menu option and see if it helps.

**Comment by kiraduwang** [comment]
That fixed it, thanks.
