### ISSUE TITLE
Please add support files .g00 preview images

### ISSUE THREAD

**Issue by EAxp3** [morkt/GARbro#13]
archive: .g00  -- It contains multiple images

Name: RealLive
Description: VisualArt's ScriptEngine RealLive
Archive:	.g00 .nwa .txt .ovk .cgm .dat .nwk

more information:
http://dev.haeleth.net/rldev.shtml
http://dev.haeleth.net/rldev/manual.html#htoc6
https://github.com/eglaysher/rldev

Thanks :+1:

**Comment by morkt** [comment]
probably not gonna happen.
