### ISSUE TITLE
Game Request: Silverio Vendetta - First Press Edition

### ISSUE THREAD

**Issue by Silence-s** [morkt/GARbro#131]
https://vndb.org/r36741
Developer: light
Engine: Malie
File Extension: .Dat

**Comment by morkt** [comment]
i've added key to the database, you may download it using 'check for updates' menu option.

**Comment by Silence-s** [comment]
Thanks

**Comment by hacker123-321** [comment]
Is there a way to repack the data.dat file of malie?
