### ISSUE TITLE
Game request: Doku Mail Series 1 - NTR - Seduce ~Netorareta Tsuma - Sefure - Kouhai - Imouto~

### ISSUE THREAD

**Issue by AlchemistofAtlas** [morkt/GARbro#132]
https://vndb.org/v21952

Game has no support, may I request if it can be supported, please? Tanks beforehand.

**Comment by morkt** [comment]
make sure to use the [latest pre-rerelease](https://github.com/morkt/GARbro/releases/tag/v1.4.34-pre2). it's actually supported.

**Comment by AlchemistofAtlas** [comment]
Updated it with the program's updater, but tells me that it could not be opened as a resource archive.

![screenshot_24](https://user-images.githubusercontent.com/20749122/34935824-c00677e4-f9a4-11e7-9a96-e8d0aa24da23.jpg)

My only guess it's because the link still points to 1.4.33 version, but even after updating it's still doesn't let me view the files.

**Comment by morkt** [comment]
no, you can't update to pre-release with built-in updater, you have to download it manually. pre-releases are kind of a test builds and therefore are not offered as an automatic update.
