### ISSUE TITLE
Game Request: [MangaGamer] Sorcery Jokers

### ISSUE THREAD

**Issue by shamashii** [morkt/GARbro#133]
https://vndb.org/r47518
Rio Shiina v2.50
GARbro-v1.4.33.2122
By selecting the existing Sorcery Jokers decrypt scheme will give invalid decryption scheme error.

P.S: For other games if confirmed in support list, just double click on war in garbro and  select right one dec scheme, and it will work? Need not to run game or other operation?(cuz I used use other tools they all do some hack like injection or somelse-- need running game)

**Comment by morkt** [comment]
i've updated formats database, you may download it using 'check for updates' menu option.

**Comment by marcussacana** [comment]
@morkt I have no idea if It's better create a new issue or use this, well basically have something wrong...
![https://pomf.pyonpyon.moe/absrcd.png](https://pomf.pyonpyon.moe/absrcd.png)
That files looks corrupted. (from SJSe_T.WAR)

**Comment by morkt** [comment]
see https://github.com/morkt/GARbro/issues/207#issuecomment-409173406
