### ISSUE TITLE
Game request: Dies irae ~Amantes amentes~ (Steam ver.)

### ISSUE THREAD

**Issue by minhrg** [morkt/GARbro#136]
![image](https://user-images.githubusercontent.com/20905553/35180312-321b980c-fde0-11e7-8c02-d5019adc3ca2.png)

Game has no support, may I request if it can be supported? Thanks...

**Comment by morkt** [comment]
this release is supported for quite some time already, make sure to use [the latest release.](https://github.com/morkt/GARbro/releases/latest)

**Comment by minhrg** [comment]
ok, sorry :)
