### ISSUE TITLE
Game Request: School of Fantasia

### ISSUE THREAD

**Issue by Veshurik** [morkt/GARbro#139]
**Developer:** [Tamamo Soft](http://tamamo-soft.com)
**VNDB link:** [https://vndb.org/v18237](https://vndb.org/v18237)
**Engine:** ???
**Archive files:** .pck

Thank you so much!

**Comment by morkt** [comment]
added in new release.

**Comment by Veshurik** [comment]
Спасибо большое! Всё работает, люблю.
