### ISSUE TITLE
Overlay ERISA/Entis images

### ISSUE THREAD

**Issue by rr-** [morkt/GARbro#14]
In [[SYRUP] [140131] 町ぐるみの罠～ 白濁にまみれた優理～](https://vndb.org/v15214) I stumbled across a kind of ERI images that our decoders are not capable of decoding - seemingly, not even ERISA library examples from 200x can decode it properly. After decoding, they look like this:

**Inverted colors**
![evet92](https://cloud.githubusercontent.com/assets/1045476/12077973/ea615644-b1fd-11e5-8498-edd6ef34c805.png)

**Downright glitches**
![evet93](https://cloud.githubusercontent.com/assets/1045476/12077974/ea65efd8-b1fd-11e5-9954-22aebe892eb1.png)

Points of interest

* The game .exe is unprotected, thankfully
* Most of the images work normally, problems are only with some specific images
* There are references to other images in `Header/descript` field, which is of following form:

        #hot-spot
        0,0
        #resolution
        0
        #reference-file
        evom09hf.eri

    The line endings are `\r\n`. Not sure if `#hot-spot` refers to coordinate where to put the overlay.

    Suspicion: perhaps this kind of comment is used only by this game specifically, and is not a part of ERISA library? Unfortunately I can't either deny or confirm this suspicion because the only other game I know that uses ERISA is Sakura Musubi from 2008, which doesn't even use `.noa` archives except for scripts.
* At some point, lossless decoder uses color transformations. Technically there are 16 possible color transformations, but all of the images so far used only some of them, and we implemented only those used. I thought the new images might use those unimplemented transformations, however, I quickly ruled this out - I verified that no new color transformations are used.
* Sometimes the actual bit depth doesn't match the one declared in the header. Besides that, header doesn't show anything suspicious (all values stay in the same range as in correctly decoded images, including version/architecture/transformation values).

I'll try to support them in my arc\_unpacker but if you nailed it faster, it'd be great :)

**Comment by rr-** [comment]
Mystery solved - all of those glitched images are just overlay images that are supposed to be added to the base image, rather than overwrite its pixels.

So to decode them properly, one needs to:

    1. Get base image from `descript` field
    2. Add pixels to the base image.

I'm not sure if alpha channel should be added as well. The only thing's that left is to figure whether this is only a quirk of the game in question, or a late extension to the ERISA library.

**Comment by morkt** [comment]
>  not even ERISA library examples from 200x can decode it properly

you probably missed it as sources for Erisa 3.0 available at their site contain full support for such images, file egl2d.cpp, method EGLAnimation::ReadImageFile

i was too lazy to implement all features of ERI format, so my code lacks it.
