### ISSUE TITLE
Game Request:Onii-chan, Kiss no Junbi wa Mada Desu ka? Ecchi no Junbi mo Mada Desu ka?

### ISSUE THREAD

**Issue by WARGBM** [morkt/GARbro#140]
https://vndb.org/v20003
Engine: Kirikiri
Files: .dpak
dpak is also  PSB file, Can it be supported?

**Comment by morkt** [comment]
added in new release.

**Comment by WARGBM** [comment]
Thanks

**Comment by UlyssesWu** [comment]
@WARGBM  I'm getting confused. Is it `.dpak` or `.dapk`? I have to say `dpak` sounds more reasonable but I just got a sample with `.dapk`.

**Comment by WARGBM** [comment]
@UlyssesWu 不好意思  文件格式其实是dpak，上次给你发的样品，格式被我改掉了，我也被混淆了。你更新后的工具，已经可以编译这种文件了，不管是dpak还是dapk ==  sry

**Comment by UlyssesWu** [comment]
@WARGBM Please, if you need help, you should always provide complete and real infos, or just say "IDK" or "I can't tell you because...". Don't add confusion since the truth will always be revealed sooner or later.
