### ISSUE TITLE
Question: How to calculate CpzEntry.CheckSum of ArcCPZ.cs

### ISSUE THREAD

**Issue by haniwa55** [morkt/GARbro#142]
Do you know how to calculate CpzEntry.CheckSum of ArcCPZ.cs?
I rebuilt the CPZ6 archive file that replaced some PB3 files.
The GARbro can browse the replaced PB3 files.
However, cmvs32.exe can not browse the replaced PB3 file with format error.
I do not know how to calculate the checksum of entry.
I tried it a lot but I could not ask for the correct checksum.
Please tell me that checksum calculation method if you know.
ArcCPZ.cs source program is coded only as reading from the index.
    entry.CheckSum  = LittleEndian.ToUInt32 (index, key_offset);

**Comment by morkt** [comment]
i think it's done by [this method](https://github.com/morkt/GARbro/blob/6c0f4657ac22b5cf038c4f71f7caf148a3b603d2/ArcFormats/Cmvs/CpzHeader.cs#L148), i'm not sure though.

**Comment by morkt** [comment]
this method accepts initial value of checksum as 'crc' parameter. entries checksum might use different initial value than index. try `0x5A902B7C`. also, checksum should be computed over encrypted entry.

**Comment by haniwa55** [comment]
That was a great answer.
The cmvs32.exe can browse the replaced PB3 files.
Thank you very much for your reply despite being so busy.
