### ISSUE TITLE
Dies Irae sub-archives

### ISSUE THREAD

**Issue by tahu157** [morkt/GARbro#147]
I know Garbro will already open the .dat archives for Dies Irae. However, within some of the initial archives are more archives that seem to be encoded differently. I can't seem to open them with Garbro. Am I doing something wrong or are the sub-archives' encoding not yet supported?

If you have the game, the sub-archive I'm looking at specifically is data3.dat/data/system/exec.dat which is supposed to contain the game's actual script files.

**Comment by morkt** [comment]
yes, this is a compiled script file and i don't have plans to implement a decompiler, so you're on your own.

**Comment by tahu157** [comment]
Gotcha. I don't really know anything about reverse engineering but maybe this'll be a good motivation to learn.
