### ISSUE TITLE
Формат текста и поддержка упаковки для Cyberworks / Crimson System

### ISSUE THREAD

**Issue by reyaz006** [morkt/GARbro#148]
Уважаемый morkt, недавно я отправлял письмо по адресу m********gmail, где описал запрос, но ответа не получил. Поэтому пишу здесь.
Имеется переводчик, который желает перевести на английский одну или более VN-игр от Cyberworks. Для этого ему нужна возможность редактирования и упаковки текстовых ресурсов. Эти ресурсы в данный момент распаковываются несколькими утилитами, в т.ч. GARbro, но не подлежат редактированию - нужно либо разобраться с форматом текста, либо добавить специальную обработку для распакованных текстовых файлов.
За рабочие инструменты переводчик готов заплатить. Дистрибутив первой игры я готов предоставить - он избавлен от протектора. Можно ли рассчитывать на помощь?

**Comment by morkt** [comment]
нет, это нудная и кропотливая работа, и мне даже трудно себе представить размер вознаграждения, который замотивировал бы меня в этом ковыряться.
