### ISSUE TITLE
При попытке извлечения F4 - файл не может быть открыт как архив ресурсов

### ISSUE THREAD

**Issue by Veshurik** [morkt/GARbro#149]
Trying to extract any file with **F4** or right mouse click - file can't be opened as archive resources.

File **ArcFormats.dll** already unblocked.
![2](https://user-images.githubusercontent.com/26744056/35801996-6ce51dae-0a7f-11e8-982e-93cc82fe3b9e.png)

_Version 1.5.34.2195_

Спасибо большое за помощь.

**Comment by morkt** [comment]
it's not an archive, it's an audio file, and it's properly detected as such, so there's nothing to extract. if it could be played, then you should be able to convert it to WAV format with `F6` key.

**Comment by Veshurik** [comment]
Ammgh, sorry, I'm so stupid. Thank you so much.
