### ISSUE TITLE
Add support---Archive .LPK  :)

### ISSUE THREAD

**Issue by EAxp3** [morkt/GARbro#15]
Please add: keys
 archive .LPK
GAME:[ [150227][WHITESOFT] さくらシンクロニシティ](https://vndb.org/v16215)

[tool-game not support](http://asmodean.reverse.net/pages/exnllpk.html)

sys
B5 B6 91 AE 5C ED 42 9D
chr
4E 99 C8 7D 99 24 E4 B6
pic
36 16 9D C6 69 B3 7D 38
data
C8 AA 4D 2D AE 75 5D E1

Thanks :)

**Comment by morkt** [comment]
added in v1.2.12

**Comment by EAxp3** [comment]
thanks I'll try :+1:  :tada:
