### ISSUE TITLE
Game Request: Sora no Baroque

### ISSUE THREAD

**Issue by YoxalLoyal** [morkt/GARbro#151]
https://vndb.org/v21524
Developer: light
Engine: Malie
File Extension: .dat

Not sure if this game is supported in your recent pre-release yet.

**Comment by morkt** [comment]
it is.

**Comment by YoxalLoyal** [comment]
Okay, thanks.

**Comment by morkt** [comment]
webp is fully supported for a very long time, i don't know what your're talking about.

**Comment by shamashii** [comment]
Sorry my miss, -v1.5.34.2240 seemed lack some file, after copy  ArcExtra.dll, x86/x64 folders from previous ver and unlock dlls, it worked like magic.
