### ISSUE TITLE
Question about Renpy

### ISSUE THREAD

**Issue by YoxalLoyal** [morkt/GARbro#155]
Hello. In some games like the fault series (https://vndb.org/v12694), the character sprites are separated by several pieces in separate folders along with a composite.rpyc file. Is possible for GARbro able to read this file and compose the parts together to make the full character sprites during extraction? Thanks in advance.
![screenshot 1265](https://user-images.githubusercontent.com/34036620/36069435-b6329edc-0eb7-11e8-8569-c17808150779.png)

**Comment by morkt** [comment]
no, it's not possible with existing interface. i suggest use ImageMagick if you want to combine such images. for example, laying one image on top of the other could be done with a simple command
`composite.exe face.png body.png output.png`
next step is to process all images with a script that applies this command to all body images in a loop. it could be done in any scripting language, for example, windows powershell, python, perl, unix shell, or even windows batch.
