### ISSUE TITLE
Problems with extracting images from Kadenz fermata//Akkord:fortissimo

### ISSUE THREAD

**Issue by YoxalLoyal** [morkt/GARbro#156]
Hi again. First I would like to thank you for your advice on the previous issue. I didn't want to post this on on the other issue's thread because they're two totally different topics so here's another issue I'm having. 

When I used GARbro to extract the character sprites from the game Kadenz fermata//Akkord:fortissimo, which uses both .CRM and .CRX extensions for sprites and CGs respectively, there are some images that contain grid-like patterns on the image itself. Are you able to fix that to make the image look like the second screenshot?

There are also times where I would not be able to extract some of the sprites (third screenshot) but I assume that is because those sprites are duplicates of a previous sprite. Thanks again.
![screenshot 1268](https://user-images.githubusercontent.com/34036620/36075250-4804792c-0f1a-11e8-923b-3aa8d4107919.png)
![screenshot 1269](https://user-images.githubusercontent.com/34036620/36075251-48103a28-0f1a-11e8-8d9a-1d8dfa30f36a.png)
![screenshot 1267](https://user-images.githubusercontent.com/34036620/36075279-aa0ac018-0f1a-11e8-8a86-9c6b8de8f199.png)

**Comment by morkt** [comment]
fixed in recent release.
