### ISSUE TITLE
Game Request: Nora to Oujo to Noraneko Heart 2

### ISSUE THREAD

**Issue by KiritoCy** [morkt/GARbro#158]
Here's a pic with the archives
https://gyazo.com/77050a54de68f87e7d3131cf44ea6eee

**Comment by morkt** [comment]
added in recent release.

**Comment by KiritoCy** [comment]
TNX ;D

**Comment by RECAE** [comment]
arc2.dat/z/st/-
Facial expressions are not synthesized for some standing pictures
I hope that you can correct it

https://i.imgur.com/0T1dv6p.png

**Comment by morkt** [comment]
nothing i can do.
