### ISSUE TITLE
About nitro+ *.npk (new format)

### ISSUE THREAD

**Issue by mireado** [morkt/GARbro#16]
nitroplus using new format on new 凍京NECRO(TokyoNecro).
![Imgur](http://i.imgur.com/S78Yxci.png)

Can you please support these format in later?

I attached some file on this address.
http://www.mediafire.com/?0rupvjuzz8jo0
(I want it could be a small help >_<// not including cg.npk/3d.npk/voice.npk)

Thank you >_<

**Comment by rr-** [comment]
The reading seems to be located in `Mware.dll` (MD5: `a757bd128af36a74cf966064948e52bd`) at `sub_14DD430`.

**Comment by morkt** [comment]
judging by the constants archive contents is AES256-encrypted.

**Comment by mireado** [comment]
AES256......... OTL...

**Comment by wfsaya** [comment]
could you please tell me what's the compression method of .nut file?

**Comment by marcussacana** [comment]
> could you please tell me what's the compression method of .nut file?

The nut files are decompressed

**Comment by MishaIac** [comment]
> > could you please tell me what's the compression method of .nut file?
> 
> The nut files are decompressed

Most likely .nut are compiled, but I don’t know how to decompile them. I urgently need help.

**Comment by wfsaya** [comment]
> > > could you please tell me what's the compression method of .nut file?
> > 
> > 
> > The nut files are decompressed
> 
> Most likely .nut are compiled, but I don’t know how to decompile them. I urgently need help.

实在不行就往小里翻译，应该也不难做到。

**Comment by marcussacana** [comment]
@MishaIac if you just wanna translate this can help you https://github.com/marcussacana/MwareStuff

**Comment by MishaIac** [comment]
> @MishaIac if you just wanna translate this can help you https://github.com/marcussacana/MwareStuff

Thanks!

**Comment by wfsaya** [comment]
> could you please tell me what's the compression method of .nut file?
> 
> The nut files are decompressed

but I can't read the .nut file /(ㄒoㄒ)/ could you teach me how to make them the format I can read?

**Comment by marcussacana** [comment]
I already said
