### ISSUE TITLE
Game request: Katekyo Shichao! ~Hitotsu Yane no Shita, Muhyohyo Gasshuku Monogatari~

### ISSUE THREAD

**Issue by AlchemistofAtlas** [morkt/GARbro#160]
https://vndb.org/v22043

Can I ask for this game to be supported, please? Thank you beforehand.

**Comment by morkt** [comment]
playdrm

**Comment by Lbzttt** [comment]
http://www.anime-sharing.com/forum/torrents-47/japanese-677202/

crack came out.
