### ISSUE TITLE
File names of Tanuki Soft games

### ISSUE THREAD

**Issue by Gammokin** [morkt/GARbro#165]
In the case of Tanuki Soft(たぬきそふと) games, extracted file names are mostly normal but some are abnormal.
[This is a sample image of 隣りのぷ～さん.](https://lh3.googleusercontent.com/KGsYFo8aJ1yEpV3nwSc1nHmwBCjNu8YdrLHFClh-sWaf1VMOI5qu7gdO-eUk_WBR6L6WLCVb01GXw0LibA=s0)
Would you mind if I ask you to solve this problem?

**Comment by morkt** [comment]
added some missing filenames in new release.
