### ISSUE TITLE
Game Request: Wonderful Everyday (Steam Version)

### ISSUE THREAD

**Issue by Protonium18** [morkt/GARbro#166]
Runs Buriko General Interpreter. Not sure if encrypted or not.
https://vndb.org/v3144
Filetype: .arc

**Comment by morkt** [comment]
are you sure it's not supported? try to open an archive and report results.

**Comment by shamashii** [comment]
https://vndb.org/r6173
I had this and confirmed work
ev in data02930.arc , select image manually

**Comment by Protonium18** [comment]
When I try to open that file, it says that it could not be opened as a resource archive.

**Comment by morkt** [comment]
most likely you've installed garbro incorrectly. try setup from the [latest release](https://github.com/morkt/GARbro/releases/latest). if archives still can't be opened, click help->troubleshooting->copy and post here a report.

**Comment by Protonium18** [comment]
Oh! That definitely worked! Thank you! I installed it and it worked correctly.
