### ISSUE TITLE
Game request: Riddle Joker

### ISSUE THREAD

**Issue by WARGBM** [morkt/GARbro#168]
Engine: krkrz
Files: .xp3
https://vndb.org/v22230
Can you add support for this game？
Thanks

**Comment by jszhtian** [comment]
Riddle Joker is differet with SenrenBanka.
M2 Krkrz change the Yuzu chunk.
This is the old chunk:
/*
cbg:
MAGIC[4]sen:
ChunkSize xx xx xx xx xx xx xx xx
NameTable POS:xx xx xx xx xx xx xx xx
OrigSize xx xx xx xx
Packed Size xx xx xx xx
hashKeyLength(need *2)xx xx
hashKey[]
*/
But in Riddle Joker, it is different.
/*
MAGIC[4]yuz:
ChunkSize xx xx xx xx xx xx xx xx
NameTable POS:xx xx xx xx xx xx xx xx
OrigSize xx xx xx xx
Packed Size xx xx xx xx
*/
the NameTable has been encrypted this time. use KrkrExtract or other tools can not directly dump the file from the XP3 Archive.
when you use process dump to dump the process or use ollydbg. You will find a hidden module at 0x10000000. it will handle this chunk and decrypt the encrypt NameTable.

This game just encrypts the first 0x100 bytes.
![default](https://user-images.githubusercontent.com/23244094/38139419-a3e5a722-342f-11e8-9641-427f6a8d039e.png)
![default](https://user-images.githubusercontent.com/23244094/38139153-8134aac6-342e-11e8-995c-eeb51d2f9b4d.png)

I think it should be some type of stream cipher algorithm. But i am not sure.
I have compare some XP3 Archives. This game looks like use the same key to decrypt the nametable part.
For krkrz, I can just write a dll and inject it to the Krkrz process. Then use TVPCreateIStream to dump the file if I know the file name. So it should be not very complicated for KrkrExtract. but for static dump tools like Garbro, they may spend more time to analyze the cipher algorithm.

**Comment by morkt** [comment]
added in recent release.
