### ISSUE TITLE
Game request : Kari Gurashi Ren'ai

### ISSUE THREAD

**Issue by KiritoCy** [morkt/GARbro#169]
https://vndb.org/v22045

Here's a pic with the archives
https://gyazo.com/2b196d9ec003d03652dfe6e67079c268

*Sigh* First Riddle Joker and now this. I can't extract sh*t with my current knowledge nvm getting and fixing the scripts again......Feels Bad

**Comment by WARGBM** [comment]
u can use the exe of Trial Edition to start  KrkrExtract , then unpack it

**Comment by KiritoCy** [comment]
Link pls?

**Comment by WARGBM** [comment]
https://github.com/xmoeproject/KrkrExtract
just now,it support the Riddle Joker unpack

**Comment by KiritoCy** [comment]
God Bless, krkrextract's maker for fast updates and y for fast reply tnx bro!
Note: still doesn't work on this gme though. Well, i'm still happy to get riddle joker's files in any case this one was a secondary vn i wanted it's files

**Comment by jszhtian** [comment]
Because the Krkrextract use a prebuild index to unpack Riddle Joker. If you want to use krkrextract to unpack the newest krkrz game. You need use ollydbg to dump the decrypted Special chunk yourself, uncompress it and save this chunk as xp3i.

**Comment by morkt** [comment]
added in recent release.
