### ISSUE TITLE
I can constantly inform you about many Vn Archives If Yr Interested

### ISSUE THREAD

**Issue by KiritoCy** [morkt/GARbro#173]
Well idk how rarely you wanna update and make a new release version of Garbro, but due to my work and research i constantly get new vn releases (I own over a hundred vns btw), and if you want i can keep telling you the archives of every one i get and tell ya if there's changes in their engines and etc. You can add me on Discord KiritoCy #6543 if y want.
If yr busy then nvm.

**Comment by 0xh3LL0** [comment]
well, i dont think company interested that much in developing new engine, they probably more interested using open source engine, or keep using their existed game engine and use their money/time to develop better security/anti-piracy stuff, so i dont think the game archives will be changes within games...
regarding morkt is busy or not, we dont know, but we know that he also have a real life things/stuff to do...
so if one of those archive is unpackable you can just fell free to create an issue here, as long as he dont say he stop developing garbro, we still have a hope.

**Comment by morkt** [comment]
just post an issue if you want some VN to be supported.
