### ISSUE TITLE
Game Request: Akatsuki no Goei Trinity Complete Edition

### ISSUE THREAD

**Issue by KiritoCy** [morkt/GARbro#174]
Here's a pic with the archives
https://gyazo.com/498f9ff94ca9fdec726ef8e16833d168

**Comment by morkt** [comment]
it will be added in the next release, in the meantime you could select any title with `AppliqueCrypt` encryption to access these archives.

**Comment by KiritoCy** [comment]
It's not that couldn't get the archives from this one, but this edition in particular had some different script decryption and i couldn't only get them so i tried asking you about it. Also don't worry, i'm working on getting the archives from around 10 vns at a time usually per month lel, and as for the actual number of scripts i get even you'd be suprised xd. Personally i wanted to discuss that much with ya personally on discord that's why i posted that a while back not like this on the issues

**Comment by morkt** [comment]
haven't noticed anything different with these scripts, it's plain text scripts in UTF-16 encoding.

**Comment by KiritoCy** [comment]
Hmm then it should be an issue with my converting methods or something i guess. Tnx anyway
