### ISSUE TITLE
support for .Bytes files????

### ISSUE THREAD

**Issue by Ygnes** [morkt/GARbro#177]
hello good morning I would like if you could help me to extract this type of files the .bytes

**Comment by 0xh3LL0** [comment]
hey mate, make it clear when you're asking, at least give us info like the game title or company
just asking for .bytes file wont give us any idea.

**Comment by Ygnes** [comment]
this game [https://vndb.org/v20293](url) Developer | noserious

**Comment by Ygnes** [comment]
this game https://vndb.org/v20293

**Comment by morkt** [comment]
added in new release.

**Comment by Ygnes** [comment]
thanks
