### ISSUE TITLE
Game Request: Yuusha to Maou to, Majo no Cafe

### ISSUE THREAD

**Issue by Veshurik** [morkt/GARbro#179]
VNDB: https://vndb.org/v22302
Developer: MintCube (CUFFS)
Engine: Kirikiri

Thank you so much!

**Comment by morkt** [comment]
added in new release.

**Comment by Veshurik** [comment]
Благодарю! Скажите, а планируется ли функция соединения тела персонажей и их лиц? Потому что делать это самостоятельно очень тяжело :( Спасибо за ответ!

**Comment by morkt** [comment]
такой функции не планируется. советую изучить какой-нибудь простой скриптовый язык типа питона и склеивать картинки с помощью ImageMagick, а не вручную,
