### ISSUE TITLE
Help, please add support GAME: minori (罪ノ光ランデヴー) 2016/02/26

### ISSUE THREAD

**Issue by EAxp3** [morkt/GARbro#18]
New Game 2016/02/26
Please add support Files

information: GAME:
[url1](http://www.getchu.com/soft.phtml?id=878766)
[url2](https://vndb.org/v17872)

I'm downloading process: GAME

Download Game: [DON'T POST DOWNLOAD LINKS FOR FUCKS SAKE --morkt]

thanks I hope you can help :)

**Comment by rr-** [comment]
Better not mess with minori:

- http://asmodean.reverse.net/pages/exef2paz.html
- http://mitiku3.jugem.jp/?eid=5959 (basically they mention a lawsuit against [ExtractData](https://github.com/lioncash/ExtractData/) authors)

**Comment by EAxp3** [comment]
you cannot create a version for private use
bad luck :(
Fail 
will wait to see if someone adds support: exef2paz_1.22r6 new version Chinese

**Comment by EAxp3** [comment]
[main.cpp.txt](https://github.com/morkt/GARbro/files/149288/main.cpp.txt)

**Comment by rr-** [comment]
The code is not an issue here. It's the potential legal issues.

**Comment by EAxp3** [comment]
ok thank you very much anyway
I do understand
:)

**Comment by morkt** [comment]
seeing as this code is [all](https://github.com/lioncash/ExtractData/tree/master/Extract/paz) [over](https://github.com/Ouroboros/Arianrhod/blob/master/Source/Unpacker/ef/exef2paz.cpp) [github](https://github.com/dsp2003/arc_conv/blob/master/arc_conv/arc_minori.asm) i doubt there would be serious complications. it's almost tempting to try and see.

**Comment by mireado** [comment]
Is it have legal problem?
um.. sometime, I was dreamed some tool could used for all engine.
I wish luck with development.

@EAxp3 if you need unpacker right now, try this.
http://tieba.baidu.com/p/4379949184
https://github.com/Inori/FuckGalEngine/tree/master/Minori

**Comment by EAxp3** [comment]
thank you @mireado 
if I could create a unpacker
I would not mind legal problems

"Thank you all for your great work" :+1:  :hammer:

**Comment by EAxp3** [comment]
@morkt I wonder if it will add support minori.
and if you tell me that it will not happen.
I want you please help me ported the tool fuckpaz C ++ to C #

I need help, I have translated a part of the C ++ code to C #,
but there are some things I do not understand.

I want to know how the program works,
but only I understand C #, I dominate more C #, so I want to port it to C # to add support same future
I hope you can help me or direct me what to do
on this topic.
I love this whole issue of the (Visual Novel Unpacker), I learn a lot about programming I did not know before.

this program is: [fuckpaz](https://github.com/Inori/FuckGalEngine/tree/master/Minori)

sorry for my English.
it is the fault of google translate

**Comment by morkt** [comment]
those archives might be implemented at some point, but i don't have any estimate.

as for the rest of your issue, sorry, you're asking too much, doing such "code review" goes way beyond my generosity.

**Comment by EAxp3** [comment]
ok, thanks be waiting the implementation

with respect to C ++ code,
I'll see how far I can get,
I'll keep studying to understand how it works
Thanks for answering. see what happens.

**Comment by EAxp3** [comment]
### great, thank you very much for implementation.
I've been waiting for a long time.
finally the dream came true ase. Thank you.

I'll check after my upgrade to Windows 10 anniversary.
thanks-thanks-thanks-thanks 👍  
I thank you very much for your very valuable work.
You are amazing.

**Comment by GalletaDeYomi** [comment]
O: Minori
