### ISSUE TITLE
Kanojo ga Ore ni Kureta Mono. Ore ga Kanojo ni Ageru Mono "Case 3"

### ISSUE THREAD

**Issue by OBSIDIANSWORD** [morkt/GARbro#180]
Hello,

Would you consider adding in the above to options available for RioShiina-encrypted games?

It would be much appreciated, thank you.

VNDB: [Kanojo ga Ore ni Kureta Mono "Case 3"](https://vndb.org/v14321)
Developer: Onomatope*
Encryption Scheme: ShiinaRio

**Comment by morkt** [comment]
i've updated formats database, you may download it using "check for updates" menu option.

**Comment by OBSIDIANSWORD** [comment]
Thank you very much, much appreciated.
