### ISSUE TITLE
Some Games Request: By Akatsuki Works

### ISSUE THREAD

**Issue by alittlered** [morkt/GARbro#182]
Developer: ALL by Akatsuki Works
Engine: ALL are Kirikiri
Files: ALL are .xp3

'&' - Sora no Mukou de Sakimasu you ni -
[https://vndb.org/v7636](url)

Hello Lady!
[https://vndb.org/v13631](url)

Hello Lady! -New Division-
[https://vndb.org/v15892](url)

Hi no Nai Tokoro ni Kemuri wa Tatanai
[https://vndb.org/v19369](url)

Suisei Ginka
[https://vndb.org/v20227](url)

ps: 
the "ALL" means only the games i list before

So it is just a request...

**Comment by morkt** [comment]
i've updated formats database, you may download it using 'check for updates' menu option.

**Comment by alittlered** [comment]
Thanks
