### ISSUE TITLE
Game Request: Anekouji Naoko to Gin'iro no Shinigami

### ISSUE THREAD

**Issue by ferdioz** [morkt/GARbro#186]
Would you consider adding in the above to options available for mirai/Minato Carnival-encrypted games?
it would be greatly appreciated, thank you.

https://vndb.org/v16066
Developer: Minato Carnival
Files: arc*.dat

![archive parameters](https://user-images.githubusercontent.com/39424140/40263717-bf728db0-5b40-11e8-9301-7e2e060fc207.jpg)

**Comment by morkt** [comment]
i've added it in a new pre-release build.

**Comment by Veshurik** [comment]
Oh, would be cool to do it for Destiny Star Girlfriend, trial version doesn't see all the files with your program. Thanks!

**Comment by ferdioz** [comment]
After updating the format database I cant open Anekouji Naoko to Gin'iro no Shinigami  arc*.dat file as resource archive now.

![image](https://user-images.githubusercontent.com/39424140/40594398-327e1e04-6259-11e8-98cc-af60d771b56f.png)

I can open it as resource archive before database update

**Comment by morkt** [comment]
probably you're experiencing #20
