### ISSUE TITLE
Catsystem2 *.hg3 file not extracted correctly

### ISSUE THREAD

**Issue by 0xh3LL0** [morkt/GARbro#187]
if the *.hg3 file contain multiple images, garbro read & extract only one of them...
garbro version: latest pre-release 1.5.37.2386

what garbro read
<a href="https://imgur.com/GcJuBkv"><img src="https://i.imgur.com/GcJuBkv.png" title="source: imgur.com" /></a>

what it should be extracted
<a href="https://imgur.com/3bGHKTp"><img src="https://i.imgur.com/3bGHKTp.png" title="source: imgur.com" /></a>

in case you need sample
[image.zip](https://github.com/morkt/GARbro/files/2021186/image.zip)

**Comment by morkt** [comment]
you could enter into multi-frame images by pressing `Enter` on them and extract all frames from the inside.

**Comment by 0xh3LL0** [comment]
whoops, looks like you're right...
when i just right click on it and choose extract, only 1 image is extracted, so i thought it was an issue...
