### ISSUE TITLE
Game Request: Kimi to Hajimeru Dasanteki na Love Come

### ISSUE THREAD

**Issue by Veshurik** [morkt/GARbro#188]
VNDB page: https://vndb.org/v22583
File format: .dat
Engine: malie

Thank you so much!

**Comment by morkt** [comment]
new formats database should be available now, use 'check for updates' menu option.

**Comment by Veshurik** [comment]
Unknown ,DZI format. Can't see any BG, CG or sprites.

**Comment by morkt** [comment]
#20

**Comment by Veshurik** [comment]
ArcFormats.dll unblocked. 
![dzi](https://user-images.githubusercontent.com/26744056/41037449-0ac2a8ea-699c-11e8-95f8-6bb5d847986c.png)
![2](https://user-images.githubusercontent.com/26744056/41037545-49c4dd88-699c-11e8-849a-7fae2db297b0.png)

I mean that. In data/picture/bg, for example. BGM playing. 

I can't understand what's wrong.

**Comment by morkt** [comment]
download [latest release](https://github.com/morkt/GARbro/releases/latest), install, click 'check for updates', download update, try then.

**Comment by Veshurik** [comment]
Using 1.5.37.2386.
Reinstall, trying to go to archive... When I click on .dzi - Unknown DZI tile format.

**Comment by morkt** [comment]
again, you're using pre-release.  [latest release](https://github.com/morkt/GARbro/releases/latest) has version number 1.5.37.2370. either use it, or unpack pre-release in the same directory as previously installed release.

**Comment by Veshurik** [comment]
With latest release it works! With pre-release - not. Thank you!
