### ISSUE TITLE
Game Request: Bitch na Anoko ni Seikatsu Shidou! JK Bitch Hamepako School Life Plus

### ISSUE THREAD

**Issue by SosFiro** [morkt/GARbro#189]
Hello. Is there a possibility to decompile and also compile the ".YPF" data file for this game? I saw that you do it with other games with this format, and I'm interested to open it for start a translation project.
Thanks in any case, and congratulations for developing this amazing tool! (The only one that properly extract WAR files, I think)

Info:
VNDB: https://vndb.org/r48888
Japanese Title: ビッチなあの娘に性活指導! JKビッチ★はめぱこスクールライフ Plus
Circle: PacoPacoSoft＋

**Comment by morkt** [comment]
i've updated formats database, you may download it using 'check for updates' menu option.

**Comment by SosFiro** [comment]
Thanks so much! 
But, for compiling again to YPF, what encryption and version I need to use? Tried to search on my own, but no luck on getting it.

**Comment by morkt** [comment]
use latest version, update database, choose "Bitch na Ano Ko ni Seikatsu Shidou! Plus" if asked. if there's no such option then you're doing something wrong.

**Comment by SosFiro** [comment]
I think I not explained my problem well. The decompilation works well, but when I try to compile the extracted folders again to YPF, I need to insert the "Archive Version" and "8-bit encryption key", and there's where I have no idea on what exactly is need to be put, to properly compile to .ypf and the game can load it.

Sorry if I bother you with this...

**Comment by 0xh3LL0** [comment]
@SosFiro maybe you can use AE, when using AE to open yuris archive it show something like this
![yuris](https://user-images.githubusercontent.com/23132217/41134482-bd0a26a8-6af6-11e8-9b15-705ac2be23db.PNG)
dunno if this is the correct  value to put though, but you can try

**Comment by SosFiro** [comment]
@0xh3LL0 Thanks! This works well. Finally, I can start translating the game.

As you say, the hex at the final of the format line is the encryption key, but you need to put it without the "0x".

Also, thanks @morkt for making your tool support the decompile and compile of this game and type of file. Very useful!
But, as a recommendation, it would be a nice idea to implement an autodetect of the version and encryption key when you open a .ypf file, so the compile function can be used with all games.

**Comment by Il-Sette** [comment]
@0xh3LL0 Sorry, I have the same problem with another game, but i can't find the program AE anywhere.

**Comment by Echoinsraht5** [comment]
May i ask the reason why after creating a archive file by in this way, it then turned out unable to run game correctly and produce a .crash.dmp file?
