### ISSUE TITLE
Unsuported PAC file from unknown engine

### ISSUE THREAD

**Issue by marcussacana** [morkt/GARbro#19]
This game (legal store url)
http://www.dlsite.com/maniax/work/=/product_id/RJ172521.html

Pac signature: PAC3 (0x50414333)
Can add support?

**Comment by marcussacana** [comment]
you can download the game finding for "RJ172521"...

**Comment by morkt** [comment]
i'll wait till it become a little more "mainstream" before trying to look into it.
