### ISSUE TITLE
Cannot Extract Half of Event CGs for light's Kajiri Kamui Kagura

### ISSUE THREAD

**Issue by YoxalLoyal** [morkt/GARbro#191]
Hello. I download the latest version and tried to extract the event CGs, but I get an error during the extraction about number 050 and onwards and GARbro does not continue extracting the rest of the CGs. This is for the original Kajiri Kamui Kagura btw. I'm not sure if the same error occurs in the Akebono no Hikari version. Could you fix this please? Thank you in advance.
![screenshot 1577](https://user-images.githubusercontent.com/34036620/41133794-f0c1445a-6a96-11e8-969a-2c89e471cf71.png)

**Comment by morkt** [comment]
tile mentioned in the error dialog is located in a different archive. for conversion to work, you have to extract all files from adjacent archives without conversion first (choose 'as is' format in extraction dialog), then convert extracted images using 'convert multimedia' function.
