### ISSUE TITLE
Formats.dat source ?

### ISSUE THREAD

**Issue by imKota** [morkt/GARbro#195]
Привет!
Могу ли я получить содержимое файла Formats.dat ?

**Comment by morkt** [comment]
да, в дебаггере visual studio, поставив брейкпойнт в функции десериализации.

**Comment by imKota** [comment]
@morkt можете ли вы отправить мне на почту **aleksey-nyaka@yandex.ru** не зашифрованное содержимое Formats.dat? 
Я был бы вам очень признателен

**Comment by morkt** [comment]
оно не зашифровано, см. выше. если это слишком сложно, то больше я ничем помочь не могу.

**Comment by imKota** [comment]
При сборке возникают проблемы. Те рекомендации что указаны в ссылке я сделал, но результат тот-же.
![1](https://user-images.githubusercontent.com/24241471/41608929-53285714-73f2-11e8-9129-85951cfb65c2.png)

**Comment by imKota** [comment]
@morkt допустим я хочу добавить новые игры. Как мне это сделать?
