### ISSUE TITLE
Game request: Hatarakanai Honey Life

### ISSUE THREAD

**Issue by Veshurik** [morkt/GARbro#197]
VNDB: https://vndb.org/v22335
Developer: LimeCat
Engine: Kirikiri
Format: .xp3

Thank you very much!

**Comment by morkt** [comment]
i'll add it in the next release, in the meantime, you may select `Se-n-pa-i ~Hiromi-senpai` when asked for a game title, it utilizes the same encryption scheme.

**Comment by morkt** [comment]
added in new release.
