### ISSUE TITLE
[SOLVED] Unable to open any archive - Unblocking "ArcFormats.dll" required

### ISSUE THREAD

**Issue by tenyuhuang** [morkt/GARbro#20]
**Solved. Unblocking "ArcFormats.dll" required.**

Hi, I've installed GARbro 1.2.15 and was unable to open any archive files.
When attempting to open supported archive, it returns "<FILENAME>: file could not be opened as resource archive".

Since I have limited games installed on my system, the only two games I tested was Symphonic Rain (HyPack) and Tokyo Necro (npk2). Both games failed to extract:
![qq 20160412054700](https://cloud.githubusercontent.com/assets/16178657/14443485/32925608-0072-11e6-8719-fdbafe6d2591.png)
![qq 20160412054818](https://cloud.githubusercontent.com/assets/16178657/14443496/418609f2-0072-11e6-9bbe-6d27202f86b2.png)
I can't tell if this is a file format issue or total failure at the moment, while another thing I've noticed is that the list is empty in "About Game Resource Browser":
![qq 20160412054823](https://cloud.githubusercontent.com/assets/16178657/14443518/5b0a2700-0072-11e6-8da9-cb74a2d95806.png)

I'm running GARbro 1.2.15 on Windows 7 x64 (Simplified Chinese) with dotNet Framework 4.6.1.
Could you kindly look into the issue? Thanks!

**Comment by morkt** [comment]
somehow you managed to install it incorrectly. make sure you extract ALL files from binary release archive.

**Comment by tenyuhuang** [comment]
I extracted all files directly from the latest archive, using WinRAR 5.31 (64bit). The folder structure extracted are as follows:
![qq 20160412144308](https://cloud.githubusercontent.com/assets/16178657/14451888/30aef1c0-00bd-11e6-89dc-c58fcbb8af71.png)
I compared these with the original package and no files seem to be missing. I don't use anti-virus software so it's not causing the problem, either.
How can I generate a diagnostic or something?

**Comment by mireado** [comment]
Did you have .NET Framework(v4.5)?
https://www.microsoft.com/net

**Comment by tenyuhuang** [comment]
> @mireado Did you have .NET Framework(v4.5)?

Yes, and I installed dotNet from the very link you provided.

**Comment by mireado** [comment]
Um...... 
How about installing latest version of 'visual studio 2013 redistributable'?
https://www.microsoft.com/download/details.aspx?id=40784

**Comment by tenyuhuang** [comment]
> @mireado 
> Um......
>How about install 'visual studio 2013 redistributable'?
>https://www.microsoft.com/download/details.aspx?id=40784

![qq 20160412213553](https://cloud.githubusercontent.com/assets/16178657/14461828/dbb24fb6-00f6-11e6-9123-3dc996b3372d.png)
They're already off to go. Updating the x64 redist to a more recent version didn't help, either.
This must be the weirdest issue I've run into recently :disappointed:

**Comment by morkt** [comment]
your setup prevents ArcFormats.dll assembly to load. the possible cause described here: http://mikehadlow.blogspot.com/2011/07/mef-directorycatalog-fails-to-load.html

to put it simply, when you extract DLLs from an archive that you downloaded from internet windows marks them with some sort of "this shit was downloaded from internet and therefore suspicious" label which then prevents .Net framework to load it normally.

now, to possible solutions: either extract binary distribution with some other software (eg. 7-zip), or turn off blocking manually by right clicking on ArcFormats.dll -> Unblock (don't know how it's localized, but it's the bottom button in the file properties dialog). or unblock .zip archive itself before extracting it, this would unblock its contents as well.

i probably should write a normal application installer to prevent such behavior, but i'm too lazy to implement it, sorry.

**Comment by tenyuhuang** [comment]
> @morkt 
>your setup prevents ArcFormats.dll assembly to load. the possible cause described here: http://mikehadlow.blogspot.com/2011/07/mef-directorycatalog-fails-to-load.html
>to put it simply, when you extract DLLs from an archive that you downloaded from internet windows marks them with some sort of "this shit was downloaded from internet and therefore suspicious" label which then prevents .Net framework to load it normally.
>now, to possible solutions: either extract binary distribution with some other software (eg. 7-zip), or turn off blocking manually by right clicking on ArcFormats.dll -> Unblock (don't know how it's localized, but it's the bottom button in the file properties dialog). or unblock .zip archive itself before extracting it, this would unblock its contents as well.

That worked: didn't realise the blocking stuff applies to DLL files.
And FYI, the "Unblock" button lies in the bottom of Properties dialog instead of appearing directly in right-click context menu (at least in Windows 7):
![qq 20160413062927](https://cloud.githubusercontent.com/assets/16178657/14477619/a309266c-0141-11e6-86df-ecddfc6cc0fb.png)

Thanks for the support!

**Comment by morkt** [comment]
>  lies in the bottom of Properties dialog 
yeah, i meant exactly that, just worded it incorrectly.
