### ISSUE TITLE
EntisGLS - Bad Filename encoding?

### ISSUE THREAD

**Issue by marcussacana** [morkt/GARbro#202]
Well, I tried extract the script.noa from https://vndb.org/v22776 (All Volumes Pack edition)
And well, the result:
![https://pomf.pyonpyon.moe/ofnfgd.png](https://pomf.pyonpyon.moe/ofnfgd.png)

Any other file with ascii names works without problem.

(I think is utf8 and the GARbro is using 932)

As aways, thanks for the tool.

**Comment by morkt** [comment]
you may now choose NOA archives encoding in preferences (ctrl+P).

**Comment by marcussacana** [comment]
Thank you
