### ISSUE TITLE
Yuuki Yuuna wa Yuusha de Aru S: глюк в игровых архивах

### ISSUE THREAD

**Issue by Teashrock** [morkt/GARbro#206]
Тоже самое, что и в #205 , только список файлов шире.

Лежат, как обычно, в arc0.dat и arc2.dat/z, папках 005S, 005M и 005L.

S005_1AA1BA_000_S.tlg
S005_1AA1BA_010_S.tlg
S005_1AA1BA_020_S.tlg
S005_1AA1BA_030_S.tlg
S005_1AA1BA_040_S.tlg
S005_1AA1BA_050_S.tlg
S005_1AA1BA_060_S.tlg
S005_1AA1BA_070_S.tlg

S005_1AA1BA_000_M.tlg
S005_1AA1BA_010_M.tlg
S005_1AA1BA_020_M.tlg
S005_1AA1BA_030_M.tlg
S005_1AA1BA_040_M.tlg
S005_1AA1BA_050_M.tlg
S005_1AA1BA_060_M.tlg
S005_1AA1BA_070_M.tlg

S005_1AA1BA_000_L.tlg
S005_1AA1BA_010_L.tlg
S005_1AA1BA_020_L.tlg
S005_1AA1BA_030_L.tlg
S005_1AA1BA_040_L.tlg
S005_1AA1BA_050_L.tlg
S005_1AA1BA_060_L.tlg
S005_1AA1BA_070_L.tlg

S005_1BA1BA_000_S.tlg
S005_1BA1BA_010_S.tlg
S005_1BA1BA_020_S.tlg
S005_1BA1BA_030_S.tlg
S005_1BA1BA_040_S.tlg
S005_1BA1BA_050_S.tlg
S005_1BA1BA_060_S.tlg
S005_1BA1BA_070_S.tlg

S005_1BA1BA_000_M.tlg
S005_1BA1BA_010_M.tlg
S005_1BA1BA_020_M.tlg
S005_1BA1BA_030_M.tlg
S005_1BA1BA_040_M.tlg
S005_1BA1BA_050_M.tlg
S005_1BA1BA_060_M.tlg
S005_1BA1BA_070_M.tlg

S005_1BA1BA_000_L.tlg
S005_1BA1BA_010_L.tlg
S005_1BA1BA_020_L.tlg
S005_1BA1BA_030_L.tlg
S005_1BA1BA_040_L.tlg
S005_1BA1BA_050_L.tlg
S005_1BA1BA_060_L.tlg
S005_1BA1BA_070_L.tlg

S005_1CA1BA_000_S.tlg
S005_1CA1BA_010_S.tlg
S005_1CA1BA_020_S.tlg
S005_1CA1BA_030_S.tlg
S005_1CA1BA_040_S.tlg
S005_1CA1BA_050_S.tlg
S005_1CA1BA_060_S.tlg
S005_1CA1BA_070_S.tlg

S005_1CA1BA_000_M.tlg
S005_1CA1BA_010_M.tlg
S005_1CA1BA_020_M.tlg
S005_1CA1BA_030_M.tlg
S005_1CA1BA_040_M.tlg
S005_1CA1BA_050_M.tlg
S005_1CA1BA_060_M.tlg
S005_1CA1BA_070_M.tlg

S005_1CA1BA_000_L.tlg
S005_1CA1BA_010_L.tlg
S005_1CA1BA_020_L.tlg
S005_1CA1BA_030_L.tlg
S005_1CA1BA_040_L.tlg
S005_1CA1BA_050_L.tlg
S005_1CA1BA_060_L.tlg
S005_1CA1BA_070_L.tlg

S005_1DA1BA_000_S.tlg
S005_1DA1BA_010_S.tlg
S005_1DA1BA_020_S.tlg
S005_1DA1BA_030_S.tlg
S005_1DA1BA_040_S.tlg
S005_1DA1BA_050_S.tlg
S005_1DA1BA_060_S.tlg
S005_1DA1BA_070_S.tlg

S005_1DA1BA_000_M.tlg
S005_1DA1BA_010_M.tlg
S005_1DA1BA_020_M.tlg
S005_1DA1BA_030_M.tlg
S005_1DA1BA_040_M.tlg
S005_1DA1BA_050_M.tlg
S005_1DA1BA_060_M.tlg
S005_1DA1BA_070_M.tlg

S005_1DA1BA_000_L.tlg
S005_1DA1BA_010_L.tlg
S005_1DA1BA_020_L.tlg
S005_1DA1BA_030_L.tlg
S005_1DA1BA_040_L.tlg
S005_1DA1BA_050_L.tlg
S005_1DA1BA_060_L.tlg
S005_1DA1BA_070_L.tlg

S005_1EA1BA_000_S.tlg
S005_1EA1BA_010_S.tlg
S005_1EA1BA_020_S.tlg
S005_1EA1BA_030_S.tlg
S005_1EA1BA_040_S.tlg
S005_1EA1BA_050_S.tlg
S005_1EA1BA_060_S.tlg
S005_1EA1BA_070_S.tlg

S005_1EA1BA_000_M.tlg
S005_1EA1BA_010_M.tlg
S005_1EA1BA_020_M.tlg
S005_1EA1BA_030_M.tlg
S005_1EA1BA_040_M.tlg
S005_1EA1BA_050_M.tlg
S005_1EA1BA_060_M.tlg
S005_1EA1BA_070_M.tlg

S005_1EA1BA_000_L.tlg
S005_1EA1BA_010_L.tlg
S005_1EA1BA_020_L.tlg
S005_1EA1BA_030_L.tlg
S005_1EA1BA_040_L.tlg
S005_1EA1BA_050_L.tlg
S005_1EA1BA_060_L.tlg
S005_1EA1BA_070_L.tlg

S005_1FA1BA_000_S.tlg
S005_1FA1BA_010_S.tlg
S005_1FA1BA_020_S.tlg
S005_1FA1BA_030_S.tlg
S005_1FA1BA_040_S.tlg
S005_1FA1BA_050_S.tlg
S005_1FA1BA_060_S.tlg
S005_1FA1BA_070_S.tlg

S005_1FA1BA_000_M.tlg
S005_1FA1BA_010_M.tlg
S005_1FA1BA_020_M.tlg
S005_1FA1BA_030_M.tlg
S005_1FA1BA_040_M.tlg
S005_1FA1BA_050_M.tlg
S005_1FA1BA_060_M.tlg
S005_1FA1BA_070_M.tlg

S005_1FA1BA_000_L.tlg
S005_1FA1BA_010_L.tlg
S005_1FA1BA_020_L.tlg
S005_1FA1BA_030_L.tlg
S005_1FA1BA_040_L.tlg
S005_1FA1BA_050_L.tlg
S005_1FA1BA_060_L.tlg
S005_1FA1BA_070_L.tlg

S005_1GA1BA_000_S.tlg
S005_1GA1BA_010_S.tlg
S005_1GA1BA_020_S.tlg
S005_1GA1BA_030_S.tlg
S005_1GA1BA_040_S.tlg
S005_1GA1BA_050_S.tlg
S005_1GA1BA_060_S.tlg
S005_1GA1BA_070_S.tlg

S005_1GA1BA_000_M.tlg
S005_1GA1BA_010_M.tlg
S005_1GA1BA_020_M.tlg
S005_1GA1BA_030_M.tlg
S005_1GA1BA_040_M.tlg
S005_1GA1BA_050_M.tlg
S005_1GA1BA_060_M.tlg
S005_1GA1BA_070_M.tlg

S005_1GA1BA_000_L.tlg
S005_1GA1BA_010_L.tlg
S005_1GA1BA_020_L.tlg
S005_1GA1BA_030_L.tlg
S005_1GA1BA_040_L.tlg
S005_1GA1BA_050_L.tlg
S005_1GA1BA_060_L.tlg
S005_1GA1BA_070_L.tlg

Заранее спасибо.

**Comment by morkt** [comment]
that's the same issue as #205, please don't spam.

**Comment by Teashrock** [comment]
Sorry
