### ISSUE TITLE
Game request: Shukusei no Girlfriend

### ISSUE THREAD

**Issue by Veshurik** [morkt/GARbro#208]
VNDB: https://vndb.org/v22880
Developer: mirai
Engine: HorkEye
File format: .dat

Thank you!

![3](https://user-images.githubusercontent.com/26744056/43357246-294eeb7a-9287-11e8-9525-6c1b8e5475ae.png)

**Comment by morkt** [comment]
added support in a new pre-release.

**Comment by Veshurik** [comment]
Thanks! Working perfectly!
