### ISSUE TITLE
Simplified Chinese Locale (file enclosed)

### ISSUE THREAD

**Issue by tenyuhuang** [morkt/GARbro#21]
**Got it. Finally got pull request working.**

My apologize in advance for opening up a issue for submitting translation, since I'm at a loss using Github and got riddled while figuring out the "PULL" and "fork" stuff...

I don't know if I've made it right by directly editing the resx files, but I've pasted the whole file here:
https://gist.github.com/tenyuhuang/8ee59400e0c5515ed429c87fa71d3e66

If you're in the mood of including Simplified Chinese Locale in the next version, feel free to use it. :laughing: 
Thanks!

**Comment by morkt** [comment]
your gist link seems to be broken, i got 404 error following it.

as for pull/fork, you did it right actually with your pull request #22

**Comment by tenyuhuang** [comment]
@morkt Thank god I've done it right without messing up anything. Again, sorry for opening uneccessary issues. I'll do this through pull request from now on 😀
