### ISSUE TITLE
Game Request : Haru to Yuki,

### ISSUE THREAD

**Issue by KiritoCy** [morkt/GARbro#210]
https://vndb.org/v22894
Developer : Akabei Soft3
Archive files: .xp3

New encrypting method? Neither Garbro the newest ver nor KrkrExtract-master (idk if i have an old ver and this one doesn't even open the main menu) can extract the scripts & some other files properly idk.

**Comment by morkt** [comment]
it uses the same encryption as `Shoujo to Toshi no Sa, Futamawari` and some other akabei soft games. select this title to access archives.

**Comment by KiritoCy** [comment]
You're right. Although there's still a single prob for some scripts at least 1/10 comes out like this for some reason.....Any idea why? 
https://gyazo.com/22f3489734704c7520a1ff69a619deee

**Comment by morkt** [comment]
scripts are in UTF-16LE encoding (aka UCS-2 little endian).

**Comment by KiritoCy** [comment]
Ahhhh lel. I've fixed them tnx
