### ISSUE TITLE
Game Request : Imouto Paradise! 3

### ISSUE THREAD

**Issue by Bkstrike** [morkt/GARbro#211]
https://vndb.org/v21766

Developer | Moonstone Cherry
Publishers | Moonstone
file format .gyu
extract using imouto 2
![1054](https://user-images.githubusercontent.com/41852772/43364096-0775392e-92ea-11e8-8263-f547da19ac23.png)

**Comment by morkt** [comment]
you may download updated formats database using 'check for updates' menu option.
