### ISSUE TITLE
Request: 24bpp *.hg3 support, and unreadable multi-frame *.hg3

### ISSUE THREAD

**Issue by jkascpkmc** [morkt/GARbro#214]
About half of the background images (and some other system images) in Nekopara vol. 3 (https://vndb.org/v19385) are 24bpp, and thus unviewable.
The game also has many multi-frame images which it uses as video that are completely unreadable. ("The image decoder cannot decode the image. The image might be corrupted.")
Samples: [link removed]
Edit Aug. 29: Sample link expired, replaced it with a permanent one (with more samples).

**Comment by morkt** [comment]
fixed in recent release.

**Comment by morkt** [comment]
multi-frame images are fixed in recent release.
