### ISSUE TITLE
RanceX -決戦- ランス10

### ISSUE THREAD

**Issue by ixvjlv** [morkt/GARbro#216]
Rance10CG3.afa Rance10CG4.afa Rance10CG5.afa
Error opening file

**Comment by morkt** [comment]
probably because these are not archives, but either video clips or dummy files put into disk to fill spare space.

**Comment by ixvjlv** [comment]
https://mega.nz/#!NgQQnK7b!g59PUIjVa96HxFS_PQxNpuKd0om6_JRFo2ntDl4YQbM
https://mega.nz/#!Z8Y0RY5B!_K-BCIBp8_6qPatFBCKAtufapzZ2Xt-h95fIXAXrW0s

I thought this is the file added by the update file?

**Comment by morkt** [comment]
added in recent release.
