### ISSUE TITLE
Issue when extracting "Sweet Switch ~When Our Eyes Meet, My Body Melts~" (English version)

### ISSUE THREAD

**Issue by GuyInDogSuit** [morkt/GARbro#218]
The files extract fine, but they don't open and the images have blank thumbnails, the audio files won't play, etc.

OS: Windows 10 Pro
Framework version: 4.0.30319.42000
Framework release: 461808 (4.7.1+)
GARbro: 1.5.38.2464
Formats database version: 122

Loaded assemblies:
GARbro.GUI 1.5.38.2464
GameRes 1.5.39.295
ArcExtra 1.0.12.32
ArcFormats 1.2.42.1834
ArcLegacy 1.0.5.96
NAudio 1.8.4.0
System.Windows.Controls.Input.Toolkit 3.5.40128.1
WPFToolkit 3.5.40128.1

**Comment by morkt** [comment]
select "no encryption" in encryption choice dialog.

**Comment by GuyInDogSuit** [comment]
Thanks! That worked!
