### ISSUE TITLE
Gin'iro Haruka - Not all files decrypted

### ISSUE THREAD

**Issue by Veshurik** [morkt/GARbro#221]
https://vndb.org/v18778
Siglus Engine.

In folder g00 there are many files that not listed, but exists in folder - almost all CGs, most BG, and sprites also, some images too. Why it happens? Maybe, I need something to do or what?

Thanks for the help.

**Comment by morkt** [comment]
can't confirm this. please provide more elaborate explanation, with exact filenames not showing, screenshots etc.

**Comment by morkt** [comment]
closing as insubstantial.
