### ISSUE TITLE
Some Games Request: By Nyan Nyan / Bug System

### ISSUE THREAD

**Issue by alittlered** [morkt/GARbro#222]
Developer: Nyan Nyan
Format: xp3

Ero Mangaka-san to Binbou Shimai
https://vndb.org/v17998

JK Trouble Main"s
https://vndb.org/v18187

Osakoi Ore to Futari no Ama Ama Gohoushi H Seikatsu
https://vndb.org/v18718

------
Developer: Bug System
Format: xp3

Sukui no Serenade
https://vndb.org/v16895

Shiniyuku Kimi, Yakata ni Mebuku Zouo
https://vndb.org/v19233

Haze Man -The Local Hero-
https://vndb.org/v21374

Not important, i just report this, take it easy.

**Comment by morkt** [comment]
added in recent pre-release.
