### ISSUE TITLE
Game Request: Kuro Gyaru Musume to no In'yoku Soukan ~Honrou Sareru Chichioya no Seiyoku~

### ISSUE THREAD

**Issue by YoxalLoyal** [morkt/GARbro#225]
VNDB: https://vndb.org/v23333
Engine: KiriKiri
Developer: Appetite
File Extension: .xp3 (encrypted)

Thanks in advance.

**Comment by morkt** [comment]
it should be supported, choose "Kuro Gyaru Musume" when asked for encryption scheme.
