### ISSUE TITLE
Starless repacking

### ISSUE THREAD

**Issue by Ileca** [morkt/GARbro#227]
Hello hello. I am trying to patch Starless by Mangagamer to recensor everything with the original arts (don't judge). For the moment, I started by extracting then immediately repacking. If the first step works as far as I can tell, you have no option for repacking. Like they are arc files, I tried ARC/Will & 2 but it would have been too easy (I got "file damaged")...
Thank you.

**Comment by morkt** [comment]
as far as i know mangagamer didn't publish starless, it was jast usa. jast usa release utilizes Majiro archives.

**Comment by Ileca** [comment]
Oh, yeah, stupid mistake, even more when I just saw the JAST logo like ten times before writing this.
Majiro works and I can repack pics from original Starless inside the Manga... JAST port without breaking.
Thanks, bro, you are so GAR.
(I just saw I could have found that by myself just by looking at the bottom of the tool where the engine is written when you open an archive. Those stupid users... please excuse them.)

**Comment by morkt** [comment]
still, i wonder if repacking would work. i wrote it 3 years ago and almost didn't test aside from may be one title.

**Comment by Ileca** [comment]
Oh, I tested it. I recreated the data3.arc with assets from the original Starless and filled the JAST release with it. This archive contains the very first CG you started the game with and there was no problem loading (without the data3.arc, it doesn't crash but the CG doesn't show, the engine appears to be very resilient to missing assets even if _all_ the CG are missing).
