### ISSUE TITLE
[Req] Your Diary+ H English ver

### ISSUE THREAD

**Issue by GuyInDogSuit** [morkt/GARbro#230]
Can you add support for this VN?

**Comment by morkt** [comment]
selecting "your diary + H" doesn't work?

**Comment by GuyInDogSuit** [comment]
Any luck so far?

**Comment by GuyInDogSuit** [comment]
@morkt

**Comment by morkt** [comment]
by any chance, have you tried "no encryption" to access archives?

**Comment by GuyInDogSuit** [comment]
I'll be damned... it actually worked. I'll have to try that option more often in future. Thanks!

**Comment by morkt** [comment]
yeah, i probably had to ask that earlier, been busy though.
