### ISSUE TITLE
Hana Hime * Absolute! BugBug Append File Extraction Errors

### ISSUE THREAD

**Issue by KiritoCy** [morkt/GARbro#231]
The Original Game Files are ok (https://vndb.org/v15727), but when i installed the append patch for it from the "BugBug 2015 08 250 Anniversary DVD Append H Disk Part 3", to my surprise it's actually a mini fandisc (200 MB) which is installed seperatelly and the scripts can't be extracted from it for some reason (i don't see prob with anything else from what i can tell). Can you update garbro for this append too plz?

**Comment by morkt** [comment]
i believe it's actually a trial version of a game, not a fandisc, it was released year before the complete game release. eventually i'll add support for it, but it will be on a low priority (couple of weeks until the next update).

**Comment by KiritoCy** [comment]
Ahhh yr right. Didn't actually check the release date just saw it had an append and downloaded everything that related to it. Well in that case i'll just patiently wait for ya to support it along with the following months requests i'll make. Tnx anyway!

**Comment by morkt** [comment]
added in recent release.
