### ISSUE TITLE
Game Request: Dies irae Mangagamer Version

### ISSUE THREAD

**Issue by YoxalLoyal** [morkt/GARbro#232]
VNDB: https://vndb.org/r50485 and https://vndb.org/r49319
Developer: light
Engine: Malie
File Extension: .dat

I know you are probably extremely sick of seeing these light requests so I apologize beforehand. Onto the request, I tried several of your GARbro versions on one of the files in the Mangagamer version (or 18+ patch for the Steam version) of Dies irae which is the data4.dat file containing the 18+ CGs and Acta est Fabula images but all of them did not work. Could you fix this? Thanks in advance.

**Comment by morkt** [comment]
if you can, copy-paste contents of Help | Troubleshooting from garbro.

**Comment by morkt** [comment]
you're not using the latest version, which is 1.5.39 and available on the [latest release page](https://github.com/morkt/GARbro/releases/latest). please, always try **latest** application version before making an issue.

**Comment by YoxalLoyal** [comment]
That seemed to have fixed it, thanks.
