### ISSUE TITLE
Game request: In'youchuu Kyou (nsfw)

### ISSUE THREAD

**Issue by progste** [morkt/GARbro#238]
Warning: erotic game, sorry if that isn't allowed...
VNDB: https://vndb.org/v15483
Engine: probably propietary Cyberworks/Tinkerbell

I've wished to translate this series of games for a while, starting with this one.
Currently I can extract CGs and sound files with GARbro, but no script. There are a lot of small unreadable files that look like they could be an encrypted version of the script (some files looked like a series of pointers when opened with a hex viewer).
I'm looking for a way to extract the original srcipt and possibly put it back in after translating it.

**Comment by morkt** [comment]
if you happen to know how scripts are stored in this engine i will happily add it to an extraction routine, otherwise i'm afraid i can't help you much.
