### ISSUE TITLE
Request: Hello Lady!

### ISSUE THREAD

**Issue by GuyInDogSuit** [morkt/GARbro#239]
I can't seem to open this without a encryption option nor with either of the two "Hello Lady!" options available. "Hello Lady!" gives "xp3 could not be opened as resource archive." "Hello Lady! -New Division-" option opens it and lists the file but gives an "invalid file format" error, even on recognizable file formats (PNG images, TXT files, etc).

**Comment by morkt** [comment]
where did you get english version? according to VNDB it's due to release in 2019.

**Comment by GuyInDogSuit** [comment]
Oh, my mistake, I was looking at a different game and mixed the two up.

This one's in Japanese, actually, but as stated, neither option is working on it.

**Comment by morkt** [comment]
specify exact release you're using (preferably with VNDB link) because "hello lady" is supported according to my supported games list.

**Comment by GuyInDogSuit** [comment]
I believe it's this version:
https://vndb.org/r33259

It doesn't have anything else special to it.

**Comment by morkt** [comment]
i don't know how to help you. this release should be supported, if you're unable to access archives i can't do anything about it.

**Comment by GuyInDogSuit** [comment]
*shrug*
Oh well. Guess I'll just wait for the English release, then.
