### ISSUE TITLE
Request: FLT formats?

### ISSUE THREAD

**Issue by GuyInDogSuit** [morkt/GARbro#240]
For example, Purino Party uses this.

**Comment by GuyInDogSuit** [comment]
Yes, it's a VN with match-three gameplay.

**Comment by morkt** [comment]
it's not a VN, but i've added support in recent release nevertheless. note that some images are split in parts across different archives and in order to view them you should first extract *.fg and *.fge files without conversion into one directory, and then they can be viewed/converted from there.
