### ISSUE TITLE
Запрос игры: Seigi no Henshin Heroine o Sasaeru Ore to Aku no Onna Kanbu

### ISSUE THREAD

**Issue by rahimodze** [morkt/GARbro#241]
Судя по всему написана на движке Artemis. Запакована в .pfs.xxx формат, а именно ".pfs.000; .pfs; .pfs.001; .pfs.002;" распаковке поддаётся только root.pfs.002.
Ccылка: https://vndb.org/v24211
[link removed]
![default](https://user-images.githubusercontent.com/21127119/47257560-e49eb280-d4a8-11e8-8779-cff1ad298caf.PNG)
![2](https://user-images.githubusercontent.com/21127119/47257576-14e65100-d4a9-11e8-82ae-14b8f9ce1fa6.PNG)
Полагаю, что ключ шифрования у архивов разный.

**Comment by morkt** [comment]
open preferences (ctrl-P) and change PFS archive encoding to Shift-JIS, this should help.

**Comment by rahimodze** [comment]
thank you very much for the help
