### ISSUE TITLE
Game Request: Deatte 5-fun wa Ore no Mono! Jikan Teishi to Atropos

### ISSUE THREAD

**Issue by thxalot** [morkt/GARbro#244]
Hello,

Would you support following game with Garbro?

Deatte 5-fun wa Ore no Mono! Jikan Teishi to Atropos - First Edition (NOT DL edition)
https://vndb.org/r57869

The methods of other games by the same developer were useless.
(Garbro: SourireCrypt, XorCrypt(0xCD), HashCrypt)
And also KrkrExtract and Crass were useless, too.

Thank you in advance.

**Comment by morkt** [comment]
i've updated formats database, you may download it using "check for updates" menu option.

**Comment by thxalot** [comment]
New formats database worked fine.
Thank you very much for your promptly response!
