### ISSUE TITLE
Game Request: White Album 2

### ISSUE THREAD

**Issue by DoqtorKirby** [morkt/GARbro#245]
**VNDBs:** https://vndb.org/v2920 https://vndb.org/v7771
**Developer:** Leaf
**Engine:** Unknown *(Leaf-specific?)*
**File format:** .pak
**Notes:** There is a release with both installations. This is considered to be the definitive version. It has a release on vndb here -> https://vndb.org/r17326

Thank.

**Comment by morkt** [comment]
added in recent release.
