### ISSUE TITLE
Game Request: 	Boku to Koi Suru Ponkotsu Akuma (English ver.)

### ISSUE THREAD

**Issue by Veshurik** [morkt/GARbro#246]
VNDB: https://vndb.org/v17515
Engine: Kirikiri
File: .xp3

Thank you so much!

**Comment by morkt** [comment]
did you try "Boku to Koi Suru Ponkotsu Akuma" when asked for encryption?

**Comment by Veshurik** [comment]
I am so stupid. Sorry. I thought the name starts with other letter, not B...

**Comment by Veshurik** [comment]
So, bgimage.xp3... Can't see backgrounds in folders.
![3](https://user-images.githubusercontent.com/26744056/47608232-fe08a700-da32-11e8-8e54-e6f07115b1bd.png)

**Comment by morkt** [comment]
.NET JPEG decoder can't parse those images. nothing i can do about it. you could extract them and watch with any external application.
