### ISSUE TITLE
Game request: Sabbat of the Witch

### ISSUE THREAD

**Issue by x151973** [morkt/GARbro#249]
https://vndb.org/r60368
[link](magnet:?xt=urn:btih:ad6d7940b3becfd952721748dcfc328986abad67&dn=%5b181026%5d%20%5bNekoNyan%5d%20Sabbat%20of%20the%20Witch&tr=http%3a%2f%2fanidex.moe%3a6969%2fannounce)
xp3,pimg

**Comment by morkt** [comment]
i've updated formats database, you may download it using 'check for updates' menu option. select "Sabbat of the Witch" when opening archives.

**Comment by Entangled-Cable** [comment]
No text decryption?

**Comment by morkt** [comment]
everything is decrypted. scripts are in bytecode form.

**Comment by Entangled-Cable** [comment]
Ah, you're right. When I open the .scn files I can see the text. I was confused by krkr-extract not being able to read the extracted files - when I dump the files to .txt, only name tags are shown. Usually krkrz games work just fine.

**Comment by DennisWeyrauch** [comment]
Am I missing something or how can I make it being readable text?

**Comment by morkt** [comment]
i have no idea.

**Comment by Entangled-Cable** [comment]
@DennisWeyrauch Open the .ks.scn in notepad++ or your text program of choice. Scroll all the way down and you will see the encrypted Japanese text. Scroll just a bit up and you will see the English text, which is unecrypted, though the lines will be in alphabetical order, not in chronological order. Just search for a common English word and you will get to the point where they are written. This is not that uncommon in English releases. You won't be able to change and repack the text into the game this way, but you can view it.
