### ISSUE TITLE
Please add key support Archive .LPK

### ISSUE THREAD

**Issue by EAxp3** [morkt/GARbro#25]
Please add: keys
archive .LPK
GAME: [info-game](https://vndb.org/v18171)

keys:

sys
84 CC 78 EB B9 C5 F5 92
chr
72 B9 76 DE 4E DD 69 1E
pic
A2 43 64 DD 32 28 48 CD

Thanks :+1:

**Comment by EAxp3** [comment]
thanks for implement .g00 Real Live :+1:  :tada:

**Comment by morkt** [comment]
i've updated encryption schemes database, you could grab it [directly from repository](https://github.com/morkt/GARbro/blob/master/GUI/Resources/Formats.dat), click [Raw] and place it into GARbro directory (replacing old one).
