### ISSUE TITLE
Game Request: Otometeki Koi Kakumei★Love Revo!!

### ISSUE THREAD

**Issue by meganeco** [morkt/GARbro#251]
vndb: https://vndb.org/v3549
Uses shiina-rio engine (WARC 1.7 signature). GARbro can open .war archives using presets for games using engine versions 2.40 - 2.49, but gives errors when trying to decode files inside.

**Comment by morkt** [comment]
i've updated formats database, you may download it using "check for updates" menu option in the latest release.

**Comment by meganeco** [comment]
Thank you very much! I can access everything perfectly (except for the script files, but I know that's outside the scope of this project).
