### ISSUE TITLE
Game Request: light Visual Novels

### ISSUE THREAD

**Issue by YoxalLoyal** [morkt/GARbro#256]
VNDB: https://vndb.org/r59864 and https://vndb.org/r52327
Engine: Malie
File Extension: .dat

I downloaded the latest version of GARbro and tried to extract images from 相州戦神館學園 八命陣 released in Dies irae & WORLD BOX: Masada Premium but I got an invalid file format error and got .svg files instead. I'm not sure if the encryption format in this release is different than the original release.

Also, light released a patch in September for the Dies irae Kickstarter with the 4:3 resolution CGs for Amantes amentes. I tried to extract files from it, but got an error message: data5.dat could not be opened as resource archive.

**Comment by morkt** [comment]
what exact version of garbro are you using? if archives can be opened, but images not displayed most likely you got garbro installed incorrectly. try to re-install it from [release with executable setup](https://github.com/morkt/GARbro/releases/latest).

as for other dies irae releases, it has so many of them that it's almost impossible to track them all. if you're eager to get 4:3 CGs i suggest you rip them from some earlier release, most of them are supported.

**Comment by YoxalLoyal** [comment]
I'm using GARbro-v1.5.40.2721.

**Comment by morkt** [comment]
try new pre-release (still not sure if it will support your particular release).
