### ISSUE TITLE
After GARbro 1.5.39, some Willplus *.arc archives are failed to decode

### ISSUE THREAD

**Issue by thxalot** [morkt/GARbro#259]
Hello,
Today, I have noticed that some Willplus *.arc archives are not decoded correctly after ver. 1.5.39.
For example,

(1) Koi Suru Ojou-sama wa Ecchi na Hanayome
https://vndb.org/v19103
Chip6.arc

(2)Otome ga Musubu Tsukiyo no Kirameki
https://vndb.org/v23338
Chip5.arc

These archives are successfully decoded in GARbro 1.5.38 or older.
Could you confirm this issue on your side?

Thank you in advance.

**Comment by morkt** [comment]
fixed in new pre-release.

**Comment by thxalot** [comment]
Thank you.
I am going to check new pre-release works properly with my WillPlus games.
