### ISSUE TITLE
Some info regarding Kourin no Machi, Lavender no Shoujo

### ISSUE THREAD

**Issue by fro0116** [morkt/GARbro#26]
Hi! I was pointed to this repo by @rr- after [requesting support](https://github.com/vn-tools/arc_unpacker/issues/45) for this game in arc_unpacker. @rr- suggested I should share the following findings with you in order to help speed up the process:

> 
1. The entry point to the whole thing seems to be located at lavender.tpm+0xE70. Specifically, it can be reached by analyzing references to zlib's uncompress function, and comparing it to kirikiri source code by tracking down usages of TVPXP3ArchiveExtractionFilter upwards.
2. I also noticed the game executes code from dynamically allocated regions, which probably means that it uses dynamic assembly like CXDEC did. Also, it too uses "encryption control block" as well as two constants in form of (x & A) + B, all looking familiar to CXDEC, but don't let it fool you - later it does everything differently, and I think it starts with compiling repeatedly mini-functions that serve as LCGs at a later time.
3. To prove without doubt that it's not CXDEC, there's not even one mention of 0x41C64E6D, which served an essential role in the CXDEC as a part of its RNG.

It's all way beyond my own technical comprehension, but I hope that helped! Thank you for your work!

**Comment by morkt** [comment]
nah, it's still CXDEC, just with additional layer of encryption. i've updated encryption schemes database, you could [grab it from repository](https://github.com/morkt/GARbro/blob/master/GUI/Resources/Formats.dat), click [Raw] and place "Formats.dat" into GARbro folder, replacing old one.

this is a second time in a week, probably should start working on a networked app update already :sweat:

**Comment by fro0116** [comment]
Thank you so much @morkt!

Gave it a try just now and it worked perfectly! =)
