### ISSUE TITLE
Game Request: Hatsujou Switch ~Bishimai ga Saiminjutsu ni Ochita Saki~

### ISSUE THREAD

**Issue by marconii2002** [morkt/GARbro#260]
Vndb: https://vndb.org/v16089
Engine: KiriKiri
Files : .xp3

With xp3viewer and KrKr I get images like this

![ev49c](https://user-images.githubusercontent.com/22653453/49284912-4aae2a80-f496-11e8-8537-f0e902ecb953.png)

**Comment by morkt** [comment]
added in new pre-release.
