### ISSUE TITLE
the new-style .wolf file cannot be unpack

### ISSUE THREAD

**Issue by HarutLiang** [morkt/GARbro#267]
Your soft is wonderful!
But there is some problems.
some new-style .wolf file cannot be unpack.
such as
[EVCG_g.zip](https://github.com/morkt/GARbro/files/2672567/EVCG_g.zip)
it belongs トレジャーハンタークレア～精液を集める冒険家～
can you fix these support problem?
than you so much!

**Comment by HarutLiang** [comment]
this company's old-style .wolf file can be unpack.

**Comment by morkt** [comment]
can't confirm this, everything works fine on my end. make sure to use the latest release when reporting issues.
