### ISSUE TITLE
Saimin Paradise! Viewing issue

### ISSUE THREAD

**Issue by wlghks9911** [morkt/GARbro#268]
Greetings, I have several problems from opening up files with .s25 extension in Saimin Paradise!.
When I try to extract WAR file and open .s25, all the characters in the file show up without face and arms.
This kind of problem happens not just to all Standing CGs, but to all Event CGs as well.

I also noticed that the number of .s25 of CGs are fewer than I have witnessed. I suspect it's because there's some problem with the decryption.

Below is what I've tried so far.

![image](https://user-images.githubusercontent.com/45862992/50038107-841d9300-005d-11e9-917e-9482f45fd7c1.png)
![image](https://user-images.githubusercontent.com/45862992/50038162-5be26400-005e-11e9-8abe-f75d3e082bec.png)

VNDb : https://vndb.org/v23063

After I bought the game, I applied the special patch included in the package.
(But i guess it does not matter. i uninstalled all of the game and reinstalled the game without special patch for once. but there are no difference for viewing with GARbro.)
Game and GARbro is working fine. Also GARbro is updated to the latest version.

Thank you very much.

**Comment by morkt** [comment]
images in those games are composed by game engine from separate parts. you could access those parts by "entering" inside an image (press `Enter` on filename). you'll have to combine those parts manually, order and number of parts are different for every image.

**Comment by wlghks9911** [comment]
oh i never thought that such "entering" the .s25 file. it's my mistake.

Thank you for your prompt reply.
