### ISSUE TITLE
Does your instruments support parsing this script file in pbd format？

### ISSUE THREAD

**Issue by WARGBM** [morkt/GARbro#270]
Pbd is a kind of script file in which derive from an engine called krkr and it contains the coordinate information of character＇s vertical drawing.

For instance:Riddle Joker,Loca Love My Cute Roommate

I would really appreciate if you could give me a hand.
![s7em nt c zxnz da4 5l](https://user-images.githubusercontent.com/26682094/50371393-193c0100-05f5-11e9-8e80-1ae473c72e87.png)

**Comment by Gomiokiba** [comment]
I think there may be a clue in the source code named "PbdDecoder.cpp" written by X'moe.
But this code is probably unfinished, and I have no idea how to complete it...
