### ISSUE TITLE
Game Request: Ina☆Koi! ~Oinari-sama to Motemote no Tatari~

### ISSUE THREAD

**Issue by studentmain** [morkt/GARbro#272]
[VNDB Link](https://vndb.org/v511)

Seems it use a old version of YuRis engine.
Wrote a unpacker for it in C# few months ago.

[code.zip](https://github.com/morkt/GARbro/files/2706493/code.zip)

**Comment by morkt** [comment]
added in new release.

**Comment by studentmain** [comment]
Confirmed works. Thank you.
