### ISSUE TITLE
file can not be opened..... Nora to Oujo to Noraneko Heart (mv\op.dat)

### ISSUE THREAD

**Issue by 28598519a** [morkt/GARbro#275]
ノラと皇女と野良猫ハート [HARUKAZE]

arc0.dat ~ arc3.dat 、 script.dat
open and extract sucess

but mv\OP.dat and mv\OP_L.dat 
file can not be opened as resource archive

**Comment by 28598519a** [comment]
> Just rename those .dat file in .mp4 and enjoy

video (failed) any ieda ?
audio recongized by Vorbis decoder

**Comment by 28598519a** [comment]
> Just rename those .dat file in .mp4 and enjoy

here is OP.dat (GoogleDrive;you can check it) , I rename it in .mp4, but the video can't play.
https://drive.google.com/open?id=1Qy_qoacmqg5zc8BNHm3qozpmLr4LVlZY

**Comment by morkt** [comment]
it's not an archive, but a video file. you should ask somewhere else for help with video playback, here it's an off-topic.

**Comment by 28598519a** [comment]
> it's not an archive, but a video file. you should ask somewhere else for help with video playback, here it's an off-topic.

I think it's an half archive, because if you search hex ( AC 26 ) you can find it and copy (00 49 AC 26 ....and  to the file end) paste to be a new file. now it can be open by GARbro, it seems it have some files in side, but extract failed

**Comment by Veshurik** [comment]
http://harukaze-soft.com/nora/download/download.html

You can download the same OP movie that was in game in MP4 or WAV on that site. I think it's no difference.

**Comment by 28598519a** [comment]
> http://harukaze-soft.com/nora/download/download.html
> 
> You can download the same OP movie that was in game in MP4 or WAV on that site. I think it's no difference.

Thanks.

But I think it may have some difference, because I check the time length.
>OP.mp4                                : 1min55s

>noratotoCM_fullHD05.mp4 : 1min19s
>noratotoOPCM_fix_70.mov : 2min22s
