### ISSUE TITLE
The *.pimg archives of certain YuzuSoft products cannot be recognized as correct archives with GARbro 1.5.41.

### ISSUE THREAD

**Issue by thxalot** [morkt/GARbro#277]
Hi,

I have noticed that *.pimg archives in evimage.xp3 of following VNs cannot be extracted with GARbro 1.5.41.2805.

NG: Dracu-Riot! (https://vndb.org/r16640)
NG: Amairo ＊ Islenauts (https://vndb.org/r25734)
NG: Sanoba Witch - Package Edition (https://vndb.org/r36485)
(OK: Senren ＊ Banka - Package Edition (https://vndb.org/r45245) evimage720.xp3, evimage1080.xp3)
(OK: Riddle Joker (https://vndb.org/r54747))

This problem does not occur in GARbro 1.5.40.2749.
And, please take care that Noble☆Works or older titles  are not investigated yet.

Thanks.

**Comment by morkt** [comment]
fixed and re-uploaded release.

**Comment by thxalot** [comment]
I confirmed that this problem was solved.
Thank you very much.

p.s. I aiso confirmed "Noble☆Works" was not contain *.pimg archives.
