### ISSUE TITLE
Game Request:Wagamama High Spec

### ISSUE THREAD

**Issue by qmamu** [morkt/GARbro#280]
hello , Wagamama High Spec (Japanese) doesn't work on encryption schemes after version 1.4.32

VNDB - https://vndb.org/v17823

**Comment by morkt** [comment]
only Sekai Project release was supported. i've added original scheme, you may download updated database using "check for updates" menu option.

**Comment by qmamu** [comment]
Thank you for your hard work.

**Comment by AsukaLangleyfag** [comment]
Regression: latest release (v1.5.44.2904) doesnt work, you can open archives but encoding scheme is wrong so cant get anything valuable
