### ISSUE TITLE
Game Request:Prism Princess ~Futari no Himekishi to Kokan no Monshou~

### ISSUE THREAD

**Issue by hfsztt** [morkt/GARbro#281]
Hello, I'm trying to encrypt this game. Could you please support this game?
This is made by Lucifen (*.LPK) but something different so that I can't open it with common encrypter.
I've seen that this program can encrypt Nekonade Distortion Exodus. So I think that we can encrypt this game with the same way.
Thank you very much!
https://vndb.org/v15640

**Comment by morkt** [comment]
i've updated formats database, you may download it using 'check for updates' menu option.

**Comment by hfsztt** [comment]
> i've updated formats database, you may download it using 'check for updates' menu option.

Thank you very much!
