### ISSUE TITLE
Game Request: Amakano

### ISSUE THREAD

**Issue by fkvldh** [morkt/GARbro#282]
Name: Amakano (Perfect Edition is lastest)
VNDB: https://vndb.org/v15679
Trial: http://suezou.dyndns.org/dl2014/azarashi-soft/amakano/amakano_trial.zip
Engine: cs2(?)
Files: int

Thank you so much! Sorry if I miss something.

**Comment by morkt** [comment]
in the open dialog, press 'Check EXE', select `amakanoPE.exe`, it should find appropriate key.

**Comment by fkvldh** [comment]
Thank you, morkt! It's work. I will try other series.
