### ISSUE TITLE
Game Request: The Eden of Grisaia

### ISSUE THREAD

**Issue by Aecheritt** [morkt/GARbro#286]
The access code actually works with Labyrinth but it's a mess, like in Kajitsu when you messed up your ripping before GARbro was a thing, so it needs its own code

**Comment by morkt** [comment]
in archive open dialog press 'check exe', select `Grisaia3.bin`, it should find appropriate key.

**Comment by Aecheritt** [comment]
Oh so it was .bin I had to choose wow, thank you
