### ISSUE TITLE
Request : Can't decrypt .Pac files.

### ISSUE THREAD

**Issue by hs7728m** [morkt/GARbro#290]
I can decrypt this game trial ver 1.00 (link_1)
but after trial version update to 2.00, I can decrypt Game.pac files. (link_2)

I think it is .pac/lunasoft . but now I can't decrypt now. my GARbro ver is 1.5.42.2807.

https://www.dlsite.com/maniax/announce/=/product_id/RJ219681.html <-- Game

.Pac file
[link removed] <-- Link_1
[link removed] <--Link_2

**Comment by morkt** [comment]
added in recent pre-release.
