### ISSUE TITLE
Game request: Sorceress＊Alive

### ISSUE THREAD

**Issue by Veshurik** [morkt/GARbro#291]
VNDB: https://vndb.org/v23288
Files: root.pfs

Problem: can't find existing files, for example...
root.pfs.000 - image - sd - sd_008.

Thank you so much!

**Comment by morkt** [comment]
pfs archives are fully supported, including this title. if you're not seeing some files it means they don't exist.

**Comment by Veshurik** [comment]
So, that means that developers forgot to add sd_008 in game?

Just because

root.pfs - image - thumb - sd_008.png

There is thumb of image, but image itself - no? What a nice devs, ahaha...
