### ISSUE TITLE
Game Request: Sono Hi No Kemono Ni Wa (Full)

### ISSUE THREAD

**Issue by Anonchilla5** [morkt/GARbro#293]
Requesting support for the full version of Sono Hi No Kemono Ni Wa, which previously had support for the trial edition added. (Trial version mode does not work on full version, tested.)
VNDB: https://vndb.org/v23458
Official Site (JP Locked): http://www.minori.ph/lineup/sonokemo/

Thank you for your consideration!

**Comment by morkt** [comment]
i've updated formats database, you may download it using 'check for updates' menu option.

**Comment by TR4D1T10N4L** [comment]
Seems to be an issue with this game, says the paz files cannot be opened, made sure GARbro was up to date and it also has no issues dealing with Trinoline's paz files.
