### ISSUE TITLE
Game Request: Shirokoi Sakura ＊ Gram - Trial Edition

### ISSUE THREAD

**Issue by ycrack** [morkt/GARbro#294]
VNDB link: https://vndb.org/r60848
Developer: NanaWind
Release date: 181128
Original title: 白恋サクラ＊グラム 体験版

I found that NanaCxCrypt(0x23C, 0x6D) decrypter of "Haruoto Alice＊Gram", *which is previous works of this series,* can not decrypt. so I hope to support this title.

BTW, what changes have happened between *Haruoto Alice＊Gram* and *Shirokoi Sakura＊Gram* Trial ?
Although it may not be related, I found that the distributed folder name is *sirokoi01*, not *s**h**irokoi01*.

**Comment by WARGBM** [comment]
Choose No encryption

**Comment by ycrack** [comment]
wow, it opened 😮 

it means *encryption detection* malfunctioned? 🤔
