### ISSUE TITLE
Game Request: Hello,good-bye

### ISSUE THREAD

**Issue by SenaKaito** [morkt/GARbro#298]
VNDB link: https://vndb.org/v5316
Developer: Lump of Sugar
Release date: 2019-01-25
Original title: ハローグッバイ, HGB
English title: Hello,good-bye

.dat files, kinda modified, can't open.
(maybe from unity engine vn)

thank you.

**Comment by jszhtian** [comment]
for 2010 version, that is a BGI game, but use BGI v1 arc packfile. use some old tools like crass to unpack it.

**Comment by morkt** [comment]
added in recent release.
