### ISSUE TITLE
Compilation problems

### ISSUE THREAD

**Issue by rr-** [morkt/GARbro#3]
There are a few issues with compiling the project:

- The references aren't fetched automatically by NuGet and one needs to move `.dll` from binary distribution to respective folders in `packages/`.
- In case of two dependencies, the project refers to `D:\Program Files\` rather than `packages/`, so the trick above can't work and one needs to edit `.csproj`...
- After manually fixing the dependencies, the compiler complains about missing resources:
   -  `Could not find file "GARbro\ArcFormats\Resources\ShiinaRio4.jpg"`

I don't know if there are any other problems since I can't get pass the last problem.

MSVS version: Microsoft Visual Studio Community 2015 14.0.23107.0.D14REL
.NET version: 4.6.00081

**Comment by morkt** [comment]
yeah shiina rio resources are private for now sorry. consider this repository for educational use. so, as long as it compiles without problems on my machine issues like this are of little concern for me.

**Comment by rr-** [comment]
Understood, thanks
