### ISSUE TITLE
Support for English Sonicomi

### ISSUE THREAD

**Issue by Redyn** [morkt/GARbro#30]
Hi, could you please add support for the JAST USA version of Sonicomi? It uses .npk archives like Tokyo Necro, so it shouldn't be hard to do. arc_unpacker recently added support for it, but unlike this utility, it doesn't support repacking. Anyway, it's probably only a matter of adding the Sonicomi encryption key, which can be found in:

https://github.com/vn-tools/arc_unpacker/blob/master/src/dec/nitroplus/npk2_archive_decoder_plugins.cc

Thank you.

**Comment by Redyn** [comment]
I just realized that not even this program supports packing .npk archives. Awwww... I don't suppose there are any plans to add that feature any time soon?

**Comment by morkt** [comment]
i've implemented creation of NPK archives ([download](https://github.com/morkt/GARbro/tree/v1.2.19-pre)), but i don't possess any of the related games so i can't test it.

**Comment by Redyn** [comment]
Thank you! Unpacking of Sonicomi archives works like a charm. Unfortunately, packing seems to be broken. I unpacked an archive and repacked it without touching any of its files or folders. The game crashes when it tries to load it.

Here's the npk archive I tried recreating (the original version, of course, not the repacked version):
https://mega.nz/#!aZJXWA4A!IsPypwWw0tZqvKu4iMK5voyodgqi5ntVJAYH79zFx0w

Sorry for not providing this before. I wasn't sure certain if it was okay to post these kind of files.

**Comment by Redyn** [comment]
Oh, btw, I can also upload the game exe if you want. It can be used to verify if the archives are being repacked correctly. As long as the proper script.npk file is in the same folder, it should run. If it's missing, corrupt or incorrectly packed, it will crash.

**Comment by morkt** [comment]
i'll look into it, but it will take some time.

**Comment by Redyn** [comment]
Thanks for your efforts, much appreciated :)

**Comment by morkt** [comment]
appears to be working now, see latest release.

**Comment by Redyn** [comment]
Whoa. Sorry for the late reply. I just tried the new version and it works like a charm! Many thanks for fixing NPK packing!
