### ISSUE TITLE
Game Request: Soushuu Senshinkan Gakuen Hachimyoujin 

### ISSUE THREAD

**Issue by kinoulo** [morkt/GARbro#301]
https://vndb.org/r26515
Engine: Malie
Developer: light

**Comment by morkt** [comment]
should work in recent release.

**Comment by kinoulo** [comment]
Thank you so much😭🙏

**Comment by kinoulo** [comment]
There are some images that cannot be analyzed
Can you  correspond with the next update?

https://user-images.githubusercontent.com/47352402/53858578-1e1e2780-401e-11e9-9f3a-7de6d6477cc5.png

**Comment by morkt** [comment]
see #191

**Comment by kinoulo** [comment]
Thank you very much.
