### ISSUE TITLE
Game request: 9-Nine- Kokonotsu Kokonoka Kokonoiro EN/CN version

### ISSUE THREAD

**Issue by Entangled-Cable** [morkt/GARbro#303]
VNDB: https://vndb.org/v19829
Developer: Palette
Engine: Kirikiri
Files: .xp3
Note: Sekai project Steam release

Japanese version decryption doesn't seem to work. It doesn't even ask for a title and opens the archives immediately. Then it cannot read or properly extract the images.

**Comment by morkt** [comment]
added in recent release. select '9 -Nine-:Episode 1' when asked for encryption.

**Comment by Entangled-Cable** [comment]
Thanks.
