### ISSUE TITLE
Game Request: Yahari Game demo Ore no Seishun Love Come wa Machigatteiru

### ISSUE THREAD

**Issue by 0xh3LL0** [morkt/GARbro#306]
VNDB: https://vndb.org/v12630
Developer: 5pb Games
Engine: Criware
File Format: no extension, "GXT" header
Sample: [chara.zip](https://github.com/morkt/GARbro/files/2896408/chara.zip)

**Comment by 0xh3LL0** [comment]
maybe it can help?
https://github.com/ningshanwutuobang/ChaosChildPCTools/blob/master/gxt.py

**Comment by morkt** [comment]
added in recent release, although these particular textures seem to be shuffled with unknown algorithm.

**Comment by 0xh3LL0** [comment]
thank you very much!
