### ISSUE TITLE
Game Request: Kanojo to Ore to Koibito to.

### ISSUE THREAD

**Issue by SenaKaito** [morkt/GARbro#307]
VNDB: https://vndb.org/v10972
Developer: Pulltop Latte
Engine: E-mote (?)
Files Format: .dat .psp

All assets work with GARbro, except **sprites** assets with extension .dat and .psp.
Thank you :3

**Comment by morkt** [comment]
DAT are simply video files that could be played in any decent media player.

PSP files are compressed PSB, added decompression in a recent release.

**Comment by SenaKaito** [comment]
> DAT are simply video files that could be played in any decent media player.
> 
> PSP files are compressed PSB, added decompression in a recent release.

Work like a charm!
Thank you :3
