### ISSUE TITLE
Game request: Sorairo Innocent

### ISSUE THREAD

**Issue by Veshurik** [morkt/GARbro#309]
VNDB: https://vndb.org/v17980
Developer: AkabeiSoft3
Engine: Kirikiri
Format: .xp3

Thank you so much!

**Comment by Veshurik** [comment]
It uses "Akatsuki no Goei" encryption.

Can you just, please, add that game name in list in future? Thanks.

**Comment by a65090482** [comment]
[151211][あかべぇそふとすりぃ] 空色イノセント ―Sorairo Innocent―
XP3Viewer

**Comment by Veshurik** [comment]
Thanks, but I already choose "Akatsuki no Goei", and it works!
