### ISSUE TITLE
About Siglus engine pck

### ISSUE THREAD

**Issue by mireado** [morkt/GARbro#31]
Siglus engine is next(?) generation of RealLive engine by Visual Arts.

GARbro support almost everything of Siglus engine,
Cause Siglus engine using same type.

but,
Unfortunately, Siglus engine using another ARCformat 'pck'.

If you have interesting about this,
could you please support this type?

example game made by Visual Arts like
Angel Beats-1stBeat
フローラル・フローラブ
etc..

Thank you for reading >_<

**Comment by morkt** [comment]
i've looked into フローラル・フローラブ trial, the only PCK file there is 'SCENE.PCK', and it's not an archive, but a compiled game script. writing game code decompilers is far beyond my intents with GARbro. are there any other PCK files that i might have missed?

**Comment by mireado** [comment]
Oh.. I'm so sorry to bother you.
I was think it was archive.. sorry.
You might be right.

Thank you for kind answer >_<

**Comment by arcusmaximus** [comment]
Scene.pck is, in fact, an archive containing many .ss files (scenario scripts). However, extracting it is difficult because (as far as I know) it's always encrypted and every game has its own set of encryption keys. That said, the tool called SiglusExtract can not only extract but also repack it.
