### ISSUE TITLE
Could I repacking .pfs file with GARbro?

### ISSUE THREAD

**Issue by fkvldh** [morkt/GARbro#311]
(Sorry for my bad English)
Hello, morkt.
I'm trying to repack this into a VN to make an nude patch to this game.
But I've never worked with this file format before.
Aibeya アイベヤ
root.pfs
root.pfs.000
root.pfs.001

Could I repacking .pfs file with GARbro?
If anyone knows how to repack this/convert this file type and could give me some help, it would be greatly appreciated.

**Comment by Cerzs** [comment]
Artemis Engine does not need repack. Just put the folder in the same directory and it will work.

Example... Inside root.pfs.000: X/Y/Z.png extract it. Then copy the folder and paste it in the directory.

**Comment by fkvldh** [comment]
> Artemis Engine does not need repack. Just put the folder in the same directory and should work.
> 
> Example... Inside root.pfs.000: X/Y/Z.png extract it. Then copy the folder and paste it in the directory.

Thank you! But I'm idiot...
So... I extract file inside root.pfs, then just paste in same directory?
Wait, I will try.

**Comment by Cerzs** [comment]
Extract the folder that you need and paste it in the same directory. Then you can modify the images.

**Comment by fkvldh** [comment]
> Extract the folder that you need and paste it in the same directory. Then you can modify the images.

I'm really sorry, my bad english skill and my idiot.
Check my twitter. I upload screenshot.
[](https://twitter.com/translator444/status/1100504365901799429)

**Comment by fkvldh** [comment]
> Extract the folder that you need and paste it in the same directory. Then you can modify the images.

IT'S WORK. I UNDERSTAND NOW.
Thank you, Cerzs. Have a nice day!
