### ISSUE TITLE
Game request: Yume to Iro de Dekiteiru

### ISSUE THREAD

**Issue by TkzcM** [morkt/GARbro#312]
VNDB: https://vndb.org/v16516
Engine: Kirikiri
Format: .xp3

Thanks!

**Comment by morkt** [comment]
select 'no encryption' when asked.

**Comment by Veshurik** [comment]
Yeah, usually try always "no encryption", if possible. If it doesn't work, then open thread. Thanks

**Comment by TkzcM** [comment]
> select 'no encryption' when asked.

It doesn't seem to work with the v1.01 patch.xp3. :(
