### ISSUE TITLE
Game request: Purely x Cation [Trial] and .ks support

### ISSUE THREAD

**Issue by Veshurik** [morkt/GARbro#314]
VNDB: https://vndb.org/v18723
Engine: Kirikiri
Format: .xp3

Thank you so much.
When I open archives, it doesn't appear that I can choose decryption method. 
Only "uncorrect type of file" inside the archives. 

UPD. It happes for [Trial] version of game.
In full version only .ks files can't be opened.

UPD2. In main.dat - scenario files can't be opened. But if you extract them, only few of them can read normally through Notepad++. Bad encoding? 
I can open them in usual Notepad, save them, and they will show normally in Notepad++. But one file is still strange, 99マップアイテム入手イベント, it can't show anyway as normal text. Thank you for the help.

**Comment by morkt** [comment]
added trial.

can't help you with scripts.

**Comment by Veshurik** [comment]
Thank you so much!
