### ISSUE TITLE
Game request: SPIRAL!!

### ISSUE THREAD

**Issue by Veshurik** [morkt/GARbro#315]
VNDB: https://vndb.org/v24748
File extension: .pack

Thank you very much!

UPD. It works, but some file extension doesn't open (.b) and some CG are missing (for example, zzz02 in data4.pack - ... - ev). Thank you!

**Comment by morkt** [comment]
please provide some evidence that this file actually exists in archive. generally, if files are not displayed it means they don't exist. for *.b, provide exact name and location of files that can't be opened.

**Comment by Veshurik** [comment]
Yeah, again developer issue, patch provided with those content. Thanks!

**Comment by Veshurik** [comment]
Eh, I'm sorry, I just wanna be sure, is it okay or not.

data2.pack is 375Mb. When I extracts all fines from that archive, it becomes 366Mb. Is it okay?

In "bg" and "bgl" folders I can't see some backgrounds, which exists in comment .txt section.
7, 17, 18, 32.
I don't know if they are 9 Mb unextracted from archive or something else, and it's really developer issue.
I will try to play the game and find those unexisting background, maybe, it will help.
![1](https://user-images.githubusercontent.com/26744056/54197971-5e761d80-44d6-11e9-93a3-93042d134441.png)

**Comment by morkt** [comment]
> data2.pack is 375Mb. When I extracts all fines from that archive, it becomes 366Mb. Is it okay?

i can't confirm this. i see that data2.pack is 384'589'528 bytes long, files extracted from it are 384'574'781 bytes in total, the difference of 14k is a size of archive index.

**Comment by Veshurik** [comment]
Oh, wow... Yeah, I see, that game released in unfinished state, because adding patch with new CG arts, etc...
Well, yeah, I think, it's theif fault. Thank you again.

**Comment by Veshurik** [comment]
Ah, sorry again, one else question.
Is it okay that acrhives doesn't open with images of title screen?

For example:

data7.pack - script - title - titleback.b (921375 bytes). 

Thank you again as always!

**Comment by morkt** [comment]
made some adjustments to *.b interpreter in recent release.
