### ISSUE TITLE
The behavior of GARbro v1.5.43 is unstable...

### ISSUE THREAD

**Issue by thxalot** [morkt/GARbro#316]
After starting to use GARbro 1.5.43.2857, the program stopped responding for a while in the following situation.

- Opening the .arc(Majiro), .xp3, etc. -> Saving image as PNG -> No response for a while.
- Browsing in archives(contains ZIP archive) -> clicking back button -> No response for a while.

I wonder why AssemblyVersion and AssemblyFileVersion in "GameRes/Properties/AssemblyInfo.cs" changed from 1.5.42.**316** to 1.5.43.316.
According to the change history, former number of these variables was 1.5.42.**315**.

Since I am not familiar with programming, I apologize in advance that it may be saying something outrageous.

**Comment by morkt** [comment]
can't confirm such behavior here. does it happen to you every time or sporadically? [not that there's anything i can do about it in either case]

> changed from 1.5.42.316 to 1.5.43.316

[snarky comment removed] you're thinking too much pal. it doesn't matter. release number increases with each release, revision number is a total number of commits into repository.

**Comment by thxalot** [comment]
Thank you for your reply.
I'll check my Windows environment carefully again.
I'm very sorry for making you uncomfortable with my ignorance.
