### ISSUE TITLE
Where is Uchi no Kanojo(ExHibit) script?

### ISSUE THREAD

**Issue by fkvldh** [morkt/GARbro#317]
Hello.
I'm looking for script file, Uchi no Kanojo and Uchi no Imouto
But I can't find.
Engine is ExHibit.
Uchi no Kanojo =家の彼女
Uchi no Imouto=家の妹

**Comment by morkt** [comment]
i don't know.

**Comment by fkvldh** [comment]
> i don't know.

I see. It's ok.

**Comment by fkvldh** [comment]
> > > i don't know.
> > 
> > 
> > I see. It's ok.
> 
> .../(game)/rld

Oh, Thank you!
