### ISSUE TITLE
Support for Microsoft cabinet archives

### ISSUE THREAD

**Issue by EAxp3** [morkt/GARbro#32]
Please add support archive .cab in used GAME in ExHIBIT

I don't want extract the files to view pictures
I hope you can please support
thanks for your great work :+1: 

[info-.cab-1](https://en.wikipedia.org/wiki/Cabinet_%28file_format%29)
[info-.cab-2](https://msdn.microsoft.com/en-us/library/bb417343.aspx)
[info-.cab-3](http://www.sweetscape.com/010editor/templates/files/CABTemplate.bt)

![captura](https://cloud.githubusercontent.com/assets/15073580/17546471/ddc19190-5ea7-11e6-86fe-959877a615f2.PNG)

![captura2](https://cloud.githubusercontent.com/assets/15073580/17547299/fb921a4c-5eab-11e6-844a-8f502f479312.PNG)

**Comment by morkt** [comment]
while it would be handy to be able to navigate cab archives, i'm not motivated enough to implement it anytime soon. there's already plenty of third-party tools that could do that (like 7-zip on your screenshot). i'm feeling like re-inventing wheel here, and the fact that format itself is somewhat complicated doesn't help.

bottom-line: unlikely to happen.

**Comment by morkt** [comment]
added in v1.3.23

**Comment by EAxp3** [comment]
👍 :mexico:
