### ISSUE TITLE
Could you convert image files to GYU?

### ISSUE THREAD

**Issue by fkvldh** [morkt/GARbro#320]
[GarBro not supporting .gyu files]
https://github.com/morkt/GARbro/issues/108

Hello. I have a question.
I know GYU is image format.
If GarBro can convert GYU files to another format, convert other image format to GYU files?
I need that files for making patch.

I hope you support convert image to GYU, but if you don't want it's ok.

**Comment by Entangled-Cable** [comment]
You don't need to, because Exhibit can read .png files as well. Also, for your question in the other thread, script files are always in a folder called rld (encrypted, obviously). I could dump them for you, but you need to promise me you're not going to translate the games to English.

**Comment by fkvldh** [comment]
> You don't need to, because Exhibit can read .png files as well. Also, for your question in the other thread, script files are always in a folder called rld (encrypted, obviously). I could dump them for you, but you need to promise me you're not going to translate the games to English.

Thank you.
But I will find other way.

**Comment by a65090482** [comment]
> > You don't need to, because Exhibit can read .png files as well. Also, for your question in the other thread, script files are always in a folder called rld (encrypted, obviously). I could dump them for you, but you need to promise me you're not going to translate the games to English.
> 
> Thank you.
> But I will find other way.

The official website of the development tool: http://www.retouch.info/
