### ISSUE TITLE
Cant read/convert webp format files on few system

### ISSUE THREAD

**Issue by yonghengweilan** [morkt/GARbro#321]
When reading webp files or extracting it to other image format the GUI shows "parameter error", this issue only appears at few systems, checked trouble shooting and find nothing, tried to change libwebp.dll to another version even compiled by myself. Not working at all.

**Comment by morkt** [comment]
could you copy-paste contents of "Help | Troubleshooting..." window on the system where error occurs?

**Comment by yonghengweilan** [comment]
oh solved after windows update patch, thanks anyway... I think its just because the support of webp functions/lib was too old.
