### ISSUE TITLE
Game request: Hataraku Otaku no Ren'ai Jijou

### ISSUE THREAD

**Issue by Veshurik** [morkt/GARbro#323]
VNDB: https://vndb.org/v19592
Engine: Kikiriki
Format: .xp3

Thank you so much!

**Comment by morkt** [comment]
i've updated formats database, use 'check for updates' to update.

**Comment by Veshurik** [comment]
![image](https://user-images.githubusercontent.com/26744056/54151443-e19e6180-444b-11e9-9efd-b1f1fafb5ca0.png)
Click "update", but nothing happens, waiting really long. Is it okay?

**Comment by Veshurik** [comment]
Just wait some time, and finally it finished, thank you!
