### ISSUE TITLE
Game Request: IxSHE Tell [Background issue]

### ISSUE THREAD

**Issue by Veshurik** [morkt/GARbro#324]
VNDB: https://vndb.org/v21956
File extension: .pfs

In root.pfs.000 - image - bg...
Can't extract backgrounds with files _ix_bg... and ix_bg...

There is no other way to extract images from game (it works such way only for background, CG are okay, and I don't know what the problem)?

Thank you so much!

![1](https://user-images.githubusercontent.com/26744056/54235101-8f2f7480-4521-11e9-80e7-3e56489f302b.jpg)

**Comment by morkt** [comment]
it's a NET framework issue, can't do anything about it. just extract them without conversion, they could be viewed with any other program just fine.
