### ISSUE TITLE
Game request: Steam Prison [BGI/Ethornell]

### ISSUE THREAD

**Issue by Tialey** [morkt/GARbro#326]
VNDB: https://vndb.org/v19397
Format: .arc

Thank you so much!

**Comment by morkt** [comment]
are you using the latest garbro release? because i don't see an issue with these archives, they are opening fine, with images and audio inside them accessible.

**Comment by Tialey** [comment]
The problem is that I didn't fully understand how to run the program

**Comment by Tialey** [comment]
Yeah, it kind of worked. But how to change something to make it appear in the game?

**Comment by morkt** [comment]
you should have been more clear in your initial post. to answer your question: i don't know.
