### ISSUE TITLE
Can't open archives when GARbro placed in UNC Folder

### ISSUE THREAD

**Issue by hayabusa2yk** [morkt/GARbro#327]
I can't open any archives when I extracted GARbro in UNC Folder.
And there is no problem with GARbro in local folder (Desktop).
Checked with: "Amazing Grace" (type:arc)
OS: Windows 10 Home
Framework version: 4.0.30319.42000
Framework release: 461814 (4.7.1+)
GARbro: 1.5.43.2857
Formats database version: 142

Loaded assemblies:
GARbro.GUI 1.5.43.2857
GARbro.GUI.resources 1.5.43.2857
GameRes 1.5.43.316
GameRes.resources 1.5.43.316
ArcFormats 1.2.47.2120
System.Windows.Controls.Input.Toolkit 3.5.40128.1
WPFToolkit 3.5.40128.1
NAudio 1.8.4.0

Error screenshot:
![image](https://user-images.githubusercontent.com/32059738/54479552-36354880-4861-11e9-86f6-e346b6177ab5.png)

(Sorry for my bad English)

**Comment by morkt** [comment]
then don't put GARbro in UNC folder, it's supposed to reside in the standard "Program Files" folder.
