### ISSUE TITLE
Game request: [SQUEEZ] Honoo no Haramase Oppai Nyuu Doukyuusei

### ISSUE THREAD

**Issue by Eu-Other** [morkt/GARbro#329]
Extension: * .PAK
VNDB : https://vndb.org/v11133

**Comment by morkt** [comment]
what exact archive you're experiencing trouble with? as far as i can see, these archives are supported all right.

**Comment by Eu-Other** [comment]
Пишет файл не может быть открыт как архив ресурсов. При чем пробовал открыть .pak файлы других игр. 
Я видел в списке поддерживаемых игр есть одна от SQUEEZ , на ней не испытывал .
До Garbro пытался открыть с помощью arc_unpacker , единственное что получалось из архива это один .gr файл и это касается тольки игр от SQUEEZ остальные с расширением .pak открывало.
Думал может поможешь с этим . Сэнк!

**Comment by Eu-Other** [comment]
Все норм , это я что то затупил . 
Просто установил не через экзешник а просто архив закинул .
Сэнк ю вэри мач !
