### ISSUE TITLE
Game Request: Shogun-sama wa Otoshigoro

### ISSUE THREAD

**Issue by SenaKaito** [morkt/GARbro#331]
VNDB: https://vndb.org/v21931
Developer: ALcot

Unable to decrypt *.xp3 file.
Thank you :3

**Comment by SenaKaito** [comment]
What is *.sig files for?
Signature for what?

**Comment by morkt** [comment]
i've updated formats database, you may download it using 'check for updates' menu option.

> Signature for what?
for corresponding files they share a filename with.

**Comment by SenaKaito** [comment]
Wow, so fast as always.
Thank you so much!

I wanna ask,
Is there any faster/easier way to extract .pna files instead clicking on them one-by-one?
