### ISSUE TITLE
Game Request: Soushuu Senshinkan Gakuen Bansenjin

### ISSUE THREAD

**Issue by kinoulo** [morkt/GARbro#333]
https://vndb.org/v16131
Engine: Malie
Developer: light

**Comment by morkt** [comment]
support was added a year ago #172

please elaborate on your issue, particularly what's your game release, and whether you're able to open archives at all.

**Comment by kinoulo** [comment]
I'm sorry, I misunderstood.
I appreciate your listening to me.

**Comment by morkt** [comment]
closing as insubstantial.
