### ISSUE TITLE
can i use this tools to unpack xp3 files with command line

### ISSUE THREAD

**Issue by sh2288** [morkt/GARbro#334]
maybe like run this command d:\GARbro\GARbro.GUI.exe data.xp3 d:\unpack\data 
then the file data.xp3 will unpack to d:\unpack\data

**Comment by morkt** [comment]
this project is built around gui. there's plenty of command-line extraction tools out there, especially for xp3 files. i suggest you seek an alternative or write one yourself using `Console` project as an example.
