### ISSUE TITLE
Unable to extract from Grisaia Phantom Trigger Vol.3 and Vol.4

### ISSUE THREAD

**Issue by Pokom123** [morkt/GARbro#337]
I tried to extract image from .xp3 files but it said file could not be opened as resource archive but I had no problem with Vol. 1, Vol.2 and Vol.5. So can you look into it?

**Comment by morkt** [comment]
apparently steam version uses different encryption from japanese release.

i've disabled game detection in new formats database, you may download it using "check for updates" menu option. select "grisaia phantom trigger [steam]" when asked for encryption.

**Comment by Pokom123** [comment]
Thanks. It works.
