### ISSUE TITLE
Lambda unpacker code doesn't seem to work correcly

### ISSUE THREAD

**Issue by galtgendo** [morkt/GARbro#343]
This might be bogus, cause I might just be failing to see something in the C# code, that's obvious to someone who actually knows the language, but...

For my own reason, I've rewritten that unpacker into a python script.
It failed to work, until I've made a minor logic change, then it worked just fine.

That change was turning:
```python
    i_file.seek(offset+0x14)
    frame_offset = struct.unpack('<l', i_file.read(4))[0]
```

into
```python
    i_file.seek(offset+0x14)
    frame_offset = struct.unpack('<l', i_file.read(4))[0]
    i_file.seek(offset+frame_offset)
    frame_offset = struct.unpack('<l', i_file.read(4))[0]
```
So, did I somehow got the offsets wrong in that single place or is it something else ?

For reference:
initial value of frame_offset was 0x20, after second read - 0x30.

**Comment by morkt** [comment]
i have no idea what is it you're talking about. a reference to an actual garbro codebase and whatever game it's failing on would be nice.

**Comment by galtgendo** [comment]
ArcFormats/Lambda/ImageCLS.cs: ClsFormat.ReadMetaData(IBinaryStream file)

**Comment by galtgendo** [comment]
...and for reference, the relevant part of the file (starting from CLS_TEXFILE):
```
43 4C 53 5F 54 45 58 46 49 4C 45 00 00 00 00 00
01 00 00 00 20 00 00 00 30 00 00 00 40 0C 00 00
30 00 00 00 10 0C 00 00 00 00 00 00 00 00 00 00
```

**Comment by galtgendo** [comment]
oops...
OK, I've figured out which part confused me - my bad, the code in the repo is correct.
