### ISSUE TITLE
problems with files: CIRCUS

### ISSUE THREAD

**Issue by EAxp3** [morkt/GARbro#35]
I can not open files: (.pcm)-(.CRX)
Unknown file: (.CRM) --> What contain inside?
[GAME](https://vndb.org/v17742)

game files in case you need
[DATA](https://mega.nz/#!o1xAlZTa!Hv6GzXwbeze3-Bi-VgyHFdbZw27h4DxgLz-29KuNbf8)

**Comment by morkt** [comment]
seems working now.

**Comment by EAxp3** [comment]
### great thank you very much :gear:  👍
