### ISSUE TITLE
Game Request: Symphonic Rain NSwitch

### ISSUE THREAD

**Issue by wwwklopar** [morkt/GARbro#352]
Engine: probably Kogado
Format extension: .kgo
GarBro can't open this files
Thanks!

**Comment by wwwklopar** [comment]
[script.zip](https://github.com/morkt/GARbro/files/3134530/script.zip)
Files

**Comment by morkt** [comment]
these are game script files, writing script decompiler lies beyond the scope of this project, i suggest you look for it elsewhere.
