### ISSUE TITLE
key file-->start.mjo ---> (Majiro)--You could implement this option (GARbro)

### ISSUE THREAD

**Issue by EAxp3** [morkt/GARbro#36]
I have found key file --> start.mjo (in the File-->scenario.arc)
This file contains the keys to decrypt the files.

I found a tool that extracts files using (start.mjo).
could you please add that function to (GARbro).
incredibly serious, and that would support most games (Majiro).

-eh I tried to find the encryption key for use in (GARbro)
but not eh succeeded.

![3](https://cloud.githubusercontent.com/assets/15073580/18981637/de61ad76-86a5-11e6-8a6b-3c2c55068e0e.PNG)

Could you implement an option to open this file to decrypt files?

[tool used + screenshots](https://mega.nz/#!8tYjTJTT!7eIvRh2ci8UsFnzYrXhgXRevxCzvZK-2Qv3UTgXWDdI)

sorry for my bad English.

**Comment by EAxp3** [comment]
it seems that the file (start.mjo) is compressed using zlib.
I extracted the file (start.mjo) using GARbro but is not readable.
extracting files (scenario.arc) using the tool seems that decompresses including (start.mjo).

possible key found
![key found](https://cloud.githubusercontent.com/assets/15073580/18982999/e5e42af6-86af-11e6-9198-b2ac290f6512.PNG)

the key functions in GARbro
used game: [Love La Bride](https://vndb.org/v12028)
I hope this is the place where is the key to other games that use (Majiro).

**Comment by morkt** [comment]
no, i'm not going to add MJO decryption.

if i remember correctly you could type password you found into a pop-up dialog when viewing CG archives.

**Comment by EAxp3** [comment]
then it is the same password for all games?

**Comment by morkt** [comment]
no, it's different in every game.
