### ISSUE TITLE
Request: Sankaku Ren'ai: Love Triangle Trouble! (aka Suki to Suki to de Sankaku Ren’ai)

### ISSUE THREAD

**Issue by GuyInDogSuit** [morkt/GARbro#367]
VN by ASa Project, published by NekoNyan. XP3 format. No encryption seems to work on it.

**Comment by lsssk11331** [comment]
Try Kari Gurashi Ren'ai (MadoCrypt)

**Comment by GuyInDogSuit** [comment]
That works! Thank you!

**Comment by hsgwktb** [comment]
"Renai Karichaimashita: Koikari – Love For Hire" this game also works, LOVE YOU!
