### ISSUE TITLE
Can't open .pak from Kaigen's Ambition

### ISSUE THREAD

**Issue by 730730** [morkt/GARbro#37]
I'm not sure if Kaigen's Ambition is included in the Hanachirasu behind the .pak row in the supported games list, but I'm not sure where else to ask.
I assign the file type of the 'sound.pak' to audio, then double click/enter, but nothing happens, not even an error. 
If I attempt to Extract it I get the error "sound.pak: file could not be opened as resource archive".
The game is an English translated version by the way, if that means anything.

**Comment by morkt** [comment]
most likely it uses a different encryption, i'll look into it.

**Comment by 730730** [comment]
Thanks! By the way, I'm having the same problem with the sound.npa from Hanachirasu itself, though when I try to open it it does load for a while, albeit with no results.

**Comment by morkt** [comment]
i've updated pre-release with this fix.
