### ISSUE TITLE
Cannot open .npk files

### ISSUE THREAD

**Issue by PikaDude** [morkt/GARbro#38]
Hi, I recently tried to use this program to open the npk files located in Sonicomi's game directory, however, I receive an error saying "File could not be opened as resource archive" despite the program supporting npk files in the list. Am I doing something wrong?

**Comment by morkt** [comment]
probably. read #20, maybe it would help.

**Comment by PikaDude** [comment]
I followed the instructions on the issue you had linked me. After unblocking everything it still does not register the file.

**Comment by PikaDude** [comment]
Fixed the problem by deleting all the files and trying again multiple times... somehow
