### ISSUE TITLE
Game Request: How to Raise a Wolf Girl

### ISSUE THREAD

**Issue by GuyInDogSuit** [morkt/GARbro#392]
Can anyone help me extract files from "How to Raise a Wolf Girl"? Garbro can open the XP3 files, but can't read the files inside, and when I extract them, the images are blank and the files can't be opened. I've tried other programs as well, none seem to work.

**Comment by uyjulian** [comment]
Use KrkrExtract

**Comment by Veshurik** [comment]
Yeah, KrKrExtract helped (but with command line option, because usually it doesn't work)
