### ISSUE TITLE
Issue when trying to access Shiniyuku Kimi, Yakata ni Mebuku Zouo even when it should be supported

### ISSUE THREAD

**Issue by Ryona-Fang** [morkt/GARbro#399]
Game Romanji Title: Shiniyuku Kimi, Yakata ni Mebuku Zouo
VNDB Link: https://vndb.org/v19233
Format: xp3

Hi from what i understood here https://github.com/morkt/GARbro/issues/193 Shiniyuku Kimi, Yakata ni Mebuku Zouo is now supported, but it has a weird issue which i will be describing now:

 Normally whenever i open any other (that is not from Shiniyuku Kimi, Yakata ni Mebuku Zouo)  .xp3 archive a menu pops up that asks me to choose a an encryption or "no encryption", in that list of encryptions there is also the title "Shiniyuku Kimi, Yakata ni Mebuku Zouo". But whenever i try to open Shiniyuku Kimi, Yakata ni Mebuku Zouo .xp3 archives i get no menu pop up and while it does enter the archive i can't preview or access any on the files, it says invalid files. Does anyone have any solutions ? I tried older versions of GARbro but with no success.

**Comment by scese250** [comment]
I can open the XP3, it doesn't ask me what kind of encryption. I bet there's two version of this game, DVD and DL version, I have the DL one. 

I tried to replicate the problem deleting everything related to the GARBro program, like the %localappdata%\mørkt folder. 

However, if you want the CGs and sprites, I can provide you a link with such files.

**Comment by Ryona-Fang** [comment]
> I can open the XP3, it doesn't ask me what kind of encryption. I bet there's two version of this game, DVD and DL version, I have the DL one.
> 
> I tried to replicate the problem deleting everything related to the GARBro program, like the %localappdata%\mørkt folder but I still I can open the XP3 without problems, sorry if I can't help you.
> 
> However, if you want the CGs and sprites, I can provide you a link with such files.

The CG i have, but i did want to get my hands on the CH Sprites, and indeed what i have is the DVD version, not the DL one.

**Comment by scese250** [comment]
I recommend to download the sprites from Internet because if you rip them from the game you'll have sprites without face/expressions and you have to assemble everything :P

**Comment by Ryona-Fang** [comment]
> I recommend to download the sprites from Internet because if you rip them from the game you'll have sprites without face/expressions and you have to assemble everything :P

I already prepared myself mentally for that XD, this artist usually always has sprites that need assembly, and there aren't any Sprites on the net unfortunately, as i did check for it before hand.

**Comment by scese250** [comment]
> > I recommend to download the sprites from Internet because if you rip them from the game you'll have sprites without face/expressions and you have to assemble everything :P
> 
> I already prepared myself mentally for that XD, this artist usually always has sprites that need assembly, and there aren't any Sprites on the net unfortunately, as i did check for it before hand.

Nah, there is sprites in the net, it's in the CG collection but searching I can't find the page that I downloaded from :/ Well, then download the DL version: https://drive.google.com/open?id=1q85nFv8sxpsL9IlaGxGEe3-GUlT6XTcU

I'll edit the comment once I confirm you downloaded it! Hope it work for you

**Comment by Ryona-Fang** [comment]
> > > I recommend to download the sprites from Internet because if you rip them from the game you'll have sprites without face/expressions and you have to assemble everything :P
> > 
> > 
> > I already prepared myself mentally for that XD, this artist usually always has sprites that need assembly, and there aren't any Sprites on the net unfortunately, as i did check for it before hand.
> 
> Nah, there is sprites in the net, it's in the CG collection but searching I can't find the page that I downloaded from :/ Well, then download the DL version: https://drive.google.com/open?id=1q85nFv8sxpsL9IlaGxGEe3-GUlT6XTcU
> 
> I'll edit the comment once I confirm you downloaded it! Hope it work for you

Thank you very much i started the download now, should take about 30 minutes tops, really thank you for the help, but now i gotta run for work though lol.

**Comment by Ryona-Fang** [comment]
> > > I recommend to download the sprites from Internet because if you rip them from the game you'll have sprites without face/expressions and you have to assemble everything :P
> > 
> > 
> > I already prepared myself mentally for that XD, this artist usually always has sprites that need assembly, and there aren't any Sprites on the net unfortunately, as i did check for it before hand.
> 
> Nah, there is sprites in the net, it's in the CG collection but searching I can't find the page that I downloaded from :/ 
> 
>  Hope it work for you

Thank you very much i finished downloading now, really thank you for the help, but now i gotta run for work though lol.

**Comment by scese250** [comment]
No problem, I'm fan of this game too. You're able to open the XP3?

**Comment by Ryona-Fang** [comment]
> No problem, I'm fan of this game too (and of Rubi-sama). You're able to open the XP3?

Unfortunately i had to run to catch my ride to work (saw the msg just as i left the house) , i plan on testing it as soon as my night shift ends  
and i had some rest XD.

**Comment by scese250** [comment]
> Unfortunately i had to run to catch my ride to work (saw the msg just as i left the house) , i plan on testing it as soon as my night shift ends
> and i had some rest XD.
Oh, okay then, good luck in the work

**Comment by Ryona-Fang** [comment]
> > Unfortunately i had to run to catch my ride to work (saw the msg just as i left the house) , i plan on testing it as soon as my night shift ends
> > and i had some rest XD.
> > Oh, okay then, good luck in the work

I just got to test it and thank you it worked great! 

-------------


Basically thread wise the outline of all this is that Garbro is only compatible with the DL version the game not the Disk version.
