### ISSUE TITLE
need help! After using GARbro to extract the bsa suffix game file of BISHOP, how to encapsulate the file back to the bsa suffix file again.

### ISSUE THREAD

**Issue by yuaniyuan** [morkt/GARbro#430]
bsa is the original file of the game, 03 is the extracted folder, and bsg is the picture file in the original format. How to package the extracted files into bsa suffix files again and e
![garbro bsa](https://user-images.githubusercontent.com/69374956/89700484-d3b28000-d960-11ea-9afa-31e9321ed2cf.png)
![QQ截图20200806103918](https://user-images.githubusercontent.com/69374956/89700490-d57c4380-d960-11ea-83ca-5a87cb7d6e09.png)
![QQ截图20200806110307](https://user-images.githubusercontent.com/69374956/89700494-d7460700-d960-11ea-9f54-540b6003856b.png)

nsure that the game can be read normally when running.

**Comment by daoluong** [comment]
dont have blue stick so it not support repack

**Comment by yuaniyuan** [comment]
> 没有蓝色的棍子，所以它不支持重新包装

It's a pity, I don't know if the author will add the bsa file packet function in the later stage, it is really needed.

**Comment by daoluong** [comment]
whats extract the game you are talking about?

**Comment by yuaniyuan** [comment]
> 什么能提取您正在谈论的游戏？
Extracting files? GARbro can be extracted, but if you want to stitch the extracted image files yourself, you need exbsa and GALphotoauto. Because the picture files extracted by GARbro do not have X, Y coordinates, it will be more troublesome to synthesize pictures. The image files extracted by exbsa will provide X, Y coordinates, which can be automatically synthesized by edible GALphotoauto.
