### ISSUE TITLE
Game Request : 英雄＊戦姫GOLD

### ISSUE THREAD

**Issue by Desmony** [morkt/GARbro#461]
VNDB : https://vndb.org/v12033
Developer : Tenco
Extension: .dat (Repipack)

What is weird is that it works perfectly with the first opus which uses the same extensions

![image](https://user-images.githubusercontent.com/33091422/108430417-9ef18080-7241-11eb-8248-2322ba98ce53.png)

**Comment by daoluong** [comment]
use repipack
