### ISSUE TITLE
Add option to save images in bsg Format and Create Archives in bsa format.

### ISSUE THREAD

**Issue by pratikpatel8982** [morkt/GARbro#474]
I am able to extract .bsa images in png format but I cannot convert .png back to .bsg. I know Image conversion is no longer developed but if @morkt you can create a standalone script, then it would be useful.

Also I am able to extract .bsa archives with GARbro but I cannot repack them back to their orignal format (.bsa) so tha the game can load it. Can you please support repacking in .bsa format.

**Comment by Cosetto** [comment]
> I am able to extract .bsa images in png format but I cannot convert .png back to .bsg. I know Image conversion is no longer developed but if @morkt you can create a standalone script, then it would be useful.
> 
> Also I am able to extract .bsa archives with GARbro but I cannot repack them back to their orignal format (.bsa) so tha the game can load it. Can you please support repacking in .bsa format.

Here man https://github.com/crskycode/Bishop_BSG_Tool

**Comment by pratikpatel8982** [comment]
Thanks
