### ISSUE TITLE
Request: "Add Support for more Kirikiri"

### ISSUE THREAD

**Issue by sakuhanachan** [morkt/GARbro#48]
Engine: Kirikiri 2
[Clover Day's](https://vndb.org/v13325)
file extension: .xp3

Engine: Kirikiri Z
[Otome ＊ Domain](https://vndb.org/v18149)
[Karenai Sekai to Owaru Hana](https://vndb.org/v19658)
file extension: .xp3
※use Download version for test

**Comment by morkt** [comment]
i believe amatsutsumi is supported already, and i don't have any plans to add support for video files.

**Comment by sakuhanachan** [comment]
Sorry, I forgot to see support formats list.

**Comment by morkt** [comment]
added and updated pre-release build.
