### ISSUE TITLE
BGI ARC repack support?

### ISSUE THREAD

**Issue by 0xh3LL0** [morkt/GARbro#49]
will you add bgi arc repack / creation support...?
i always use AE but its not updated anymore...

**Comment by mireado** [comment]
https://github.com/minirop/arc-reader
https://github.com/vn-tools/arc_unpacker

you can check above source

**Comment by marcussacana** [comment]
big don't need repack, some builds of bgi game have a checksum in the .arc, just put the file extracted into the game folder and launch...

**Comment by 0xh3LL0** [comment]
found alternative. closed.
