### ISSUE TITLE
Can't extract KARAKARA

### ISSUE THREAD

**Issue by krrr** [morkt/GARbro#51]
I have selected KARAKARA when opening archive, but all extracted files are corrupted.

Is encryption key changed? I know a little assembly, if you tell me how to maybe i can find it by myself

**Comment by morkt** [comment]
be specific. game has like 3 or 4 releases, which one are you using?

**Comment by krrr** [comment]
latest version from steam (karakara.exe file ver 1.2.0.3)

**Comment by morkt** [comment]
then it means steam release is not supported. try "no encryption" option, if it fails then you're out of luck, i don't have plans to obtain it anytime soon.

**Comment by krrr** [comment]
"no encryption" fails too☠
