### ISSUE TITLE
創作彼女の恋愛公式 ERROR

### ISSUE THREAD

**Issue by SanLukaku** [morkt/GARbro#515]
Garbro does not display a file, I would like to be able to extract some sprites
https://vndb.org/v31136

**Comment by Cosetto** [comment]
https://github.com/crskycode/GARbro use this, after download mod version download Format.dat then copy to GARbro/Gamedata, new crypt for sousaku  kanojo will be available

**Comment by SanLukaku** [comment]
In the link I did not find the Format.dat file only in previous versions, but those do not have Sousaku
![image](https://user-images.githubusercontent.com/66498710/151412127-4df4e296-c7cd-440a-954e-9e6669b322a9.png)

**Comment by Cosetto** [comment]
> In the link I did not find the Format.dat file only in previous versions, but those do not have Sousaku ![image](https://user-images.githubusercontent.com/66498710/151412127-4df4e296-c7cd-440a-954e-9e6669b322a9.png)

In the code Arcformat/Resources/Format.dat

**Comment by Cosetto** [comment]
https://github.com/crskycode/GARbro/tree/master/ArcFormats/Resources here, click on Format.dat and then view raw

**Comment by SanLukaku** [comment]
> https://github.com/crskycode/GARbro/tree/master/ArcFormats/Resources here, click on Format.dat and then view raw

Thank you very much for your patience and help, I really appreciate it.
