### ISSUE TITLE
Game Request: Rui wa Tomo o Yobu Full voiced Edition

### ISSUE THREAD

**Issue by Madaoism** [morkt/GARbro#526]
Game: https://vndb.org/v776
Release: https://vndb.org/r9924
Engine: Kirikiri
Extension: .xp3

Rui wa Tomo o Yobu regular edition is currently supported, but the Full Voice edition uses different CxEncryption key. Based on my research, the key is likely to be this:

0x24A, 0x3C4

Control block and branch orders are also down below (though I never tested it so I don't know if it's actually accurate).

Source: [Kirikiroid2 Ruitomo full voice edition patch](https://zeas2.github.io/Kirikiroid2_patch/patch/%E6%9A%81WORKS/%E3%82%8B%E3%81%84%E3%81%AF%E6%99%BA%E3%82%92%E5%91%BC%E3%81%B6%20-%E3%83%95%E3%83%AB%E3%83%9C%E3%82%A4%E3%82%B9%E3%82%A8%E3%83%87%E3%82%A3%E3%82%B7%E3%83%A7%E3%83%B3-/xp3filter.tjs)

**Comment by Cosetto** [comment]
> Game: https://vndb.org/v776 Release: https://vndb.org/r9924 Engine: Kirikiri Extension: .xp3
> 
> Rui wa Tomo o Yobu regular edition is currently supported, but the Full Voice edition uses different CxEncryption key. Based on my research, the key is likely to be this:
> 
> 0x24A, 0x3C4
> 
> Control block and branch orders are also down below (though I never tested it so I don't know if it's actually accurate).
> 
> Source: [Kirikiroid2 Ruitomo full voice edition patch](https://zeas2.github.io/Kirikiroid2_patch/patch/%E6%9A%81WORKS/%E3%82%8B%E3%81%84%E3%81%AF%E6%99%BA%E3%82%92%E5%91%BC%E3%81%B6%20-%E3%83%95%E3%83%AB%E3%83%9C%E3%82%A4%E3%82%B9%E3%82%A8%E3%83%87%E3%82%A3%E3%82%B7%E3%83%A7%E3%83%B3-/xp3filter.tjs)

try to pull request this [GARbro mod](https://github.com/crskycode/GARbro) he will add new crypt to Format.dat

**Comment by Cosetto** [comment]
or you can add the crypt yourself using [this](https://github.com/crskycode/GARbro/blob/master/SchemeTool/Program.cs)

**Comment by Madaoism** [comment]
Managed to do it somehow myself. Thanks though! 

> or you can add the crypt yourself using [this](https://github.com/crskycode/GARbro/blob/master/SchemeTool/Program.cs)

**Comment by Cosetto** [comment]
Wait, can you also add the crypt for the new https://vndb.org/v26414 Steam version too? Idk how to find the crypt of that one

**Comment by Madaoism** [comment]
> Wait, can you also add the crypt for the new https://vndb.org/v26414 Steam version too? Idk how to find the crypt of that one

Does GarBRO Mod's Cafe Stella decryption not work? It seems to be available there already. 

If so, it will require you to either fish around online to find the CxEncryption keys somewhere (which is what I did), or use reverse engineering frameworks on the cafe stella executable to trace the crypt code.

**Comment by Cosetto** [comment]
GARbro mod crypt is the original version, I wish I could use krkrextract to do dump but the Steam version uses SmartSteamLoader.exe so I can't do anything about it. Crsky has his [guide](https://github.com/crskycode/GalgameCoding/blob/main/Kirikiri/HowToFindCxEncryptKey/FindCxdecKey_CN.md) for finding the crypt for krkrz but it's in Chinese so I don't understand

**Comment by Madaoism** [comment]
> GARbro mod crypt is the original version, I wish I could use krkrextract to dump but the Steam version uses SmartSteamLoader.exe so I can't do anything about it. Crsky has his [guide](https://github.com/crskycode/GalgameCoding/blob/main/Kirikiri/HowToFindCxEncryptKey/FindCxdecKey_CN.md) for finding the crypt for krkrz but it's in Chinese so I don't understand

Unfortunately I can't help you much in that front, other than telling you to use google translate on the page or something. It requires you have a strong understanding of how the crypt work, what kind of assembly code you should be looking for, etc. These are the numbers you will need to obtain. 

```
uint Mask;
uint Offset;
byte[3] PrologOrder;
byte[6] OddBranchOrder;
byte[8] EvenBranchOrder;
uint[] ControlBlock;
```

You can try reaching out to people on Fuwanovel or some fanTL groups and ask them for tips too.

**Comment by Madaoism** [comment]
Also, is there any reason you need to unpack a translated version of the game? If you just need the CG files or something, just try unpacking the japanese version.

**Comment by Cosetto** [comment]
> Also, is there any reason you need to unpack a translated version of the game? If you just need the CG files or something, just try unpacking the japanese version.

I need the crypt in order to help my friend making the patch for our mother tongue

**Comment by SanLukaku** [comment]
> Managed to do it somehow myself. Thanks though!
> 
> > or you can add the crypt yourself using [this](https://github.com/crskycode/GARbro/blob/master/SchemeTool/Program.cs)

Could you share your file to be able to extract the Atori and Tomo sprites?
