### ISSUE TITLE
Game Request-->"Add Support(Honoo no Haramase Oppai ★ Ero Appli Gakuen)"

### ISSUE THREAD

**Issue by EAxp3** [morkt/GARbro#53]
[GAME](https://vndb.org/v19345)

SQUEEZ
EAGLS
![3](https://cloud.githubusercontent.com/assets/15073580/23833097/9ab4a164-0706-11e7-924f-bbf46dd650f7.png)

Error open archive .pak

**Comment by morkt** [comment]
supported now.
