### ISSUE TITLE
[Game Request]美少女万華鏡

### ISSUE THREAD

**Issue by s567901** [morkt/GARbro#537]
VNDB: https://vndb.org/v8038
Developer: ωstar
Engine: ？？？
Extension: .pack

Export file tips：
The object reference is not set to an instance of the object

**Comment by Cosetto** [comment]
Are you upacking the English patch? If yes then use this Are you unpacking the English patch? If yes then drag the .pack to
[arc_conv.zip](https://github.com/morkt/GARbro/files/8685534/arc_conv.zip)
If the original archive then use ExtractData

**Comment by s567901** [comment]
It's working! thanks

**Comment by Cosetto** [comment]
close issue
