### ISSUE TITLE
unless terminalia

### ISSUE THREAD

**Issue by jackwaecow** [morkt/GARbro#541]
Hi there, any idea what's the Archive version and 8-bit encryption key for the ypf for Unless Terminalia?

**Comment by Cosetto** [comment]
> Hi there, any idea what's the Archive version and 8-bit encryption key for the ypf for Unless Terminalia?

https://github.com/Xorboth/YPF-Manager

**Comment by jackwaecow** [comment]
> > Hi there, any idea what's the Archive version and 8-bit encryption key for the ypf for Unless Terminalia?
> 
> https://github.com/Xorboth/YPF-Manager

I have no idea how to use something that's not exe

**Comment by jackwaecow** [comment]
> > Hi there, any idea what's the Archive version and 8-bit encryption key for the ypf for Unless Terminalia?
> 
> https://github.com/Xorboth/YPF-Manager

can you teach me how to use this?

**Comment by Cosetto** [comment]
[ypf.zip](https://github.com/morkt/GARbro/files/8934784/ypf.zip)
Run it with cmd: ypf.exe -e cg.ypf

**Comment by jackwaecow** [comment]
> [ypf.zip](https://github.com/morkt/GARbro/files/8934784/ypf.zip) Run it with cmd: ypf.exe -e cg.ypf

I really tried but cmd just makes my head spin, is it possible to just figure out the archive version and 8-bit encryption key from Garbro?
![image](https://user-images.githubusercontent.com/107541724/177022600-a930d671-ab90-40da-9b5e-0ff4f05b0965.png)

**Comment by qbb95** [comment]
> [ypf.zip](https://github.com/morkt/GARbro/files/8934784/ypf.zip) 用cmd运行：ypf.exe -e cg.ypf

You should use -p instead of -e here

**Comment by Cosetto** [comment]
> > [ypf.zip](https://github.com/morkt/GARbro/files/8934784/ypf.zip) Run it with cmd: ypf.exe -e cg.ypf
> 
> I really tried but cmd just makes my head spin, is it possible to just figure out the archive version and 8-bit encryption key from Garbro? ![image](https://user-images.githubusercontent.com/107541724/177022600-a930d671-ab90-40da-9b5e-0ff4f05b0965.png)

what exactly do you to do with the game, extract cg or get 8 bit key?
