### ISSUE TITLE
It would be possible to add file support (.rar)

### ISSUE THREAD

**Issue by EAxp3** [morkt/GARbro#55]
Using the library of:

[sharpcompress](https://github.com/adamhathcock/sharpcompress)

[rar](https://github.com/adamhathcock/sharpcompress/tree/master/src/SharpCompress/Archives/Rar)

**Comment by morkt** [comment]
nah, just use winrar.

**Comment by EAxp3** [comment]
But with WinRAR you have to extract and with GARbro not.

What I like about GARbro is the preview of the files inside a file.

I'll see if I can create the implementation myself.
:(

**Comment by flying-neko** [comment]
XnView, HoneyView or ComicsViewer_chn might be better for reading compressed comics.
