### ISSUE TITLE
Help! Can't extract from マガツバライ X-rated(PKWARE Archive Format)

### ISSUE THREAD

**Issue by fkvldh** [morkt/GARbro#551]
VNDB: https://vndb.org/r92868
Developer: light
Engine: PKWARE archive format(?)
Extension: .dat

Ok... I really don't know what engine is it.
GARbro said it's PKWARE archive format(same engine 一途な（処女→）彼女と恋したい[?]).
Anyone help me?

download: [data_12.zip](https://github.com/morkt/GARbro/files/9292658/data_12.zip)

**Comment by Chenx221** [comment]
.Dat files can be opened with common decompression software (such as 7zip), and the decompression password is _IrsysPack_CipherKey_
You can take a look at this post (may need to log in) [link](https://bbs.kfpromax.com/read.php?tid=955367&sf=2f4&keyword=%A5%DE%A5%AC%A5%C4%A5%D0%A5%E9%A5%A4)

**Comment by fkvldh** [comment]
> .Dat files can be opened with common decompression software (such as 7zip), and the decompression password is _IrsysPack_CipherKey_ You can take a look at this post (may need to log in) [link](https://bbs.kfpromax.com/read.php?tid=955367&sf=2f4&keyword=%A5%DE%A5%AC%A5%C4%A5%D0%A5%E9%A5%A4)

Thank you!

**Comment by Aleisster** [comment]
> .Dat files can be opened with common decompression software (such as 7zip), and the decompression password is _IrsysPack_CipherKey_ You can take a look at this post (may need to log in) [link](https://bbs.kfpromax.com/read.php?tid=955367&sf=2f4&keyword=%A5%DE%A5%AC%A5%C4%A5%D0%A5%E9%A5%A4)

Hi Chenx221. Excuse me, do you know how to repack/compress again the files?
