### ISSUE TITLE
Yome no Imouto to no In'ai encryption parameters?

### ISSUE THREAD

**Issue by GeeTwentyFive** [morkt/GARbro#552]
What are the parameters (hash, values[], pos, and count) used for encrypting and decrypting the .xp3 archive for Yome no Imouto to no In'ai in "ArcFormats/KiriKiri/CryptAlgorithms.cs, line 302 HashCrypt class Decrypt() function"? Thanks!!

**Comment by Cosetto** [comment]
> What are the parameters (hash, values[], pos, and count) used for encrypting and decrypting the .xp3 archive for Yome no Imouto to no In'ai in "ArcFormats/KiriKiri/CryptAlgorithms.cs, line 302 HashCrypt class Decrypt() function"? Thanks!!

It's hashcrypt so it's hard to tell, all encryption scheme are stacked in [Formats.dat](https://github.com/morkt/GARbro/tree/master/ArcFormats/Resources) so you will need a tool to read Formats.dat like [this](https://github.com/crskycode/GARbro/tree/master/SchemeTool) or something Idk

**Comment by Cosetto** [comment]
Example of hashcript [link](https://github.com/jszhtian/Krkr-engine/blob/master/Krkr2Packer/xp3enc/xp3enc/xp3enc.cpp)

**Comment by GeeTwentyFive** [comment]
THANK YOU!!! :D

**Comment by GeeTwentyFive** [comment]
Uh- one more question: Is the HashCrypt encryption done _before_ creating the .xp3 archive or _after_?

**Comment by Cosetto** [comment]
> Uh- one more question: Is the HashCrypt encryption done _before_ creating the .xp3 archive or _after_?

You need xp3enc.dll first to create Hascrypt for xp3 archive

**Comment by Cosetto** [comment]
actually you don't need to create encrypted archive, use [this one](https://github.com/arcusmaximus/KirikiriTools) , download xp3pack and versiond.ll(61kb). Create a patch folder and put all file in there and drag to xp3pack. Finally, move patch.xp3 and version.dll to game folder and version.dll will force the game to read without encrpytion

**Comment by GeeTwentyFive** [comment]
Thanks again!! :D
