### ISSUE TITLE
hanahime*absolute!

### ISSUE THREAD

**Issue by jackwaecow** [morkt/GARbro#555]
Hey Morkt, I tried to use GARbro to extract the script for hanahime*absolute!, but when I repack it, the game won't start afterwards, repacked size is very different too.

**Comment by Cosetto** [comment]
The brand is mirai so the engine must be non color(aka whale engine), and as you see, GARbro doesn't support to repack that engine

**Comment by jackwaecow** [comment]
> The brand is mirai so the engine must be non color(aka whale engine), and as you see, GARbro doesn't support to repack that engine

is there any tool that is able to repack it?
