### ISSUE TITLE
A question in unpacking Riddle Joker

### ISSUE THREAD

**Issue by Refrain69** [morkt/GARbro#569]
The "Riddle Joker" encryption method has already been included in GARbro.
However,when I click a .xp3 file,it opens directly and don't ask me to choose one encryption method.As a result,the files inside cannot be extracted properly.Both the original version and the Mod one have this problem.
Could you please make some improvement?
![屏幕截图 2022-12-25 133530](https://user-images.githubusercontent.com/121091208/209458005-55b905f4-6fd1-4374-87ad-7032f66235e6.png)

**Comment by Refrain69** [comment]
I guess maybe every time opening the .xp3 file,GARbro should allow the user to choose the encryption method manually(even it's not encrypted),instead of deciding its encryption automatically first.

**Comment by crskycode** [comment]
Just change EXE name

**Comment by Refrain69** [comment]
It works!Thank you.
I was a stupid:-(
