### ISSUE TITLE
Can't open Majiro v0003 / decrypt .rct

### ISSUE THREAD

**Issue by DennisWeyrauch** [morkt/GARbro#57]
Can't open .arc from Chuablesoft (i.e. Noblesse of Rouge), and after figuring out with arc_unpacker, weren't able to find any key in start.mjo (after manually feeding it to the "FindImageKey" function and trying around a bit)

**Comment by morkt** [comment]
please be more specific. what do you mean by "can't open .arc"? archives can't be browsed or images aren't displayed? what game and what release, exactly? for me everything works fine, at least in Noblesse of Rouge.

**Comment by DennisWeyrauch** [comment]
I meant as in unable to decrypt the rct files. And the GUI didn't work at all for me, so I had to use other means to unpack the .arc.

**Comment by morkt** [comment]
then you're doing something wrong. majiro archives as well as RCT images are and were fully supported for a very long time. maybe you're [experiencing this issue.](https://github.com/morkt/GARbro/issues/20) other than that i'm afraid i'll be unable to help you.

**Comment by morkt** [comment]
closing as insubstantial.
