### ISSUE TITLE
Krkrz repacking/packing problem

### ISSUE THREAD

**Issue by Refrain69** [morkt/GARbro#570]
xp3 files in many krkrz galgames such as ATRI,真愛の百合は赤く染まる,can be extracted perfectly,but I can't make patch.xp3 or repack evimage.xp3/data.xp3 with GARbro or the mod one even if I choose the right encryption method.
By "keep directory structure",I made a new data.xp3,but the game cannot find startup.tjs.The patch.xp3 also didn't work……
Maybe it's because the .sig file?Or I should integrate this patch folder with universal patch.exe?Maybe there're some other tools for packing?

**Comment by crskycode** [comment]
The krkrz game uses a special xp3 format. GARbro can only create the normal krkr2 xp3 format, and krkrz game can't read it. If you want to simplify make a patch you can try [KirikiriTools](https://github.com/arcusmaximus/KirikiriTools)

**Comment by Refrain69** [comment]
Still doesn't work……His xp3pack might just create unencrypted xp3.
But surprisingly,krkrextract1.0.3.1 seems to work.
e.g.DitzyDemons（与我恋爱的废柴恶魔）;5分钟的邂逅！时间停止与不可避免的命运
However,as for 真愛の百合は赤く染まる,everything goes well except the game title……
![屏幕截图 2022-12-25 194433](https://user-images.githubusercontent.com/121091208/209466657-33771c57-4bf2-4e7b-89a0-50b34bddb303.png)
So I tried to edit data.xp3 directly but failed……
Anyway,thank you very much.

**Comment by Cosetto** [comment]
> Still doesn't work……His xp3pack might just create unencrypted xp3. But surprisingly,krkrextract1.0.3.1 seems to work. e.g.DitzyDemons（与我恋爱的废柴恶魔）;5分钟的邂逅！时间停止与不可避免的命运 However,as for 真愛の百合は赤く染まる,everything goes well except the game title…… ![屏幕截图 2022-12-25 194433](https://user-images.githubusercontent.com/121091208/209466657-33771c57-4bf2-4e7b-89a0-50b34bddb303.png) So I tried to edit data.xp3 directly but failed…… Anyway,thank you very much.

Use release version 1.3 as patch.xp3, version 1.4 is for Wamsoft encryption

**Comment by Refrain69** [comment]
Seem not work either……
Maybe Universal Patch and ProjectDir folder is a better choice……
![屏幕截图 2022-12-26 093537](https://user-images.githubusercontent.com/121091208/209488594-fadbc603-97cc-493a-8bef-4e5c51c9e5ad.png)
![屏幕截图 2022-12-26 093646](https://user-images.githubusercontent.com/121091208/209488650-2bfd6381-d44a-4c06-8a30-de418c9d43fa.png)

**Comment by Refrain69** [comment]
Aha I just found another way to edit the title so that the patch.xp3 made by krkrextract1.0.3.1 could fully function.
![屏幕截图 2022-12-26 110144](https://user-images.githubusercontent.com/121091208/209494318-84538de0-0553-4552-a539-efd1158465eb.png)
Thanks for your help~~
