### ISSUE TITLE
New Renpy game that GARbro can't read

### ISSUE THREAD

**Issue by RedEye13** [morkt/GARbro#571]
Hi I found this new Renpy game and GARbro couldn't open the rpa archives

Game [link](https://vndb.org/v39954)

I also uploaded one of the files if you need an example
[scripts.zip](https://github.com/morkt/GARbro/files/10311743/scripts.zip)

**Comment by Cosetto** [comment]
GARbro only read Renpy version of Katawa Shoujo, to unpack new Renpy, you have to use unren, can be found on f95

**Comment by RedEye13** [comment]
Thanks, dude I do know of it, it's just I was hoping I can use GARbro since that tool is very messy since it decompiles everything so I was just hoping maybe someone might add the newer Renpy games support for GARbro if the dev period has stopped just tell me and I'll just close the issue

**Comment by Cosetto** [comment]
Seems like noody gonna upgrade Renpy to GARbro, so you  nees to find another tools
