### ISSUE TITLE
[Game Request] ネコと女子寮せよ！ Neko to Wakai Seyo!

### ISSUE THREAD

**Issue by aiueo5000** [morkt/GARbro#574]
VNDB: https://vndb.org/v33494
Developer: CUBE
Engine: krkr
Extension: .xp3

KrkrExtract does not work well, so wishing GARbro to extract its data. 🙏

**Comment by Chenx221** [comment]
You can try to extract the resources using the following two tools
https://github.com/xmoezzz/KrkrzExtract or
https://github.com/crskycode/GARbro/releases

**Comment by Cosetto** [comment]
GARbro mod of Crsky should work since he added Neko Wakai's crypt

**Comment by aiueo5000** [comment]
@Chenx221 @Cosetto 
Succeeded to extract data by  [crskycode/GARbro/releases](https://github.com/crskycode/GARbro/releases). 
Thanks a lot.
