### ISSUE TITLE
[Game Request] ろけらぶ - 同棲×後輩

### ISSUE THREAD

**Issue by Refrain69** [morkt/GARbro#575]
Name:ろけらぶ - 同棲×後輩 / Loca Love - Dousei x Kouhai / 恋爱定位Location Love同居×后辈
VNDB:https://vndb.org/v23067
Developer:Frontwing
Engine:krkrz
Extension:xp3
Download link:https://pan.baidu.com/s/1wPKg_KsBiZpXXXhpQYRh4A 提取码: x2sh

This game has been included in GARbro,but the .xp3 files cannot be decompressed properly.

kirikiritools:not work
krkrextract:stuck at one point when unpacking vol1.xp3
krkrzextract:work
krkrdump:not work 
![屏幕截图 2023-01-11 225049](https://user-images.githubusercontent.com/121091208/211837231-fb686ed3-30e4-47ed-813f-2a8040bc8dff.png)

**Comment by crskycode** [comment]
Rename EXE then open XP3 with GARbro (No Crypt)

**Comment by Refrain69** [comment]
Thank you very much.
