### ISSUE TITLE
Sabbat of the Witch [Steam] support

### ISSUE THREAD

**Issue by azulika** [morkt/GARbro#577]
I've tried to unpack Sabbat of the Witch (Steam version), but it doesn't seem to work. Apparently there are two types of decryption methods for this game, named Sabbat of the Witch and Sanoba Witch, but both of them did not work.
Is the steam version not supported yet, or is it just me?

**Comment by Chenx221** [comment]
@azulika 
It looks like the current Garbro does not support the steam version of this game. But you can still extract the files via KrkrExtract.
![Screenshot_20230119-235102_Microsoft Remote Desktop~01.png](https://user-images.githubusercontent.com/21092976/213491678-f8070017-ae4d-42fb-924d-b25b2ddee683.png)

![Screenshot_20230119-235522_Microsoft Remote Desktop~01.png](https://user-images.githubusercontent.com/21092976/213491815-b68385a5-514c-4ccf-a7ba-2450f423f50d.png)

**Comment by azulika** [comment]
@Chenx221 Thanks!!
