### ISSUE TITLE
[Game Request] アマカノ2  Amakano 2

### ISSUE THREAD

**Issue by aiueo5000** [morkt/GARbro#578]
VNDB: https://vndb.org/v26307
Developer: あらざしそふと Azarashi Soft 
Engine: cs2
Extension: .int

I used previous Amakano series to decrypt `pcm_AA.int` by GARbro. But they do not decrypt all voice files(`.ogg`).
I want to get all voice files in `pcm_AA.int` by GARbro.🙏

**Comment by Chenx221** [comment]
@aiueo5000 
GARbro should be able to extract the audio files for this game properly.
![image1](https://user-images.githubusercontent.com/21092976/213682230-388fe8fd-3857-4b54-9573-3c78198eb9cf.png)
![image2](https://user-images.githubusercontent.com/21092976/213682253-4093d1c9-efa3-4842-acc5-fa9cc8c30b9f.png)

**Comment by aiueo5000** [comment]
@Chenx221 
I also succeeded.  Thanks so much❗️
