### ISSUE TITLE
Game request:	Fit Shichao! ~Toshiue Josei to Asedaku Lesson Hatsutaiken~

### ISSUE THREAD

**Issue by AlchemistofAtlas** [morkt/GARbro#58]
https://vndb.org/v20369

While it uses CSystem, it also requires PlayDRM (I don't know if that influences.)

![screenshot_6](https://cloud.githubusercontent.com/assets/20749122/24326158/c891e9e0-116d-11e7-9c37-e2d73d86bb48.png)
![screenshot_7](https://cloud.githubusercontent.com/assets/20749122/24326157/c88ebdce-116d-11e7-905e-007bf3a5ea73.png)

**Comment by morkt** [comment]
added and updated pre-release version.

**Comment by AlchemistofAtlas** [comment]
Ok, tested it and at least the appendix files can be viewed. I suppose this being the pre-release indicates the Arc05/06.dat files have yet to be accessed.

**Comment by morkt** [comment]
no, you should have game properly installed to access them.

**Comment by AlchemistofAtlas** [comment]
Properly installed? I think I don't understand that part. I installed it all accordingly.

**Comment by AlchemistofAtlas** [comment]
Ok, it worked now. Thank you.
