### ISSUE TITLE
(malie)Triangle Love -アプリコットフィズ-, help extract

### ISSUE THREAD

**Issue by mymzc4njm** [morkt/GARbro#585]
Triangle Love -アプリコットフィズ-
https://vndb.org/v19445
campus
malie engine
.dat file

Sadly, morkt is not updating this game in the past.
GARbro, exdieslib doesn't work.
If you know something, please help me.

**Comment by Cosetto** [comment]
Try asking in https://github.com/Dir-A/MalieTools
