### ISSUE TITLE
YPF - Maggot baits - Can't repack cg.ypf - missing 8 bit key

### ISSUE THREAD

**Issue by Il-Sette** [morkt/GARbro#586]
Hi, I'm having problems with a YPF file: I was able to extract the archive, however I can't repack it because I don't know the 8 bit key.
I managed to get the version with https://github.com/Xorboth/YPF-Manager
but it gives me "Filename Encrypt Key: 00"
I also tried on other games like Euphoria, the version changes but the key remains "00"

I've seen from other requests that there is a program called "AE" but I haven't found it anywhere.
Can somebody help me?

Thanks in advance

Info:
VNDB: https://vndb.org/v18077
Japanese Title: マゴット ベイツ
file: cg.ypf
version: 481

**Comment by Cosetto** [comment]
Ypfmanager doesn't need key to repack
Don't try to repack cg.ypf, but instead create update1.ypf, update2.ypf, etc with the version of ypf you get. Make sure the folder structure of update1.ypf is correct
For example in cg.ypf you have cg.ypf>bg>files, so update1.ypf should be update1.ypf>bg>files

**Comment by Il-Sette** [comment]
i feel stupid now... i tried a thousand times with a thousand Tools but it never worked. Sometimes it wouldn't open the game, other times it wouldn't open the CGs. I already tried as you said but it never worked. However this time it worked (probably I was doing something wrong). thank you <3

[the request can be closed]
