### ISSUE TITLE
Help, the layer contained in the mtn file has an illegal file name, so it cannot be exported

### ISSUE THREAD

**Issue by jxLYH6134** [morkt/GARbro#587]
The Tenshi Souzou RE-BOOT!'s data.xp3/motion/title_bg.mtn has these special character file name which is not allowed by Windows.
![image](https://user-images.githubusercontent.com/48689047/230011146-57354c38-16e0-43da-818b-7ad52429e723.png)
I can't rename when exporting, so I get this error.
![image](https://user-images.githubusercontent.com/48689047/230011532-920d9d78-9dd9-4920-8ac2-2a003c8537a5.png)
I tried to find this character in the HEX editor and destroy it, but failed

**Comment by Chenx221** [comment]
You can extract the files you want correctly using [this tool](https://github.com/UlyssesWu/FreeMote/releases/tag/v3.5.0).
![2023-04-05_161411](https://user-images.githubusercontent.com/21092976/230022362-59b50836-8fb4-4ab1-9245-8ecf190b27cf.jpg)

**Comment by jxLYH6134** [comment]
> You can extract the files you want correctly using [this tool](https://github.com/UlyssesWu/FreeMote/releases/tag/v3.5.0). ![2023-04-05_161411](https://user-images.githubusercontent.com/21092976/230022362-59b50836-8fb4-4ab1-9245-8ecf190b27cf.jpg)

I really appreciate your help and the solution you provided works perfectly. I'm glad to hear that I'm not the only one who has encountered this problem, and your response has been incredibly helpful.
