### ISSUE TITLE
ELF .MES file script format

### ISSUE THREAD

**Issue by marconii2002** [morkt/GARbro#59]
Can you add support for ELF .mes game script files ? I want extract text from this files.

**Comment by morkt** [comment]
highly unlikely. first of all, gameres library lacks infrastructure for scripts conversion, so it has to be implemented. second, reverse-engineering script interpreters is a tiresome and time-consuming process, unlike with images and audio. try it yourself sometime with a game of your choice. attach to a running game with debugger and try to figure out, how binary scripts are interpreted. with images and audio it's a straight-forward process and usually boils down to a single routine that converts data to RGB pixels or PCM samples. script interpreters, on the other hand, are much more complex and code is usually dispersed among hundreds subroutines, and if it's written on C++ with heavy use of virtual functions, deciphering it all might take quite a time.

so no, i'm not willing to spend my time on it.

**Comment by 0xh3LL0** [comment]
there is a [tools](https://github.com/regomne/lneditor) for that, next time use github advance search...

**Comment by morkt** [comment]
then use that tool and bother me further.
