### ISSUE TITLE
[Game Request] Criminal Border

### ISSUE THREAD

**Issue by Reoreii** [morkt/GARbro#593]
VNDB: https://vndb.org/v37116
Developer: Purple software
Engine: KiriKiri
Extension: .xp3

I can't get past the encryption with either the regular version or the modded version of GARbro.

**Comment by Chenx221** [comment]
The modified version of Garbro hasn't been updated for a while, so now you can only extract files using tools like [KrkrzExtract](https://github.com/xmoezzz/KrkrzExtract/releases/tag/1.0.0.0).
