### ISSUE TITLE
[Game Request] Enrenchuu no Toshishita Kanojo ga Onna ni Ueta Osuzaru-domo no Gakuen de Koubi Aite ni Sareteta.

### ISSUE THREAD

**Issue by wilgotenk** [morkt/GARbro#596]
vndb : [https://vndb.org/v36017](https://vndb.org/v36017)
Developer: Soft Circle Courreges
Engine: KiriKiri
Extension: .xp3

**Comment by Cosetto** [comment]
https://github.com/xmoezzz/KrkrExtract
