### ISSUE TITLE
[Game Request] ましろ色シンフォニー SANA EDITION Mashiro-iro Symphony: Sana Edition

### ISSUE THREAD

**Issue by SanLukaku** [morkt/GARbro#597]
VNDB: https://vndb.org/v37651
Developer: Palette
Engine: kirikiri
Extension: .xp3

**Comment by Cosetto** [comment]
https://github.com/crskycode/GARbro/commits/master
As your wish, but don't expect much because Wamsoft need a Hash list extracted by Krkrdump to display correct names on Garbro

**Comment by SanLukaku** [comment]
Np. Thanks so much Bud.
