### ISSUE TITLE
[Game Request] 鬼ごっこ！／鬼ごっこ！ファンディスク

### ISSUE THREAD

**Issue by Uduru0522** [morkt/GARbro#598]
Game: [鬼ごっこ！](http://www.alcot.biz/product/oni_gokko/) / [鬼ごっこ！ファンディスク](http://www.alcot.biz/product/oni_fd/index.html)
Developer: ALcot
Engine: kirikiri
Extension: .xp3 / .xp3.sig

**Comment by Cosetto** [comment]
https://github.com/crskycode/GARbro/
Already added in Garbro mod

**Comment by Cosetto** [comment]
Or you can simply use krkrextract

**Comment by Uduru0522** [comment]
Not the fandisc though I think?

**Comment by Cosetto** [comment]
Though you can simply use [Krkrextract](https://github.com/xmoezzz/KrkrExtract), you don't really need to wait for GARbro update

**Comment by Uduru0522** [comment]
True, but what I want to do is to edit the xp3 package (those signature might be a problem tho)

**Comment by Cosetto** [comment]
Well, use this then https://github.com/arcusmaximus/KirikiriTools

**Comment by Uduru0522** [comment]
What I want to do has nothing to do with the text
Since the EN release has uncensored CG but the game is in English, 
(which for my personal preference I really don't feel confortable reading English when playing novel games)
I wanted to move the uncensored CGs into the Japanese release of the game.

Anyway, thanks alot, gonna close the issue 🙇
