### ISSUE TITLE
TEST--Error open archive .gyu

### ISSUE THREAD

**Issue by EAxp3** [morkt/GARbro#6]
Hi

GARbro-master-(GyuReader) use Binary.CopyOverlapped
![error1](https://cloud.githubusercontent.com/assets/15073580/10918679/a3b03414-822c-11e5-9708-ac75e8516121.PNG)

GARbro-master-implemented GYU image format
![error1](https://cloud.githubusercontent.com/assets/15073580/10918721/dcb78e38-822c-11e5-9eda-4911f787ead1.PNG)

Please let me know if you get my mail,
to continue to help

More information
on file .rar

Thank you
I hope the problem is solved
bye 😊💻

link .rar 
https://mega.nz/#!k0ojlAjS!CNeg-OPh91I_45smFmR17-Uhj3yHGl_lwFnQm-fIqWY

contact email: ichikuro95@hotmail.com

**Comment by morkt** [comment]
fixed it.
