### ISSUE TITLE
[Game Request] Kuro Ai ~Ichiya Saikan - Inkou Rannyuuroku~ HD Remaster

### ISSUE THREAD

**Issue by Vincent-Dawn** [morkt/GARbro#600]
vndb: [https://vndb.org/r65221](https://vndb.org/r65221)
Developer: CLOCKUP
Engine: PIX STUDIO
Extension: .bin

This game and few others have two bin files that come with it with one named after game's application file and titled pix. I tried mounting them but when I try to click on them my computer says:

"The disc might be corrupt. Make sure that the disc uses a format that Windows recognizes. If the disc is unformatted you need to format it before using it."

When I tried using Garbro it says none of them can be opened as resource archive and when tried typing the virtual drive port where the bin files are mounted in Garbro's address section it says volume does not contain a recognized file system.

**Comment by Cosetto** [comment]
[PIXUnpack.zip](https://github.com/morkt/GARbro/files/12471382/PIXUnpack.zip)

**Comment by Vincent-Dawn** [comment]
Thank you, it's works like Krkrextract does, except you don't have to have the game running while unpack the files.
