### ISSUE TITLE
Request: Add support for minori's Trinoline

### ISSUE THREAD

**Issue by sakuhanachan** [morkt/GARbro#61]
[Trinoline (トリノライン)](https://vndb.org/v19644)
Engine: Musica
file extension: .paz, .pazA, .pazB

**Comment by mireado** [comment]
You can try this binary
http://tieba.baidu.com/p/5051664815

https://github.com/Inori/FuckGalEngine/tree/master/Minori/Minori/fuckpaz

**Comment by morkt** [comment]
updated formats database. you can download it using "check for updates" app menu.

**Comment by EAxp3** [comment]
👍 :mexico:
