### ISSUE TITLE
The ability to create .pack archives, not just read them.

### ISSUE THREAD

**Issue by Nelyfa** [morkt/GARbro#622]
I would like to see the ability to create .pack archives in this program, as currently it only has the capability to read archives of this format.
For example, .pack archives are used in the game "Tsuki ni Yorisou Otome no Sahou". It's frustrating that we can only read .pack archives but not create them.

**Comment by Cosetto** [comment]
There're some hidden tools to create .pack of Qlie. In fact, the engine itself can read without repack, we just need to patch the exe.
