### ISSUE TITLE
Crash in Windows 10 Creators Update

### ISSUE THREAD

**Issue by LaaZa** [morkt/GARbro#63]
The application crashes at startup after splashscreen in Creators Update for Windows 10.
Possibly 'Access Violation', tried running admin and from different locations, same result.

Windows version: 1703
OS Build: 15063.13

**Comment by morkt** [comment]
"New with the Windows 10 Creators Update: Windows 10 keeps getting better"

fuck windows 10 and fuck creators update. i don't care.

**Comment by LaaZa** [comment]
Interesting, I built it myself and it works.

**Comment by mireado** [comment]
@LaaZa How did you resolve that?
I should like to have the benefit of your advice.
Could you please help with this?

**Comment by LaaZa** [comment]
@mireado I didn't do really anything else than build it in visual studio, maybe I had newer Dependencies or something.

**Comment by LaaZa** [comment]
Issue seems to be fixed with the 1.4.28 release

**Comment by morkt** [comment]
good to now. i've just updated nuget packages.
