### ISSUE TITLE
Data not recoginzed as zlib-compressed stream

### ISSUE THREAD

**Issue by Yukinacchi** [morkt/GARbro#636]
Idk what is the problem here, im trying to extract files from a new visual novel called Seifuku kanojo and its a pac file, when i tried to open it, it appeared, but i cant open or see it, it just says on the bottom left corner "Data not recoginzed as zlib-compressed stream" Im am new trying this software, do i need to request to add the game so it can support it? Or it need to be unpacked to be readed? I tried soo many method to unpack the pac file and every single time it didnt work, i was going insane doing it. Pls help me :(

https://store.steampowered.com/app/2673490/Seifuku_Kanojo/

**Comment by sora324** [comment]
Seem issue on アイキスFD 七瀬アフター,both NeXAS(Giga) engine.It's because the files(at least audio,image,.etc) inside the pac archive are actually not zlib-compressed,but raw.You may try to modify the source code and compile it yourself.Or you can try some other tools around.
<img width="597" alt="1" src="https://github.com/user-attachments/assets/cd4f9fa4-e82d-4e5d-bc1e-ca6a06ca9ca4">

**Comment by sora324** [comment]
You can try this [fork](https://github.com/Refrain69/GARbro).Maybe it works.

**Comment by Yukinacchi** [comment]
How do i use it? I dont know how to use the fork

**Comment by sora324** [comment]
Alright……you can download release now.

**Comment by Yukinacchi** [comment]
Thanks bro, it works, you are a lifesaver holy sh*t. Are you jesus? 😂 anyways thank you very much

**Comment by sora324** [comment]
I made a mistake.Actually,the compression method is zstd(implied by the sign 0x00000007),but not every file is compressed,like ogg,etc.There are "unpacked file size" and "packed file size" in every entry in the archive,which imply whether the file specified is compressed.You can try the latest release of [Crsky's fork](https://github.com/crskycode/GARbro/releases/tag/GARbro-Mod-1.0.1.4) or [GalArc](https://github.com/detached64/GalArc).

**Comment by Yukinacchi** [comment]
> I made a mistake.Actually,the compression method is zstd(implied by the sign 0x00000007),but not every file is compressed,like ogg,etc.There are "unpacked file size" and "packed file size" in every entry in the archive,which imply whether the file specified is compressed.You can try the latest release of [Crsky's fork](https://github.com/crskycode/GARbro/releases/tag/GARbro-Mod-1.0.1.4) or [GalArc](https://github.com/detached64/GalArc).

Thank you for pointing out, ill try to extract the game again after this 🙏
