### ISSUE TITLE
Request: ORCSOFT Kirikiri unpack&pack

### ISSUE THREAD

**Issue by mireado** [morkt/GARbro#64]
[ORCSOFT] かがち様お慰め奉ります 寝取られ村淫夜噺
https://vndb.org/v10726

Engine: kirikiri 2.32.2.426
file extension: .xp3
This engine using '.tpm' file.

I had try to unencrypt.. but I have no idea to how to find key&using...
Could you please help this game?

Sorry to request minor game... T_T

**Comment by morkt** [comment]
try some other Orcsoft title from drop-down list, like "Dare mo ga Kanojo o Neratteru". as for packing, it might require some fixing of re-packing script files, further testing needed.

**Comment by mireado** [comment]
@morkt THX! It works! >_<
I love you>_< ♥♥♥♥♥

**Comment by morkt** [comment]
does repacking work, too?

**Comment by mireado** [comment]
YES, it works perfectly. >_<
