### ISSUE TITLE
Game Request: Grisaia Phantom trigger 2 is possible?

### ISSUE THREAD

**Issue by darkxex** [morkt/GARbro#75]
it use kirikiri z. is possible?

**Comment by morkt** [comment]
added and uploaded new pre-release.

**Comment by darkxex** [comment]
![image](https://user-images.githubusercontent.com/17991404/27601119-1bf33928-5b3c-11e7-9b8e-65ed11e77dcc.png)
man, still it is encrypted. if you can, check the diferences with krkrextract.

**Comment by morkt** [comment]
it works fine for me, you're doing something wrong.

**Comment by darkxex** [comment]
Would images, texts and everything have to appear?
If so, should I look for the directory of the game and press on extract to XP3 no?

**Comment by darkxex** [comment]
![image](https://user-images.githubusercontent.com/17991404/27619530-1594752e-5b91-11e7-887f-0bc868426ffb.png)
all is okay. thanks.

**Comment by merseus** [comment]
por que da este error cuando intento  empaquetar  
![sin titulo](https://user-images.githubusercontent.com/29648632/29147505-6c884ac0-7d35-11e7-82d5-4e915eb9195c.png)
