### ISSUE TITLE
Game request: Ore Yome!?

### ISSUE THREAD

**Issue by marconii2002** [morkt/GARbro#79]
https://vndb.org/v20679

Can you add support for this game ?

**Comment by marconii2002** [comment]
When this game will be added ?

**Comment by morkt** [comment]
i can't tell.

**Comment by Neroldy** [comment]
@marconii2002 Hey man, keep patient and just wait :)
Or do it yourself and pull request

**Comment by marconii2002** [comment]
I requested this game on time writing this 24 days ago. Game use Csystem this same that Tinkerbell games so I thinked that it will be fast.

**Comment by morkt** [comment]
if you want to speed it up you could take a process dump of the running game (either with sysinternals process explorer or some debugger like ollydbg) and somehow make it available to me.

**Comment by marconii2002** [comment]
Sorry but game is protected by PlayDRM so now is impossible to rip this game.

**Comment by Haiyami** [comment]
It's not impossible to rip. I have a ripped copy. What needs to be done is a crack.
