### ISSUE TITLE
Support for .PSM files

### ISSUE THREAD

**Issue by Ygnes** [morkt/GARbro#80]
Hello sorry if it's not too much trouble you could add support for .PSM files
Or could you explain how to extract this type of files

**Comment by morkt** [comment]
i have no idea. could you be more specific, where do you encounter them?

**Comment by Ygnes** [comment]
This type of files I found it in the game Omamagoto Hahaoya Shoujo to Chiyahoya Shippori of Peaky
![oma](https://user-images.githubusercontent.com/29958943/27960692-db0b9d70-62f1-11e7-8cb3-3c661e23e72d.png)
![oma2](https://user-images.githubusercontent.com/29958943/27960693-db0cf8fa-62f1-11e7-87e8-03394c0d7229.png)

**Comment by Neroldy** [comment]
@Ygnes Hey, man, psm file is not a archive, it just a png with modified sig. So just need the one more step, use any hex editor, 
find "ed 50 4e 47" --> "89 50 4e 47"
then rename psm to png.
That'it.
According to this blog:
https://blog.ztjal.info/acg/acg-data/galgame-unpack-record-2017-mayo-junio

**Comment by Ygnes** [comment]
@Neroldy thank you very much for solving my problem

**Comment by Neroldy** [comment]
@Ygnes You're welcome~
