### ISSUE TITLE
Game Issue: Karenai Sekai to Owaru Hana DL Edition

### ISSUE THREAD

**Issue by Pokom123** [morkt/GARbro#83]
Although it is in supported lists, I can't open it. It only shows invalid file format for me. So can you please check it?

**Comment by morkt** [comment]
please describe you issue in more details:
what version of GARbro are you using?
did you install it from zip archive or from executable installer?
could you show your game's directory structure, particularly sizes (in bytes) of *.xp3 archives? (something like #17)
do archives open at all, or is it just images that not showing up?

**Comment by Pokom123** [comment]
> GARbro Version 1.4.30.1898
> Installed from zip archive
> 
![image](https://user-images.githubusercontent.com/7065443/28511029-d291a5ec-707d-11e7-9111-ea91428d256c.png)
![image](https://user-images.githubusercontent.com/7065443/28511067-06f09eec-707e-11e7-8151-1e0327a94502.png)

**Comment by morkt** [comment]
DL release uses different encryption, i've updated formats database, you can download it using "help | check for updates" menu option. choose "Karenai Sekai to Owaru Hana DL" when prompted for encryption scheme.

**Comment by Pokom123** [comment]
Thanks! It's working fine now.
