### ISSUE TITLE
Game Request: The Labyrinth of Grisaia ~Unrated Version~

### ISSUE THREAD

**Issue by Leon-Regale** [morkt/GARbro#85]
https://vndb.org/r37935
Can you please add support for this game?
File extension is .int on CatSystem2 engine.

**Comment by morkt** [comment]
i've updated formats database, you can download it using "help | check for updates" menu option. choose "Labyrinth of Grisaia" when prompted for encryption scheme.

**Comment by Leon-Regale** [comment]
Works perfectly, thanks.
