### ISSUE TITLE
Game Request : Shiny Days JAST USA

### ISSUE THREAD

**Issue by Pokom123** [morkt/GARbro#86]
https://vndb.org/v7751
Do you think it is possible to add support for this game?
I heard crass can extract gpk file but I don't know how to use it.

**Comment by RndUser0** [comment]
I successfully extracted the GPKs with Crass (CrageGUI). To make it work, you have to specify the ShinyDays.exe file in the "param" textbox like this: exe=...\ShinyDays\shinydays.exe" ." See also the screenshot below.
![clipboard-1](https://user-images.githubusercontent.com/29837561/30633341-9c454656-9deb-11e7-996c-c1aff38b51d9.png)

**Comment by nicefunfungal** [comment]
Excuse me, I know this was 3 years ago, but I'd like to know if it was ever discovered how to repack the .GPK files!
