### ISSUE TITLE
Game Request: [NanaWind] [170630] Haruoto Alice ＊ Gram

### ISSUE THREAD

**Issue by plug784036529** [morkt/GARbro#87]
VNDB link: https://vndb.org/v19133
Developer: NanaWind
Release date: 170630
Original title: 春音アリス＊グラム
English title (if available): Spring is just around the corner., Harugra

xp3 files,
I tried Xp3Viewer and KrkrExtract .ect,but can't unpack it yet.
Ztjal's blog said 'Non-public tool'.

Hope GARbro of the next vision can unpack this game.

**Comment by EAxp3** [comment]
Add support Game in GARbro please :(
PlayDRM :(

**Comment by morkt** [comment]
added in recent release.

**Comment by EAxp3** [comment]
thanks

**Comment by Dominator56** [comment]
It doesn't seem to work for me, I tried to compile latest version of GARbro but no success.
I can browse archives and file names look correct, but previewing/extracting does not work as the format is invalid.

**Comment by morkt** [comment]
have you tried it with binary release, not compiling yourself?

**Comment by Dominator56** [comment]
Yes, I just downloaded and tried with the binary release you just added, still does not work
I can provide sample files if needed

**Comment by morkt** [comment]
use the release version (one with setup exe). pre-releases lack some supplementary data files required for this particular game.
