### ISSUE TITLE
Game Request : Fuyu Uso -Snow World End-

### ISSUE THREAD

**Issue by fdtggf** [morkt/GARbro#88]
[https://vndb.org/r51458](url)
Can you please add support for this game?
It used malie system.

**Comment by morkt** [comment]
it's supported already.

**Comment by Neroldy** [comment]
I still failed in the fuyu uso trail version...
also failed in the natsu uso trail version...
could not open the data.dat as archive file.

**Comment by morkt** [comment]
only full releases are supported.
