### ISSUE TITLE
question about CatSystem2 key

### ISSUE THREAD

**Issue by mireado** [morkt/GARbro#9]
"installed folder"\config\startup.xml
have vcode string.

Is vcode correct key on CatSystem2?
http://imgur.com/a/L2n8s
Hyper→Highspeed→Genius
WM-UR72BYNF

ウィッチズガーデン
WM-JFIGH0Q8

カミカゼ☆エクスプローラー！
CL-AS4F4PT0

I'm not sure that it is right, cause so different file name.
![Imgur](http://i.imgur.com/cLUTp5n.png)

**Comment by morkt** [comment]
looks like these games use some modified algorithm for file names obfuscation. keys are correct, otherwise images wouldn't be displayed. exact answer require reverse engineering of mentioned games, so it could take a while.

**Comment by morkt** [comment]
i was wrong, turns out your keys are actually incorrect. apparently those keys don't affect file contents encryption, only filename obfuscation.

so look for correct keys ;-)

**Comment by hiroshil** [comment]
the correct key is WM-QILQKHSK
