### ISSUE TITLE
Game Request: Yakimochi Stream

### ISSUE THREAD

**Issue by EAxp3** [morkt/GARbro#92]
[VNDB link:](https://vndb.org/v14888)
![evimage xp3-fail](https://user-images.githubusercontent.com/15073580/30246037-4885ea92-95b3-11e7-88ec-78b3ee5ed37f.JPG)

[DATA GAME](https://mega.nz/#!klhHlDyS!3X6kJEwo3vyCadh_GUcnJqZIdDUxPEhP7Ytzf5rErnU)

**Comment by morkt** [comment]
try latest pre-release.
