### ISSUE TITLE
Game Request : Make me lover

### ISSUE THREAD

**Issue by nanisise** [morkt/GARbro#95]
[Make Me Lover(メイクMeラバー)](https://vndb.org/v13060)

Engine: Kirikiri 2 v2.31.2013.411
File extension: .xp3
Vesion: GARbro v1.4.31.1915
Issue: the content of .ks and .tjs script files in .xp3 packages is mojibake, obviously it is encrypted. Is it possible to decrypt these script files?

**Comment by morkt** [comment]
game has several releases, what edition are you trying? did you select "Make Me Lover" in dropdown list when accessing XP3 files?

**Comment by nanisise** [comment]
Make Me Lover has may expansion pack, so my version is:
Make Me Lover - Package Edition + 
Make Me Lover Darkness - Package Edition + 
Make Me Lover Darkness L Body Plus Pack - Package Edition

And where is the "selection dropdown list"? I can't find it when accessing XP3 files.
Thank you.

**Comment by nanisise** [comment]
I read the README.txt, it say I will be asked for credentials or a supposed game title when archives are encrypted. I guess this is dropdown list you mentioned. But GAR Bro didn't ask me for that, so I can directly extract .tlg image files, but the script files still encrypted and can't be extract conrrectly

**Comment by morkt** [comment]
so images are displayed fine, but scripts are encrypted? i've never encountered kirikiri games with scripts encrypted differently from images. are you sure it's actually an encryption and not **character encoding**? script files could be either in SHIFT-JIS or UTF-16LE encodings. use some text editor that allows to open files in different encodings.

**Comment by nanisise** [comment]
Yes, I pretty sure it is not the issue about character encoding. Because even wrong character encoding, the script file still can be preview in GARbro, but in this case, it can't. Thus GARbro have no option to change encoding.

BTW, I also try other tools like KrkrExtract, there is the same problem in this tool. Although I reported the issue to the author of KrkrExtract, he still can't handle it. So maybe you can fix this issue.

**Comment by morkt** [comment]
the fact GARbro doesn't display text doesn't mean anything. its character encoding detection algorithm is rather silly, so UTF-16 files might not be properly detected. like i said, try some external text viewer/editor that allows to change encoding before drawing conclusions about wrong encryption.

**Comment by nanisise** [comment]
Well, this detail:
In data.xp3 the startup.tjs can be extract by GARBro even with wrong encoding, like this:
[Picture](https://imgur.com/kceCc5k)

But only starupt.tjs can be read, other script files can't be (ex. data.xp3\system\ActionData.tjs), like this:
[Picture](https://imgur.com/8b19e42)

And then I extract the unreadable script files, the context like this:
[Picture](https://imgur.com/pnNNMs8)

From the above picture, I don't this is the problem about wrong encoding. Because even with wrong encoding, the context of script file must be with some program language structure. But the extracted script file seems totally junk. I try to use notepad++ and any possible encoding, the script still be unreadable.

Thanks.

**Comment by morkt** [comment]
turns out scripts have been encrypted after all, i've updated a pre-release. take a note though that those TJS scripts are compiled into byte-code and you wont be able to read them unless you have some decompiler tools.

KS scripts on the other hand appear to be text in UTF-16 encoding after decryption.

**Comment by nanisise** [comment]
Hi, morkt, I've tested latest GARBro, and Yes, It can decrypt Script. For KS script, the decrypted UTF-16 file lack U+FEFF BOM, although It can be fixed by hex editor. For complied TJS file, the original kirrkiri2 main exe can't load it, I've read the kirrkiri2 devdoc, but still don't know how to load byte-code file. Do you have a plan to develop TJS2 decompiler?

Many thanks to you.

**Comment by morkt** [comment]
> Do you have a plan to develop TJS2 decompiler?

aboslutely not.

**Comment by Neroldy** [comment]
@nanisise Hey man, for krkr TR, first you should look at https://github.com/xmoeproject/KrkrExtract and author's other project.

**Comment by nanisise** [comment]
@Neroldy I've already used KrkrExtract before, but that tool can't even decrypted script file. I've reported this issue to author one year ago, but the latest version still is not fixed.

**Comment by Neroldy** [comment]
@nanisise Well, then use OD and decrypt yourself.

**Comment by morkt** [comment]
KiriKiriZ sources are open https://github.com/krkrz/krkrz/tree/master/tjs2, it's possible to write a decompiler based on them.
