### ISSUE TITLE
Game Request: Ouchi ni Kaeru made ga Mashimaro Desu

### ISSUE THREAD

**Issue by Gammokin** [morkt/GARbro#96]
[VNDB link](https://vndb.org/v20622)

Excuse me.
I tried to extract images from this game with GARbro v1.4.31.1915.
It can extract but can't merge images of ev.noa.
Can you add support for this game?
Thank you.

**Comment by morkt** [comment]
try new pre-release.

**Comment by Gammokin** [comment]
It works. Thank you!
