### ISSUE TITLE
Game request: Gibo no Shizuku ~Shimetta Hada kara Kaori Tatsu Amai Iroka~ 

### ISSUE THREAD

**Issue by AlchemistofAtlas** [morkt/GARbro#97]
https://vndb.org/v21239

Game has been released, but files can't be opened as resource archive. Can it be supported, please?

**Comment by morkt** [comment]
updated support in new pre-release.

**Comment by AlchemistofAtlas** [comment]
Works perfectly, Thank you.

**Comment by Lbzttt** [comment]
003069.b0 and 004465.b0 in Arc05 can't be extracted (Invalid file format).

**Comment by AlchemistofAtlas** [comment]
Ok, it recognizes the appendix files. It's cmpleted now. Thank you for the support.
