### ISSUE TITLE
can i request about re-achaive for CPZ for Purple Software

### ISSUE THREAD

**Issue by yorutoitskuki** [morkt/GARbro#99]
I have searched many tools about de-achaive and re-achaive
and YOUR tool is best ever I seen
so i think you can meke re-achaiving what i want
can you do my wish

**Comment by morkt** [comment]
see #65, this format utilizes quite complicated encryption, so implementing re-packing would be somewhat time-consuming and i don't have plans for it yet.

**Comment by yorutoitskuki** [comment]
oh, I see
Thanks to answer. ^^

**Comment by Neroldy** [comment]
@yorutoitskuki https://github.com/xmoeproject/CMVS-Engine

**Comment by morkt** [comment]
there's no CPZ packer in the project you referenced.

**Comment by Neroldy** [comment]
Oh, my fault...

**Comment by S0X-LT** [comment]
You still interested in that encryption method? I got some info on it. Granted, It's done in C++:

https://github.com/vn-tools/arc_unpacker/tree/master/src/dec/purple_software

This one is specific for .ps3 script files, but it should work for images and other files too:

>The custom LZSS decompression of Purple Software:

>https://github.com/vn-tools/arc_unpacker/blob/master/src/dec/purple_software/ps2_file_decoder.cc#L37-L76

>can be compared with the "stock" version of LZSS:

>https://github.com/vn-tools/arc_unpacker/blob/master/src/algo/pack/lzss.cc#L215-L258

>The same file, lzss.cc, also contains an encoder for stock LZSS. A quick glance at both of the decoders reveals that the only difference between them is the number and placement of bits used to store offsets and lengths of repetitions. This means you could copy the encoder as-is, and only tweak the way it outputs the computed repetition lengths.

>If you do not want to dive into LZSS too much, I guess you could also skip computing the repetitions altogether, and output something like "0xFF <8 raw bytes of input> 0xFF <8 raw bytes of input>" (give or take the script header ofc). The 0xFF marker here contains 8 control bits, each of which is set to 1, which means "copy the next byte from the source as-is" 8 times. It's trivial to code but I wouldn't use it for anything larger than scripts (e.g. SFX, GFX) cause the data size increase from this approach will be significant.

>Oh the other thing that's also different is the dictionary size and its initial offset

**Comment by morkt** [comment]
extaction is NOT what this issue is about. garbro can extract files from CPZ just fine. this issue is about REPACKING files back into archive, so your comment is irrelevant.

**Comment by S0X-LT** [comment]
No no, my comment explains how to make a repacker based on arc_unpacker's unpacking method.

By the way, I also got this: 
>my.mixtape.moe/mufvgp.7z

These are repacking tools specific to Chrono;Clock. Hope it helps.

**Comment by yorutoitskuki** [comment]
Sorry, i had been traffic accident
I woke and can move my fingers recently
Now i close this issue
Sorry too late

**Comment by S0X-LT** [comment]
Ah, sorry for bothering you then.
